openapi: 3.0.3
info:
  contact:
    name: ESI Support
    url: https://developers.eveonline.com/docs/support/
  license:
    name: EVE Developer License
    url: https://developers.eveonline.com/license-agreement
  termsOfService: https://support.eveonline.com/hc/en-us/articles/8414770561948-EVE-Online-Terms-of-Service
  title: EVE Stable Infrastructure (ESI) - tranquility
  version: 2025-11-06
servers:
- url: https://esi.evetech.net
tags:
- name: Alliance
- name: Assets
- name: Calendar
- name: Character
- name: Clones
- name: Contacts
- name: Contracts
- name: Corporation
- name: Corporation Projects
- name: Dogma
- name: Faction Warfare
- name: Fittings
- name: Fleets
- name: Incursions
- name: Industry
- name: Insurance
- name: Killmails
- name: Location
- name: Loyalty
- name: Mail
- name: Market
- name: Meta
- name: Planetary Interaction
- name: Routes
- name: Search
- name: Skills
- name: Sovereignty
- name: Status
- name: Universe
- name: User Interface
- name: Wallet
- name: Wars
paths:
  /alliances:
    get:
      description: List all active player alliances
      operationId: GetAlliances
      summary: List all alliances
      tags:
      - Alliance
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /alliances/{alliance_id}:
    get:
      description: Public information about an alliance
      operationId: GetAlliancesAllianceId
      summary: Get alliance information
      tags:
      - Alliance
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /alliances/{alliance_id}/contacts:
    get:
      description: Return contacts of an alliance
      operationId: GetAlliancesAllianceIdContacts
      security:
      - OAuth2:
        - esi-alliances.read_contacts.v1
      summary: Get alliance contacts
      tags:
      - Contacts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: alliance-social
        max-tokens: 300
        window-size: 15m
  /alliances/{alliance_id}/contacts/labels:
    get:
      description: Return custom labels for an alliance's contacts
      operationId: GetAlliancesAllianceIdContactsLabels
      security:
      - OAuth2:
        - esi-alliances.read_contacts.v1
      summary: Get alliance contact labels
      tags:
      - Contacts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: alliance-social
        max-tokens: 300
        window-size: 15m
  /alliances/{alliance_id}/corporations:
    get:
      description: List all current member corporations of an alliance
      operationId: GetAlliancesAllianceIdCorporations
      summary: List alliance's corporations
      tags:
      - Alliance
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /alliances/{alliance_id}/icons:
    get:
      description: |-
        Get the icon urls for a alliance

        This route expires daily at 11:05
      operationId: GetAlliancesAllianceIdIcons
      summary: Get alliance icon
      tags:
      - Alliance
      x-compatibility-date: 2020-01-01
  /characters/affiliation:
    post:
      description: "Bulk lookup of character IDs to corporation, alliance and faction"
      operationId: PostCharactersAffiliation
      summary: Character affiliation
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /characters/{character_id}:
    get:
      description: Public information about a character
      operationId: GetCharactersCharacterId
      summary: Get character's public information
      tags:
      - Character
      x-cache-age: 604800
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/agents_research:
    get:
      description: "Return a list of agents research information for a character.\
        \ The formula for finding the current research points with an agent is: currentPoints\
        \ = remainderPoints + pointsPerDay * days(currentTime - researchStartDate)"
      operationId: GetCharactersCharacterIdAgentsResearch
      security:
      - OAuth2:
        - esi-characters.read_agents_research.v1
      summary: Get agents research
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-industry
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/assets:
    get:
      description: Return a list of the characters assets
      operationId: GetCharactersCharacterIdAssets
      security:
      - OAuth2:
        - esi-assets.read_assets.v1
      summary: Get character assets
      tags:
      - Assets
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/assets/locations:
    post:
      description: "Return locations for a set of item ids, which you can get from\
        \ character assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)"
      operationId: PostCharactersCharacterIdAssetsLocations
      security:
      - OAuth2:
        - esi-assets.read_assets.v1
      summary: Get character asset locations
      tags:
      - Assets
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/assets/names:
    post:
      description: "Return names for a set of item ids, which you can get from character\
        \ assets endpoint. Typically used for items that can customize names, like\
        \ containers or ships."
      operationId: PostCharactersCharacterIdAssetsNames
      security:
      - OAuth2:
        - esi-assets.read_assets.v1
      summary: Get character asset names
      tags:
      - Assets
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/attributes:
    get:
      description: Return attributes of a character
      operationId: GetCharactersCharacterIdAttributes
      security:
      - OAuth2:
        - esi-skills.read_skills.v1
      summary: Get character attributes
      tags:
      - Skills
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/blueprints:
    get:
      description: Return a list of blueprints the character owns
      operationId: GetCharactersCharacterIdBlueprints
      security:
      - OAuth2:
        - esi-characters.read_blueprints.v1
      summary: Get blueprints
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-industry
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/calendar:
    get:
      description: "Get 50 event summaries from the calendar. If no from_event ID\
        \ is given, the resource will return the next 50 chronological event summaries\
        \ from now. If a from_event ID is specified, it will return the next 50 chronological\
        \ event summaries from after that event"
      operationId: GetCharactersCharacterIdCalendar
      security:
      - OAuth2:
        - esi-calendar.read_calendar_events.v1
      summary: List calendar event summaries
      tags:
      - Calendar
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/calendar/{event_id}:
    get:
      description: Get all the information for a specific event
      operationId: GetCharactersCharacterIdCalendarEventId
      security:
      - OAuth2:
        - esi-calendar.read_calendar_events.v1
      summary: Get an event
      tags:
      - Calendar
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    put:
      description: Set your response status to an event
      operationId: PutCharactersCharacterIdCalendarEventId
      security:
      - OAuth2:
        - esi-calendar.respond_calendar_events.v1
      summary: Respond to an event
      tags:
      - Calendar
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/calendar/{event_id}/attendees:
    get:
      description: Get all invited attendees for a given event
      operationId: GetCharactersCharacterIdCalendarEventIdAttendees
      security:
      - OAuth2:
        - esi-calendar.read_calendar_events.v1
      summary: Get attendees
      tags:
      - Calendar
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/clones:
    get:
      description: A list of the character's clones
      operationId: GetCharactersCharacterIdClones
      security:
      - OAuth2:
        - esi-clones.read_clones.v1
      summary: Get clones
      tags:
      - Clones
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-location
        max-tokens: 1200
        window-size: 15m
  /characters/{character_id}/contacts:
    delete:
      description: Bulk delete contacts
      operationId: DeleteCharactersCharacterIdContacts
      security:
      - OAuth2:
        - esi-characters.write_contacts.v1
      summary: Delete contacts
      tags:
      - Contacts
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    get:
      description: Return contacts of a character
      operationId: GetCharactersCharacterIdContacts
      security:
      - OAuth2:
        - esi-characters.read_contacts.v1
      summary: Get contacts
      tags:
      - Contacts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    post:
      description: Bulk add contacts with same settings
      operationId: PostCharactersCharacterIdContacts
      security:
      - OAuth2:
        - esi-characters.write_contacts.v1
      summary: Add contacts
      tags:
      - Contacts
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    put:
      description: Bulk edit contacts with same settings
      operationId: PutCharactersCharacterIdContacts
      security:
      - OAuth2:
        - esi-characters.write_contacts.v1
      summary: Edit contacts
      tags:
      - Contacts
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/contacts/labels:
    get:
      description: Return custom labels for a character's contacts
      operationId: GetCharactersCharacterIdContactsLabels
      security:
      - OAuth2:
        - esi-characters.read_contacts.v1
      summary: Get contact labels
      tags:
      - Contacts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/contracts:
    get:
      description: "Returns contracts available to a character, only if the character\
        \ is issuer, acceptor or assignee. Only returns contracts no older than 30\
        \ days, or if the status is \"in_progress\"."
      operationId: GetCharactersCharacterIdContracts
      security:
      - OAuth2:
        - esi-contracts.read_character_contracts.v1
      summary: Get contracts
      tags:
      - Contracts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-contract
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/contracts/{contract_id}/bids:
    get:
      description: Lists bids on a particular auction contract
      operationId: GetCharactersCharacterIdContractsContractIdBids
      security:
      - OAuth2:
        - esi-contracts.read_character_contracts.v1
      summary: Get contract bids
      tags:
      - Contracts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-contract
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/contracts/{contract_id}/items:
    get:
      description: Lists items of a particular contract
      operationId: GetCharactersCharacterIdContractsContractIdItems
      security:
      - OAuth2:
        - esi-contracts.read_character_contracts.v1
      summary: Get contract items
      tags:
      - Contracts
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-contract
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/corporationhistory:
    get:
      description: Get a list of all the corporations a character has been a member
        of
      operationId: GetCharactersCharacterIdCorporationhistory
      summary: Get corporation history
      tags:
      - Character
      x-cache-age: 86400
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/cspa:
    post:
      description: "Takes a source character ID in the url and a set of target character\
        \ ID's in the body, returns a CSPA charge cost"
      operationId: PostCharactersCharacterIdCspa
      security:
      - OAuth2:
        - esi-characters.read_contacts.v1
      summary: Calculate a CSPA charge cost
      tags:
      - Character
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/fatigue:
    get:
      description: Return a character's jump activation and fatigue information
      operationId: GetCharactersCharacterIdFatigue
      security:
      - OAuth2:
        - esi-characters.read_fatigue.v1
      summary: Get jump fatigue
      tags:
      - Character
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-location
        max-tokens: 1200
        window-size: 15m
  /characters/{character_id}/fittings:
    get:
      description: Return fittings of a character
      operationId: GetCharactersCharacterIdFittings
      security:
      - OAuth2:
        - esi-fittings.read_fittings.v1
      summary: Get fittings
      tags:
      - Fittings
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fitting
        max-tokens: 150
        window-size: 15m
    post:
      description: Save a new fitting for a character
      operationId: PostCharactersCharacterIdFittings
      security:
      - OAuth2:
        - esi-fittings.write_fittings.v1
      summary: Create fitting
      tags:
      - Fittings
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fitting
        max-tokens: 150
        window-size: 15m
  /characters/{character_id}/fittings/{fitting_id}:
    delete:
      description: Delete a fitting from a character
      operationId: DeleteCharactersCharacterIdFittingsFittingId
      security:
      - OAuth2:
        - esi-fittings.write_fittings.v1
      summary: Delete fitting
      tags:
      - Fittings
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fitting
        max-tokens: 150
        window-size: 15m
  /characters/{character_id}/fleet:
    get:
      description: "Return the fleet ID the character is in, if any."
      operationId: GetCharactersCharacterIdFleet
      security:
      - OAuth2:
        - esi-fleets.read_fleet.v1
      summary: Get character fleet info
      tags:
      - Fleets
      x-cache-age: 60
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /characters/{character_id}/fw/stats:
    get:
      description: |-
        Statistical overview of a character involved in faction warfare

        This route expires daily at 11:05
      operationId: GetCharactersCharacterIdFwStats
      security:
      - OAuth2:
        - esi-characters.read_fw_stats.v1
      summary: Overview of a character involved in faction warfare
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /characters/{character_id}/implants:
    get:
      description: Return implants on the active clone of a character
      operationId: GetCharactersCharacterIdImplants
      security:
      - OAuth2:
        - esi-clones.read_implants.v1
      summary: Get active implants
      tags:
      - Clones
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/industry/jobs:
    get:
      description: List industry jobs placed by a character
      operationId: GetCharactersCharacterIdIndustryJobs
      security:
      - OAuth2:
        - esi-industry.read_character_jobs.v1
      summary: List character industry jobs
      tags:
      - Industry
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-industry
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/killmails/recent:
    get:
      description: Return a list of a character's kills and losses going back 90 days
      operationId: GetCharactersCharacterIdKillmailsRecent
      security:
      - OAuth2:
        - esi-killmails.read_killmails.v1
      summary: Get a character's recent kills and losses
      tags:
      - Killmails
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-killmail
        max-tokens: 30
        window-size: 15m
  /characters/{character_id}/location:
    get:
      description: "Information about the characters current location. Returns the\
        \ current solar system id, and also the current station or structure ID if\
        \ applicable"
      operationId: GetCharactersCharacterIdLocation
      security:
      - OAuth2:
        - esi-location.read_location.v1
      summary: Get character location
      tags:
      - Location
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-location
        max-tokens: 1200
        window-size: 15m
  /characters/{character_id}/loyalty/points:
    get:
      description: Return a list of loyalty points for all corporations the character
        has worked for
      operationId: GetCharactersCharacterIdLoyaltyPoints
      security:
      - OAuth2:
        - esi-characters.read_loyalty.v1
      summary: Get loyalty points
      tags:
      - Loyalty
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-wallet
        max-tokens: 150
        window-size: 15m
  /characters/{character_id}/mail:
    get:
      description: "Return the 50 most recent mail headers belonging to the character\
        \ that match the query criteria. Queries can be filtered by label, and last_mail_id\
        \ can be used to paginate backwards"
      operationId: GetCharactersCharacterIdMail
      security:
      - OAuth2:
        - esi-mail.read_mail.v1
      summary: Return mail headers
      tags:
      - Mail
      x-cache-age: 30
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    post:
      description: Create and send a new mail
      operationId: PostCharactersCharacterIdMail
      security:
      - OAuth2:
        - esi-mail.send_mail.v1
      summary: Send a new mail
      tags:
      - Mail
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/mail/labels:
    get:
      description: "Return a list of the users mail labels, unread counts for each\
        \ label and a total unread count."
      operationId: GetCharactersCharacterIdMailLabels
      security:
      - OAuth2:
        - esi-mail.read_mail.v1
      summary: Get mail labels and unread counts
      tags:
      - Mail
      x-cache-age: 30
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    post:
      description: Create a mail label
      operationId: PostCharactersCharacterIdMailLabels
      security:
      - OAuth2:
        - esi-mail.organize_mail.v1
      summary: Create a mail label
      tags:
      - Mail
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/mail/labels/{label_id}:
    delete:
      description: Delete a mail label
      operationId: DeleteCharactersCharacterIdMailLabelsLabelId
      security:
      - OAuth2:
        - esi-mail.organize_mail.v1
      summary: Delete a mail label
      tags:
      - Mail
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/mail/lists:
    get:
      description: Return all mailing lists that the character is subscribed to
      operationId: GetCharactersCharacterIdMailLists
      security:
      - OAuth2:
        - esi-mail.read_mail.v1
      summary: Return mailing list subscriptions
      tags:
      - Mail
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/mail/{mail_id}:
    delete:
      description: Delete a mail
      operationId: DeleteCharactersCharacterIdMailMailId
      security:
      - OAuth2:
        - esi-mail.organize_mail.v1
      summary: Delete a mail
      tags:
      - Mail
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    get:
      description: Return the contents of an EVE mail
      operationId: GetCharactersCharacterIdMailMailId
      security:
      - OAuth2:
        - esi-mail.read_mail.v1
      summary: Return a mail
      tags:
      - Mail
      x-cache-age: 30
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
    put:
      description: Update metadata about a mail
      operationId: PutCharactersCharacterIdMailMailId
      security:
      - OAuth2:
        - esi-mail.organize_mail.v1
      summary: Update metadata about a mail
      tags:
      - Mail
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/medals:
    get:
      description: Return a list of medals the character has
      operationId: GetCharactersCharacterIdMedals
      security:
      - OAuth2:
        - esi-characters.read_medals.v1
      summary: Get medals
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/mining:
    get:
      description: Paginated record of all mining done by a character for the past
        30 days
      operationId: GetCharactersCharacterIdMining
      security:
      - OAuth2:
        - esi-industry.read_character_mining.v1
      summary: Character mining ledger
      tags:
      - Industry
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-industry
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/notifications:
    get:
      description: Return character notifications
      operationId: GetCharactersCharacterIdNotifications
      security:
      - OAuth2:
        - esi-characters.read_notifications.v1
      summary: Get character notifications
      tags:
      - Character
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-notification
        max-tokens: 15
        window-size: 15m
  /characters/{character_id}/notifications/contacts:
    get:
      description: Return notifications about having been added to someone's contact
        list
      operationId: GetCharactersCharacterIdNotificationsContacts
      security:
      - OAuth2:
        - esi-characters.read_notifications.v1
      summary: Get new contact notifications
      tags:
      - Character
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/online:
    get:
      description: Checks if the character is currently online
      operationId: GetCharactersCharacterIdOnline
      security:
      - OAuth2:
        - esi-location.read_online.v1
      summary: Get character online
      tags:
      - Location
      x-cache-age: 60
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-location
        max-tokens: 1200
        window-size: 15m
  /characters/{character_id}/orders:
    get:
      description: List open market orders placed by a character
      operationId: GetCharactersCharacterIdOrders
      security:
      - OAuth2:
        - esi-markets.read_character_orders.v1
      summary: List open orders from a character
      tags:
      - Market
      x-cache-age: 1200
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/orders/history:
    get:
      description: List cancelled and expired market orders placed by a character
        up to 90 days in the past.
      operationId: GetCharactersCharacterIdOrdersHistory
      security:
      - OAuth2:
        - esi-markets.read_character_orders.v1
      summary: List historical orders by a character
      tags:
      - Market
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/planets:
    get:
      description: Returns a list of all planetary colonies owned by a character.
      operationId: GetCharactersCharacterIdPlanets
      security:
      - OAuth2:
        - esi-planets.manage_planets.v1
      summary: Get colonies
      tags:
      - Planetary Interaction
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-industry
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/planets/{planet_id}:
    get:
      description: "Returns full details on the layout of a single planetary colony,\
        \ including links, pins and routes. Note: Planetary information is only recalculated\
        \ when the colony is viewed through the client. Information will not update\
        \ until this criteria is met."
      operationId: GetCharactersCharacterIdPlanetsPlanetId
      security:
      - OAuth2:
        - esi-planets.manage_planets.v1
      summary: Get colony layout
      tags:
      - Planetary Interaction
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-industry
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/portrait:
    get:
      description: |-
        Get portrait urls for a character

        This route expires daily at 11:05
      operationId: GetCharactersCharacterIdPortrait
      summary: Get character portraits
      tags:
      - Character
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/roles:
    get:
      description: Returns a character's corporation roles
      operationId: GetCharactersCharacterIdRoles
      security:
      - OAuth2:
        - esi-characters.read_corporation_roles.v1
      summary: Get character corporation roles
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/search:
    get:
      description: Search for entities that match a given sub-string.
      operationId: GetCharactersCharacterIdSearch
      security:
      - OAuth2:
        - esi-search.search_structures.v1
      summary: Search on a string
      tags:
      - Search
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /characters/{character_id}/ship:
    get:
      description: "Get the current ship type, name and id"
      operationId: GetCharactersCharacterIdShip
      security:
      - OAuth2:
        - esi-location.read_ship_type.v1
      summary: Get current ship
      tags:
      - Location
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-location
        max-tokens: 1200
        window-size: 15m
  /characters/{character_id}/skillqueue:
    get:
      description: List the configured skill queue for the given character
      operationId: GetCharactersCharacterIdSkillqueue
      security:
      - OAuth2:
        - esi-skills.read_skillqueue.v1
      summary: Get character's skill queue
      tags:
      - Skills
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/skills:
    get:
      description: List all trained skills for the given character
      operationId: GetCharactersCharacterIdSkills
      security:
      - OAuth2:
        - esi-skills.read_skills.v1
      summary: Get character skills
      tags:
      - Skills
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/standings:
    get:
      description: "Return character standings from agents, NPC corporations, and\
        \ factions"
      operationId: GetCharactersCharacterIdStandings
      security:
      - OAuth2:
        - esi-characters.read_standings.v1
      summary: Get standings
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-social
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/titles:
    get:
      description: Returns a character's titles
      operationId: GetCharactersCharacterIdTitles
      security:
      - OAuth2:
        - esi-characters.read_titles.v1
      summary: Get character corporation titles
      tags:
      - Character
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-detail
        max-tokens: 600
        window-size: 15m
  /characters/{character_id}/wallet:
    get:
      description: Returns a character's wallet balance
      operationId: GetCharactersCharacterIdWallet
      security:
      - OAuth2:
        - esi-wallet.read_character_wallet.v1
      summary: Get a character's wallet balance
      tags:
      - Wallet
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-wallet
        max-tokens: 150
        window-size: 15m
  /characters/{character_id}/wallet/journal:
    get:
      description: Retrieve the given character's wallet journal going 30 days back
      operationId: GetCharactersCharacterIdWalletJournal
      security:
      - OAuth2:
        - esi-wallet.read_character_wallet.v1
      summary: Get character wallet journal
      tags:
      - Wallet
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-wallet
        max-tokens: 150
        window-size: 15m
  /characters/{character_id}/wallet/transactions:
    get:
      description: Get wallet transactions of a character
      operationId: GetCharactersCharacterIdWalletTransactions
      security:
      - OAuth2:
        - esi-wallet.read_character_wallet.v1
      summary: Get wallet transactions
      tags:
      - Wallet
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: char-wallet
        max-tokens: 150
        window-size: 15m
  /contracts/public/bids/{contract_id}:
    get:
      description: Lists bids on a public auction contract
      operationId: GetContractsPublicBidsContractId
      summary: Get public contract bids
      tags:
      - Contracts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
  /contracts/public/items/{contract_id}:
    get:
      description: Lists items of a public contract
      operationId: GetContractsPublicItemsContractId
      summary: Get public contract items
      tags:
      - Contracts
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /contracts/public/{region_id}:
    get:
      description: Returns a paginated list of all public contracts in the given region
      operationId: GetContractsPublicRegionId
      summary: Get public contracts
      tags:
      - Contracts
      x-cache-age: 1800
      x-compatibility-date: 2020-01-01
  /corporation/{corporation_id}/mining/extractions:
    get:
      description: Extraction timers for all moon chunks being extracted by refineries
        belonging to a corporation.
      operationId: GetCorporationCorporationIdMiningExtractions
      security:
      - OAuth2:
        - esi-industry.read_corporation_mining.v1
      summary: Moon extraction timers
      tags:
      - Industry
      x-cache-age: 1800
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-industry
        max-tokens: 600
        window-size: 15m
      x-required-roles:
      - Station_Manager
  /corporation/{corporation_id}/mining/observers:
    get:
      description: Paginated list of all entities capable of observing and recording
        mining for a corporation
      operationId: GetCorporationCorporationIdMiningObservers
      security:
      - OAuth2:
        - esi-industry.read_corporation_mining.v1
      summary: Corporation mining observers
      tags:
      - Industry
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-industry
        max-tokens: 600
        window-size: 15m
      x-required-roles:
      - Accountant
  /corporation/{corporation_id}/mining/observers/{observer_id}:
    get:
      description: Paginated record of all mining seen by an observer
      operationId: GetCorporationCorporationIdMiningObserversObserverId
      security:
      - OAuth2:
        - esi-industry.read_corporation_mining.v1
      summary: Observed corporation mining
      tags:
      - Industry
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-industry
        max-tokens: 600
        window-size: 15m
      x-required-roles:
      - Accountant
  /corporations/npccorps:
    get:
      description: |-
        Get a list of npc corporations

        This route expires daily at 11:05
      operationId: GetCorporationsNpccorps
      summary: Get npc corporations
      tags:
      - Corporation
      x-compatibility-date: 2020-01-01
  /corporations/{corporation_id}:
    get:
      description: Public information about a corporation
      operationId: GetCorporationsCorporationId
      summary: Get corporation information
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /corporations/{corporation_id}/alliancehistory:
    get:
      description: Get a list of all the alliances a corporation has been a member
        of
      operationId: GetCorporationsCorporationIdAlliancehistory
      summary: Get alliance history
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /corporations/{corporation_id}/assets:
    get:
      description: Return a list of the corporation assets
      operationId: GetCorporationsCorporationIdAssets
      security:
      - OAuth2:
        - esi-assets.read_corporation_assets.v1
      summary: Get corporation assets
      tags:
      - Assets
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Director
  /corporations/{corporation_id}/assets/locations:
    post:
      description: "Return locations for a set of item ids, which you can get from\
        \ corporation assets endpoint. Coordinates for items in hangars or stations\
        \ are set to (0,0,0)"
      operationId: PostCorporationsCorporationIdAssetsLocations
      security:
      - OAuth2:
        - esi-assets.read_corporation_assets.v1
      summary: Get corporation asset locations
      tags:
      - Assets
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Director
  /corporations/{corporation_id}/assets/names:
    post:
      description: "Return names for a set of item ids, which you can get from corporation\
        \ assets endpoint. Only valid for items that can customize names, like containers\
        \ or ships"
      operationId: PostCorporationsCorporationIdAssetsNames
      security:
      - OAuth2:
        - esi-assets.read_corporation_assets.v1
      summary: Get corporation asset names
      tags:
      - Assets
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Director
  /corporations/{corporation_id}/blueprints:
    get:
      description: Returns a list of blueprints the corporation owns
      operationId: GetCorporationsCorporationIdBlueprints
      security:
      - OAuth2:
        - esi-corporations.read_blueprints.v1
      summary: Get corporation blueprints
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-industry
        max-tokens: 600
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/contacts:
    get:
      description: Return contacts of a corporation
      operationId: GetCorporationsCorporationIdContacts
      security:
      - OAuth2:
        - esi-corporations.read_contacts.v1
      summary: Get corporation contacts
      tags:
      - Contacts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-social
        max-tokens: 300
        window-size: 15m
  /corporations/{corporation_id}/contacts/labels:
    get:
      description: Return custom labels for a corporation's contacts
      operationId: GetCorporationsCorporationIdContactsLabels
      security:
      - OAuth2:
        - esi-corporations.read_contacts.v1
      summary: Get corporation contact labels
      tags:
      - Contacts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-social
        max-tokens: 300
        window-size: 15m
  /corporations/{corporation_id}/containers/logs:
    get:
      description: Returns logs recorded in the past seven days from all audit log
        secure containers (ALSC) owned by a given corporation
      operationId: GetCorporationsCorporationIdContainersLogs
      security:
      - OAuth2:
        - esi-corporations.read_container_logs.v1
      summary: Get all corporation ALSC logs
      tags:
      - Corporation
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Director
  /corporations/{corporation_id}/contracts:
    get:
      description: "Returns contracts available to a corporation, only if the corporation\
        \ is issuer, acceptor or assignee. Only returns contracts no older than 30\
        \ days, or if the status is \"in_progress\"."
      operationId: GetCorporationsCorporationIdContracts
      security:
      - OAuth2:
        - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contracts
      tags:
      - Contracts
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-contract
        max-tokens: 600
        window-size: 15m
  /corporations/{corporation_id}/contracts/{contract_id}/bids:
    get:
      description: Lists bids on a particular auction contract
      operationId: GetCorporationsCorporationIdContractsContractIdBids
      security:
      - OAuth2:
        - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contract bids
      tags:
      - Contracts
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-contract
        max-tokens: 600
        window-size: 15m
  /corporations/{corporation_id}/contracts/{contract_id}/items:
    get:
      description: Lists items of a particular contract
      operationId: GetCorporationsCorporationIdContractsContractIdItems
      security:
      - OAuth2:
        - esi-contracts.read_corporation_contracts.v1
      summary: Get corporation contract items
      tags:
      - Contracts
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-contract
        max-tokens: 600
        window-size: 15m
  /corporations/{corporation_id}/customs_offices:
    get:
      description: List customs offices owned by a corporation
      operationId: GetCorporationsCorporationIdCustomsOffices
      security:
      - OAuth2:
        - esi-planets.read_customs_offices.v1
      summary: List corporation customs offices
      tags:
      - Planetary Interaction
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-industry
        max-tokens: 600
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/divisions:
    get:
      description: "Return corporation hangar and wallet division names, only show\
        \ if a division is not using the default name"
      operationId: GetCorporationsCorporationIdDivisions
      security:
      - OAuth2:
        - esi-corporations.read_divisions.v1
      summary: Get corporation divisions
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-wallet
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/facilities:
    get:
      description: Return a corporation's facilities
      operationId: GetCorporationsCorporationIdFacilities
      security:
      - OAuth2:
        - esi-corporations.read_facilities.v1
      summary: Get corporation facilities
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Factory_Manager
  /corporations/{corporation_id}/fw/stats:
    get:
      description: |-
        Statistics about a corporation involved in faction warfare

        This route expires daily at 11:05
      operationId: GetCorporationsCorporationIdFwStats
      security:
      - OAuth2:
        - esi-corporations.read_fw_stats.v1
      summary: Overview of a corporation involved in faction warfare
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /corporations/{corporation_id}/icons:
    get:
      description: Get the icon urls for a corporation
      operationId: GetCorporationsCorporationIdIcons
      summary: Get corporation icon
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /corporations/{corporation_id}/industry/jobs:
    get:
      description: List industry jobs run by a corporation
      operationId: GetCorporationsCorporationIdIndustryJobs
      security:
      - OAuth2:
        - esi-industry.read_corporation_jobs.v1
      summary: List corporation industry jobs
      tags:
      - Industry
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-industry
        max-tokens: 600
        window-size: 15m
      x-required-roles:
      - Factory_Manager
  /corporations/{corporation_id}/killmails/recent:
    get:
      description: Get a list of a corporation's kills and losses going back 90 days
      operationId: GetCorporationsCorporationIdKillmailsRecent
      security:
      - OAuth2:
        - esi-killmails.read_corporation_killmails.v1
      summary: Get a corporation's recent kills and losses
      tags:
      - Killmails
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-killmail
        max-tokens: 30
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/medals:
    get:
      description: Returns a corporation's medals
      operationId: GetCorporationsCorporationIdMedals
      security:
      - OAuth2:
        - esi-corporations.read_medals.v1
      summary: Get corporation medals
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-detail
        max-tokens: 300
        window-size: 15m
  /corporations/{corporation_id}/medals/issued:
    get:
      description: Returns medals issued by a corporation
      operationId: GetCorporationsCorporationIdMedalsIssued
      security:
      - OAuth2:
        - esi-corporations.read_medals.v1
      summary: Get corporation issued medals
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-detail
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/members:
    get:
      description: "Return the current member list of a corporation, the token's character\
        \ need to be a member of the corporation."
      operationId: GetCorporationsCorporationIdMembers
      security:
      - OAuth2:
        - esi-corporations.read_corporation_membership.v1
      summary: Get corporation members
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
  /corporations/{corporation_id}/members/limit:
    get:
      description: "Return a corporation's member limit, not including CEO himself"
      operationId: GetCorporationsCorporationIdMembersLimit
      security:
      - OAuth2:
        - esi-corporations.track_members.v1
      summary: Get corporation member limit
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/members/titles:
    get:
      description: Returns a corporation's members' titles
      operationId: GetCorporationsCorporationIdMembersTitles
      security:
      - OAuth2:
        - esi-corporations.read_titles.v1
      summary: Get corporation's members' titles
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/membertracking:
    get:
      description: Returns additional information about a corporation's members which
        helps tracking their activities
      operationId: GetCorporationsCorporationIdMembertracking
      security:
      - OAuth2:
        - esi-corporations.track_members.v1
      summary: Track corporation members
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/orders:
    get:
      description: List open market orders placed on behalf of a corporation
      operationId: GetCorporationsCorporationIdOrders
      security:
      - OAuth2:
        - esi-markets.read_corporation_orders.v1
      summary: List open orders from a corporation
      tags:
      - Market
      x-cache-age: 1200
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Accountant
      - Trader
  /corporations/{corporation_id}/orders/history:
    get:
      description: List cancelled and expired market orders placed on behalf of a
        corporation up to 90 days in the past.
      operationId: GetCorporationsCorporationIdOrdersHistory
      security:
      - OAuth2:
        - esi-markets.read_corporation_orders.v1
      summary: List historical orders from a corporation
      tags:
      - Market
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Accountant
      - Trader
  /corporations/{corporation_id}/projects:
    get:
      description: Listing of all (active) corporation projects.
      operationId: GetCorporationsProjectsListing
      security:
      - OAuth2:
        - esi-corporations.read_projects.v1
      summary: List corporation projects
      tags:
      - Corporation Projects
      x-cache-age: 31536000
      x-compatibility-date: 2025-08-26
      x-pagination: cursor
  /corporations/{corporation_id}/projects/{project_id}:
    get:
      description: Get the details of a corporation project.
      operationId: GetCorporationsProjectsDetail
      security:
      - OAuth2:
        - esi-corporations.read_projects.v1
      summary: Get project details
      tags:
      - Corporation Projects
      x-cache-age: 600
      x-compatibility-date: 2025-08-26
  /corporations/{corporation_id}/projects/{project_id}/contribution/{character_id}:
    get:
      description: Show your contribution to a corporation project.
      operationId: GetCorporationsProjectsContribution
      security:
      - OAuth2:
        - esi-corporations.read_projects.v1
      summary: Get your project contribution
      tags:
      - Corporation Projects
      x-cache-age: 600
      x-compatibility-date: 2025-08-26
  /corporations/{corporation_id}/projects/{project_id}/contributors:
    get:
      description: Listing of all contributors to a corporation project.
      operationId: GetCorporationsProjectsContributors
      security:
      - OAuth2:
        - esi-corporations.read_projects.v1
      summary: List project contributors
      tags:
      - Corporation Projects
      x-cache-age: 31536000
      x-compatibility-date: 2025-08-26
      x-pagination: cursor
      x-required-roles:
      - Project_Manager
  /corporations/{corporation_id}/roles:
    get:
      description: Return the roles of all members if the character has the personnel
        manager role or any grantable role.
      operationId: GetCorporationsCorporationIdRoles
      security:
      - OAuth2:
        - esi-corporations.read_corporation_membership.v1
      summary: Get corporation member roles
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
  /corporations/{corporation_id}/roles/history:
    get:
      description: "Return how roles have changed for a coporation's members, up to\
        \ a month"
      operationId: GetCorporationsCorporationIdRolesHistory
      security:
      - OAuth2:
        - esi-corporations.read_corporation_membership.v1
      summary: Get corporation member roles history
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/shareholders:
    get:
      description: Return the current shareholders of a corporation.
      operationId: GetCorporationsCorporationIdShareholders
      security:
      - OAuth2:
        - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation shareholders
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-detail
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/standings:
    get:
      description: "Return corporation standings from agents, NPC corporations, and\
        \ factions"
      operationId: GetCorporationsCorporationIdStandings
      security:
      - OAuth2:
        - esi-corporations.read_standings.v1
      summary: Get corporation standings
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-member
        max-tokens: 300
        window-size: 15m
  /corporations/{corporation_id}/starbases:
    get:
      description: Returns list of corporation starbases (POSes)
      operationId: GetCorporationsCorporationIdStarbases
      security:
      - OAuth2:
        - esi-corporations.read_starbases.v1
      summary: Get corporation starbases (POSes)
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Director
  /corporations/{corporation_id}/starbases/{starbase_id}:
    get:
      description: Returns various settings and fuels of a starbase (POS)
      operationId: GetCorporationsCorporationIdStarbasesStarbaseId
      security:
      - OAuth2:
        - esi-corporations.read_starbases.v1
      summary: Get starbase (POS) detail
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Director
  /corporations/{corporation_id}/structures:
    get:
      description: "Get a list of corporation structures. This route's version includes\
        \ the changes to structures detailed in this blog: https://www.eveonline.com/article/upwell-2.0-structures-changes-coming-on-february-13th"
      operationId: GetCorporationsCorporationIdStructures
      security:
      - OAuth2:
        - esi-corporations.read_structures.v1
      summary: Get corporation structures
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-required-roles:
      - Station_Manager
  /corporations/{corporation_id}/titles:
    get:
      description: Returns a corporation's titles
      operationId: GetCorporationsCorporationIdTitles
      security:
      - OAuth2:
        - esi-corporations.read_titles.v1
      summary: Get corporation titles
      tags:
      - Corporation
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-detail
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Director
  /corporations/{corporation_id}/wallets:
    get:
      description: Get a corporation's wallets
      operationId: GetCorporationsCorporationIdWallets
      security:
      - OAuth2:
        - esi-wallet.read_corporation_wallets.v1
      summary: Returns a corporation's wallet balance
      tags:
      - Wallet
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-wallet
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Accountant
      - Junior_Accountant
  /corporations/{corporation_id}/wallets/{division}/journal:
    get:
      description: Retrieve the given corporation's wallet journal for the given division
        going 30 days back
      operationId: GetCorporationsCorporationIdWalletsDivisionJournal
      security:
      - OAuth2:
        - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation wallet journal
      tags:
      - Wallet
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-wallet
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Accountant
      - Junior_Accountant
  /corporations/{corporation_id}/wallets/{division}/transactions:
    get:
      description: Get wallet transactions of a corporation
      operationId: GetCorporationsCorporationIdWalletsDivisionTransactions
      security:
      - OAuth2:
        - esi-wallet.read_corporation_wallets.v1
      summary: Get corporation wallet transactions
      tags:
      - Wallet
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: corp-wallet
        max-tokens: 300
        window-size: 15m
      x-required-roles:
      - Accountant
      - Junior_Accountant
  /dogma/attributes:
    get:
      description: |-
        Get a list of dogma attribute ids

        This route expires daily at 11:05
      operationId: GetDogmaAttributes
      summary: Get attributes
      tags:
      - Dogma
      x-compatibility-date: 2020-01-01
  /dogma/attributes/{attribute_id}:
    get:
      description: |-
        Get information on a dogma attribute

        This route expires daily at 11:05
      operationId: GetDogmaAttributesAttributeId
      summary: Get attribute information
      tags:
      - Dogma
      x-compatibility-date: 2020-01-01
  /dogma/dynamic/items/{type_id}/{item_id}:
    get:
      description: |-
        Returns info about a dynamic item resulting from mutation with a mutaplasmid.

        This route expires daily at 11:05
      operationId: GetDogmaDynamicItemsTypeIdItemId
      summary: Get dynamic item information
      tags:
      - Dogma
      x-compatibility-date: 2020-01-01
  /dogma/effects:
    get:
      description: |-
        Get a list of dogma effect ids

        This route expires daily at 11:05
      operationId: GetDogmaEffects
      summary: Get effects
      tags:
      - Dogma
      x-compatibility-date: 2020-01-01
  /dogma/effects/{effect_id}:
    get:
      description: |-
        Get information on a dogma effect

        This route expires daily at 11:05
      operationId: GetDogmaEffectsEffectId
      summary: Get effect information
      tags:
      - Dogma
      x-compatibility-date: 2020-01-01
  /fleets/{fleet_id}:
    get:
      description: Return details about a fleet
      operationId: GetFleetsFleetId
      security:
      - OAuth2:
        - esi-fleets.read_fleet.v1
      summary: Get fleet information
      tags:
      - Fleets
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
    put:
      description: Update settings about a fleet
      operationId: PutFleetsFleetId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Update fleet
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fleets/{fleet_id}/members:
    get:
      description: Return information about fleet members
      operationId: GetFleetsFleetIdMembers
      security:
      - OAuth2:
        - esi-fleets.read_fleet.v1
      summary: Get fleet members
      tags:
      - Fleets
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
    post:
      description: Invite a character into the fleet. If a character has a CSPA charge
        set it is not possible to invite them to the fleet using ESI
      operationId: PostFleetsFleetIdMembers
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Create fleet invitation
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fleets/{fleet_id}/members/{member_id}:
    delete:
      description: Kick a fleet member
      operationId: DeleteFleetsFleetIdMembersMemberId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Kick fleet member
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
    put:
      description: Move a fleet member around
      operationId: PutFleetsFleetIdMembersMemberId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Move fleet member
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fleets/{fleet_id}/squads/{squad_id}:
    delete:
      description: "Delete a fleet squad, only empty squads can be deleted"
      operationId: DeleteFleetsFleetIdSquadsSquadId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Delete fleet squad
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
    put:
      description: Rename a fleet squad
      operationId: PutFleetsFleetIdSquadsSquadId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Rename fleet squad
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fleets/{fleet_id}/wings:
    get:
      description: Return information about wings in a fleet
      operationId: GetFleetsFleetIdWings
      security:
      - OAuth2:
        - esi-fleets.read_fleet.v1
      summary: Get fleet wings
      tags:
      - Fleets
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
    post:
      description: Create a new wing in a fleet
      operationId: PostFleetsFleetIdWings
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Create fleet wing
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fleets/{fleet_id}/wings/{wing_id}:
    delete:
      description: "Delete a fleet wing, only empty wings can be deleted. The wing\
        \ may contain squads, but the squads must be empty"
      operationId: DeleteFleetsFleetIdWingsWingId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Delete fleet wing
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
    put:
      description: Rename a fleet wing
      operationId: PutFleetsFleetIdWingsWingId
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Rename fleet wing
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fleets/{fleet_id}/wings/{wing_id}/squads:
    post:
      description: Create a new squad in a fleet
      operationId: PostFleetsFleetIdWingsWingIdSquads
      security:
      - OAuth2:
        - esi-fleets.write_fleet.v1
      summary: Create fleet squad
      tags:
      - Fleets
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: fleet
        max-tokens: 1800
        window-size: 15m
  /fw/leaderboards:
    get:
      description: |-
        Top 4 leaderboard of factions for kills and victory points separated by total, last week and yesterday

        This route expires daily at 11:05
      operationId: GetFwLeaderboards
      summary: List of the top factions in faction warfare
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /fw/leaderboards/characters:
    get:
      description: |-
        Top 100 leaderboard of pilots for kills and victory points separated by total, last week and yesterday

        This route expires daily at 11:05
      operationId: GetFwLeaderboardsCharacters
      summary: List of the top pilots in faction warfare
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /fw/leaderboards/corporations:
    get:
      description: |-
        Top 10 leaderboard of corporations for kills and victory points separated by total, last week and yesterday

        This route expires daily at 11:05
      operationId: GetFwLeaderboardsCorporations
      summary: List of the top corporations in faction warfare
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /fw/stats:
    get:
      description: |-
        Statistical overviews of factions involved in faction warfare

        This route expires daily at 11:05
      operationId: GetFwStats
      summary: An overview of statistics about factions involved in faction warfare
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /fw/systems:
    get:
      description: An overview of the current ownership of faction warfare solar systems
      operationId: GetFwSystems
      summary: Ownership of faction warfare systems
      tags:
      - Faction Warfare
      x-cache-age: 1800
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /fw/wars:
    get:
      description: |-
        Data about which NPC factions are at war

        This route expires daily at 11:05
      operationId: GetFwWars
      summary: Data about which NPC factions are at war
      tags:
      - Faction Warfare
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: factional-warfare
        max-tokens: 150
        window-size: 15m
  /incursions:
    get:
      description: Return a list of current incursions
      operationId: GetIncursions
      summary: List incursions
      tags:
      - Incursions
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: incursion
        max-tokens: 150
        window-size: 15m
  /industry/facilities:
    get:
      description: Return a list of industry facilities
      operationId: GetIndustryFacilities
      summary: List industry facilities
      tags:
      - Industry
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: industry
        max-tokens: 150
        window-size: 15m
  /industry/systems:
    get:
      description: Return cost indices for solar systems
      operationId: GetIndustrySystems
      summary: List solar system cost indices
      tags:
      - Industry
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: industry
        max-tokens: 150
        window-size: 15m
  /insurance/prices:
    get:
      description: Return available insurance levels for all ship types
      operationId: GetInsurancePrices
      summary: List insurance levels
      tags:
      - Insurance
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: insurance
        max-tokens: 150
        window-size: 15m
  /killmails/{killmail_id}/{killmail_hash}:
    get:
      description: Return a single killmail from its ID and hash
      operationId: GetKillmailsKillmailIdKillmailHash
      summary: Get a single killmail
      tags:
      - Killmails
      x-cache-age: 2592000
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: killmail
        max-tokens: 3600
        window-size: 15m
  /loyalty/stores/{corporation_id}/offers:
    get:
      description: |-
        Return a list of offers from a specific corporation's loyalty store

        This route expires daily at 11:05
      operationId: GetLoyaltyStoresCorporationIdOffers
      summary: List loyalty store offers
      tags:
      - Loyalty
      x-compatibility-date: 2020-01-01
  /markets/groups:
    get:
      description: |-
        Get a list of item groups

        This route expires daily at 11:05
      operationId: GetMarketsGroups
      summary: Get item groups
      tags:
      - Market
      x-compatibility-date: 2020-01-01
  /markets/groups/{market_group_id}:
    get:
      description: |-
        Get information on an item group

        This route expires daily at 11:05
      operationId: GetMarketsGroupsMarketGroupId
      summary: Get item group information
      tags:
      - Market
      x-compatibility-date: 2020-01-01
  /markets/prices:
    get:
      description: Return a list of prices
      operationId: GetMarketsPrices
      summary: List market prices
      tags:
      - Market
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /markets/structures/{structure_id}:
    get:
      description: Return all orders in a structure
      operationId: GetMarketsStructuresStructureId
      security:
      - OAuth2:
        - esi-markets.structure_markets.v1
      summary: List orders in a structure
      tags:
      - Market
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
  /markets/{region_id}/history:
    get:
      description: |-
        Return a list of historical market statistics for the specified type in a region

        This route expires daily at 11:05
      operationId: GetMarketsRegionIdHistory
      summary: List historical market statistics in a region
      tags:
      - Market
      x-compatibility-date: 2020-01-01
  /markets/{region_id}/orders:
    get:
      description: Return a list of orders in a region
      operationId: GetMarketsRegionIdOrders
      summary: List orders in a region
      tags:
      - Market
      x-cache-age: 300
      x-compatibility-date: 2020-01-01
  /markets/{region_id}/types:
    get:
      description: "Return a list of type IDs that have active orders in the region,\
        \ for efficient market indexing."
      operationId: GetMarketsRegionIdTypes
      summary: List type IDs relevant to a market
      tags:
      - Market
      x-cache-age: 600
      x-compatibility-date: 2020-01-01
  /meta/changelog:
    get:
      description: Get the changelog of this API.
      operationId: GetMetaChangelog
      summary: Get changelog
      tags:
      - Meta
      x-compatibility-date: 2025-09-26
  /meta/compatibility-dates:
    get:
      description: Get a list of compatibility dates.
      operationId: GetMetaCompatibilityDates
      summary: Get compatibility dates
      tags:
      - Meta
      x-compatibility-date: 2020-01-01
  /meta/status:
    get:
      description: Get the health status of each API route.
      operationId: GetMetaStatus
      summary: Get health status
      tags:
      - Meta
      x-compatibility-date: 2025-11-06
  /route/{origin_system_id}/{destination_system_id}:
    post:
      description: Calculate the systems between the given origin and destination.
      operationId: PostRoute
      summary: Get route between two systems
      tags:
      - Routes
      x-compatibility-date: 2025-09-30
      x-rate-limit:
        group: routes
        max-tokens: 3600
        window-size: 15m
  /sovereignty/campaigns:
    get:
      description: Shows sovereignty data for campaigns.
      operationId: GetSovereigntyCampaigns
      summary: List sovereignty campaigns
      tags:
      - Sovereignty
      x-cache-age: 5
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: sovereignty
        max-tokens: 600
        window-size: 15m
  /sovereignty/map:
    get:
      description: Shows sovereignty information for solar systems
      operationId: GetSovereigntyMap
      summary: List sovereignty of systems
      tags:
      - Sovereignty
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: sovereignty
        max-tokens: 600
        window-size: 15m
  /sovereignty/structures:
    get:
      description: Shows sovereignty data for structures.
      operationId: GetSovereigntyStructures
      summary: List sovereignty structures
      tags:
      - Sovereignty
      x-cache-age: 120
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: sovereignty
        max-tokens: 600
        window-size: 15m
  /status:
    get:
      description: EVE Server status
      operationId: GetStatus
      summary: Retrieve the uptime and player counts
      tags:
      - Status
      x-cache-age: 30
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: status
        max-tokens: 600
        window-size: 15m
  /ui/autopilot/waypoint:
    post:
      description: Set a solar system as autopilot waypoint
      operationId: PostUiAutopilotWaypoint
      security:
      - OAuth2:
        - esi-ui.write_waypoint.v1
      summary: Set Autopilot Waypoint
      tags:
      - User Interface
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: ui
        max-tokens: 900
        window-size: 15m
  /ui/openwindow/contract:
    post:
      description: Open the contract window inside the client
      operationId: PostUiOpenwindowContract
      security:
      - OAuth2:
        - esi-ui.open_window.v1
      summary: Open Contract Window
      tags:
      - User Interface
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: ui
        max-tokens: 900
        window-size: 15m
  /ui/openwindow/information:
    post:
      description: "Open the information window for a character, corporation or alliance\
        \ inside the client"
      operationId: PostUiOpenwindowInformation
      security:
      - OAuth2:
        - esi-ui.open_window.v1
      summary: Open Information Window
      tags:
      - User Interface
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: ui
        max-tokens: 900
        window-size: 15m
  /ui/openwindow/marketdetails:
    post:
      description: Open the market details window for a specific typeID inside the
        client
      operationId: PostUiOpenwindowMarketdetails
      security:
      - OAuth2:
        - esi-ui.open_window.v1
      summary: Open Market Details
      tags:
      - User Interface
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: ui
        max-tokens: 900
        window-size: 15m
  /ui/openwindow/newmail:
    post:
      description: "Open the New Mail window, according to settings from the request\
        \ if applicable"
      operationId: PostUiOpenwindowNewmail
      security:
      - OAuth2:
        - esi-ui.open_window.v1
      summary: Open New Mail Window
      tags:
      - User Interface
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: ui
        max-tokens: 900
        window-size: 15m
  /universe/ancestries:
    get:
      description: |-
        Get all character ancestries

        This route expires daily at 11:05
      operationId: GetUniverseAncestries
      summary: Get ancestries
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/asteroid_belts/{asteroid_belt_id}:
    get:
      description: |-
        Get information on an asteroid belt

        This route expires daily at 11:05
      operationId: GetUniverseAsteroidBeltsAsteroidBeltId
      summary: Get asteroid belt information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/bloodlines:
    get:
      description: |-
        Get a list of bloodlines

        This route expires daily at 11:05
      operationId: GetUniverseBloodlines
      summary: Get bloodlines
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/categories:
    get:
      description: |-
        Get a list of item categories

        This route expires daily at 11:05
      operationId: GetUniverseCategories
      summary: Get item categories
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/categories/{category_id}:
    get:
      description: |-
        Get information of an item category

        This route expires daily at 11:05
      operationId: GetUniverseCategoriesCategoryId
      summary: Get item category information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/constellations:
    get:
      description: |-
        Get a list of constellations

        This route expires daily at 11:05
      operationId: GetUniverseConstellations
      summary: Get constellations
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/constellations/{constellation_id}:
    get:
      description: |-
        Get information on a constellation

        This route expires daily at 11:05
      operationId: GetUniverseConstellationsConstellationId
      summary: Get constellation information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/factions:
    get:
      description: |-
        Get a list of factions

        This route expires daily at 11:05
      operationId: GetUniverseFactions
      summary: Get factions
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/graphics:
    get:
      description: |-
        Get a list of graphics

        This route expires daily at 11:05
      operationId: GetUniverseGraphics
      summary: Get graphics
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/graphics/{graphic_id}:
    get:
      description: |-
        Get information on a graphic

        This route expires daily at 11:05
      operationId: GetUniverseGraphicsGraphicId
      summary: Get graphic information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/groups:
    get:
      description: |-
        Get a list of item groups

        This route expires daily at 11:05
      operationId: GetUniverseGroups
      summary: Get item groups
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/groups/{group_id}:
    get:
      description: |-
        Get information on an item group

        This route expires daily at 11:05
      operationId: GetUniverseGroupsGroupId
      summary: Get item group information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/ids:
    post:
      description: "Resolve a set of names to IDs in the following categories: agents,\
        \ alliances, characters, constellations, corporations factions, inventory_types,\
        \ regions, stations, and systems. Only exact matches will be returned. All\
        \ names searched for are cached for 12 hours"
      operationId: PostUniverseIds
      summary: Bulk names to IDs
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/moons/{moon_id}:
    get:
      description: |-
        Get information on a moon

        This route expires daily at 11:05
      operationId: GetUniverseMoonsMoonId
      summary: Get moon information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/names:
    post:
      description: "Resolve a set of IDs to names and categories. Supported ID's for\
        \ resolving are: Characters, Corporations, Alliances, Stations, Solar Systems,\
        \ Constellations, Regions, Types, Factions"
      operationId: PostUniverseNames
      summary: Get names and categories for a set of IDs
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/planets/{planet_id}:
    get:
      description: |-
        Get information on a planet

        This route expires daily at 11:05
      operationId: GetUniversePlanetsPlanetId
      summary: Get planet information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/races:
    get:
      description: |-
        Get a list of character races

        This route expires daily at 11:05
      operationId: GetUniverseRaces
      summary: Get character races
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/regions:
    get:
      description: |-
        Get a list of regions

        This route expires daily at 11:05
      operationId: GetUniverseRegions
      summary: Get regions
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/regions/{region_id}:
    get:
      description: |-
        Get information on a region

        This route expires daily at 11:05
      operationId: GetUniverseRegionsRegionId
      summary: Get region information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/schematics/{schematic_id}:
    get:
      description: Get information on a planetary factory schematic
      operationId: GetUniverseSchematicsSchematicId
      summary: Get schematic information
      tags:
      - Planetary Interaction
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /universe/stargates/{stargate_id}:
    get:
      description: |-
        Get information on a stargate

        This route expires daily at 11:05
      operationId: GetUniverseStargatesStargateId
      summary: Get stargate information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/stars/{star_id}:
    get:
      description: |-
        Get information on a star

        This route expires daily at 11:05
      operationId: GetUniverseStarsStarId
      summary: Get star information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/stations/{station_id}:
    get:
      description: |-
        Get information on a station

        This route expires daily at 11:05
      operationId: GetUniverseStationsStationId
      summary: Get station information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/structures:
    get:
      description: List all public structures
      operationId: GetUniverseStructures
      summary: List all public structures
      tags:
      - Universe
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /universe/structures/{structure_id}:
    get:
      description: "Returns information on requested structure if you are on the ACL.\
        \ Otherwise, returns \"Forbidden\" for all inputs."
      operationId: GetUniverseStructuresStructureId
      security:
      - OAuth2:
        - esi-universe.read_structures.v1
      summary: Get structure information
      tags:
      - Universe
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /universe/system_jumps:
    get:
      description: "Get the number of jumps in solar systems within the last hour\
        \ ending at the timestamp of the Last-Modified header, excluding wormhole\
        \ space. Only systems with jumps will be listed"
      operationId: GetUniverseSystemJumps
      summary: Get system jumps
      tags:
      - Universe
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /universe/system_kills:
    get:
      description: "Get the number of ship, pod and NPC kills per solar system within\
        \ the last hour ending at the timestamp of the Last-Modified header, excluding\
        \ wormhole space. Only systems with kills will be listed"
      operationId: GetUniverseSystemKills
      summary: Get system kills
      tags:
      - Universe
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
  /universe/systems:
    get:
      description: |-
        Get a list of solar systems

        This route expires daily at 11:05
      operationId: GetUniverseSystems
      summary: Get solar systems
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/systems/{system_id}:
    get:
      description: |-
        Get information on a solar system.

        This route expires daily at 11:05
      operationId: GetUniverseSystemsSystemId
      summary: Get solar system information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/types:
    get:
      description: |-
        Get a list of type ids

        This route expires daily at 11:05
      operationId: GetUniverseTypes
      summary: Get types
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /universe/types/{type_id}:
    get:
      description: |-
        Get information on a type

        This route expires daily at 11:05
      operationId: GetUniverseTypesTypeId
      summary: Get type information
      tags:
      - Universe
      x-compatibility-date: 2020-01-01
  /wars:
    get:
      description: Return a list of wars
      operationId: GetWars
      summary: List wars
      tags:
      - Wars
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: killmail
        max-tokens: 3600
        window-size: 15m
  /wars/{war_id}:
    get:
      description: Return details about a war
      operationId: GetWarsWarId
      summary: Get war information
      tags:
      - Wars
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: killmail
        max-tokens: 3600
        window-size: 15m
  /wars/{war_id}/killmails:
    get:
      description: Return a list of kills related to a war
      operationId: GetWarsWarIdKillmails
      summary: List kills for a war
      tags:
      - Wars
      x-cache-age: 3600
      x-compatibility-date: 2020-01-01
      x-rate-limit:
        group: killmail
        max-tokens: 3600
        window-size: 15m
components:
  securitySchemes:
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: https://login.eveonline.com/v2/oauth/authorize
          scopes:
            esi-alliances.read_contacts.v1: esi-alliances.read_contacts.v1
            esi-assets.read_assets.v1: esi-assets.read_assets.v1
            esi-assets.read_corporation_assets.v1: esi-assets.read_corporation_assets.v1
            esi-calendar.read_calendar_events.v1: esi-calendar.read_calendar_events.v1
            esi-calendar.respond_calendar_events.v1: esi-calendar.respond_calendar_events.v1
            esi-characters.read_agents_research.v1: esi-characters.read_agents_research.v1
            esi-characters.read_blueprints.v1: esi-characters.read_blueprints.v1
            esi-characters.read_contacts.v1: esi-characters.read_contacts.v1
            esi-characters.read_corporation_roles.v1: esi-characters.read_corporation_roles.v1
            esi-characters.read_fatigue.v1: esi-characters.read_fatigue.v1
            esi-characters.read_freelance_jobs.v1: esi-characters.read_freelance_jobs.v1
            esi-characters.read_fw_stats.v1: esi-characters.read_fw_stats.v1
            esi-characters.read_loyalty.v1: esi-characters.read_loyalty.v1
            esi-characters.read_medals.v1: esi-characters.read_medals.v1
            esi-characters.read_notifications.v1: esi-characters.read_notifications.v1
            esi-characters.read_standings.v1: esi-characters.read_standings.v1
            esi-characters.read_titles.v1: esi-characters.read_titles.v1
            esi-characters.write_contacts.v1: esi-characters.write_contacts.v1
            esi-clones.read_clones.v1: esi-clones.read_clones.v1
            esi-clones.read_implants.v1: esi-clones.read_implants.v1
            esi-contracts.read_character_contracts.v1: esi-contracts.read_character_contracts.v1
            esi-contracts.read_corporation_contracts.v1: esi-contracts.read_corporation_contracts.v1
            esi-corporations.read_blueprints.v1: esi-corporations.read_blueprints.v1
            esi-corporations.read_contacts.v1: esi-corporations.read_contacts.v1
            esi-corporations.read_container_logs.v1: esi-corporations.read_container_logs.v1
            esi-corporations.read_corporation_membership.v1: esi-corporations.read_corporation_membership.v1
            esi-corporations.read_divisions.v1: esi-corporations.read_divisions.v1
            esi-corporations.read_facilities.v1: esi-corporations.read_facilities.v1
            esi-corporations.read_freelance_jobs.v1: esi-corporations.read_freelance_jobs.v1
            esi-corporations.read_fw_stats.v1: esi-corporations.read_fw_stats.v1
            esi-corporations.read_medals.v1: esi-corporations.read_medals.v1
            esi-corporations.read_projects.v1: esi-corporations.read_projects.v1
            esi-corporations.read_standings.v1: esi-corporations.read_standings.v1
            esi-corporations.read_starbases.v1: esi-corporations.read_starbases.v1
            esi-corporations.read_structures.v1: esi-corporations.read_structures.v1
            esi-corporations.read_titles.v1: esi-corporations.read_titles.v1
            esi-corporations.track_members.v1: esi-corporations.track_members.v1
            esi-fittings.read_fittings.v1: esi-fittings.read_fittings.v1
            esi-fittings.write_fittings.v1: esi-fittings.write_fittings.v1
            esi-fleets.read_fleet.v1: esi-fleets.read_fleet.v1
            esi-fleets.write_fleet.v1: esi-fleets.write_fleet.v1
            esi-industry.read_character_jobs.v1: esi-industry.read_character_jobs.v1
            esi-industry.read_character_mining.v1: esi-industry.read_character_mining.v1
            esi-industry.read_corporation_jobs.v1: esi-industry.read_corporation_jobs.v1
            esi-industry.read_corporation_mining.v1: esi-industry.read_corporation_mining.v1
            esi-killmails.read_corporation_killmails.v1: esi-killmails.read_corporation_killmails.v1
            esi-killmails.read_killmails.v1: esi-killmails.read_killmails.v1
            esi-location.read_location.v1: esi-location.read_location.v1
            esi-location.read_online.v1: esi-location.read_online.v1
            esi-location.read_ship_type.v1: esi-location.read_ship_type.v1
            esi-mail.organize_mail.v1: esi-mail.organize_mail.v1
            esi-mail.read_mail.v1: esi-mail.read_mail.v1
            esi-mail.send_mail.v1: esi-mail.send_mail.v1
            esi-markets.read_character_orders.v1: esi-markets.read_character_orders.v1
            esi-markets.read_corporation_orders.v1: esi-markets.read_corporation_orders.v1
            esi-markets.structure_markets.v1: esi-markets.structure_markets.v1
            esi-planets.manage_planets.v1: esi-planets.manage_planets.v1
            esi-planets.read_customs_offices.v1: esi-planets.read_customs_offices.v1
            esi-search.search_structures.v1: esi-search.search_structures.v1
            esi-skills.read_skillqueue.v1: esi-skills.read_skillqueue.v1
            esi-skills.read_skills.v1: esi-skills.read_skills.v1
            esi-ui.open_window.v1: esi-ui.open_window.v1
            esi-ui.write_waypoint.v1: esi-ui.write_waypoint.v1
            esi-universe.read_structures.v1: esi-universe.read_structures.v1
            esi-wallet.read_character_wallet.v1: esi-wallet.read_character_wallet.v1
            esi-wallet.read_corporation_wallets.v1: esi-wallet.read_corporation_wallets.v1
          tokenUrl: https://login.eveonline.com/v2/oauth/token
      type: oauth2
