/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FwStatsGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FwStatsGetInner{}

// FwStatsGetInner struct for FwStatsGetInner
type FwStatsGetInner struct {
	FactionId int64 `json:"faction_id"`
	Kills FwStatsGetInnerKills `json:"kills"`
	// How many pilots fight for the given faction
	Pilots int64 `json:"pilots"`
	// The number of solar systems controlled by the given faction
	SystemsControlled int64 `json:"systems_controlled"`
	VictoryPoints FwStatsGetInnerVictoryPoints `json:"victory_points"`
}

type _FwStatsGetInner FwStatsGetInner

// NewFwStatsGetInner instantiates a new FwStatsGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFwStatsGetInner(factionId int64, kills FwStatsGetInnerKills, pilots int64, systemsControlled int64, victoryPoints FwStatsGetInnerVictoryPoints) *FwStatsGetInner {
	this := FwStatsGetInner{}
	this.FactionId = factionId
	this.Kills = kills
	this.Pilots = pilots
	this.SystemsControlled = systemsControlled
	this.VictoryPoints = victoryPoints
	return &this
}

// NewFwStatsGetInnerWithDefaults instantiates a new FwStatsGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFwStatsGetInnerWithDefaults() *FwStatsGetInner {
	this := FwStatsGetInner{}
	return &this
}

// GetFactionId returns the FactionId field value
func (o *FwStatsGetInner) GetFactionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FactionId
}

// GetFactionIdOk returns a tuple with the FactionId field value
// and a boolean to check if the value has been set.
func (o *FwStatsGetInner) GetFactionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FactionId, true
}

// SetFactionId sets field value
func (o *FwStatsGetInner) SetFactionId(v int64) {
	o.FactionId = v
}

// GetKills returns the Kills field value
func (o *FwStatsGetInner) GetKills() FwStatsGetInnerKills {
	if o == nil {
		var ret FwStatsGetInnerKills
		return ret
	}

	return o.Kills
}

// GetKillsOk returns a tuple with the Kills field value
// and a boolean to check if the value has been set.
func (o *FwStatsGetInner) GetKillsOk() (*FwStatsGetInnerKills, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kills, true
}

// SetKills sets field value
func (o *FwStatsGetInner) SetKills(v FwStatsGetInnerKills) {
	o.Kills = v
}

// GetPilots returns the Pilots field value
func (o *FwStatsGetInner) GetPilots() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Pilots
}

// GetPilotsOk returns a tuple with the Pilots field value
// and a boolean to check if the value has been set.
func (o *FwStatsGetInner) GetPilotsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pilots, true
}

// SetPilots sets field value
func (o *FwStatsGetInner) SetPilots(v int64) {
	o.Pilots = v
}

// GetSystemsControlled returns the SystemsControlled field value
func (o *FwStatsGetInner) GetSystemsControlled() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SystemsControlled
}

// GetSystemsControlledOk returns a tuple with the SystemsControlled field value
// and a boolean to check if the value has been set.
func (o *FwStatsGetInner) GetSystemsControlledOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SystemsControlled, true
}

// SetSystemsControlled sets field value
func (o *FwStatsGetInner) SetSystemsControlled(v int64) {
	o.SystemsControlled = v
}

// GetVictoryPoints returns the VictoryPoints field value
func (o *FwStatsGetInner) GetVictoryPoints() FwStatsGetInnerVictoryPoints {
	if o == nil {
		var ret FwStatsGetInnerVictoryPoints
		return ret
	}

	return o.VictoryPoints
}

// GetVictoryPointsOk returns a tuple with the VictoryPoints field value
// and a boolean to check if the value has been set.
func (o *FwStatsGetInner) GetVictoryPointsOk() (*FwStatsGetInnerVictoryPoints, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VictoryPoints, true
}

// SetVictoryPoints sets field value
func (o *FwStatsGetInner) SetVictoryPoints(v FwStatsGetInnerVictoryPoints) {
	o.VictoryPoints = v
}

func (o FwStatsGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FwStatsGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["faction_id"] = o.FactionId
	toSerialize["kills"] = o.Kills
	toSerialize["pilots"] = o.Pilots
	toSerialize["systems_controlled"] = o.SystemsControlled
	toSerialize["victory_points"] = o.VictoryPoints
	return toSerialize, nil
}

func (o *FwStatsGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"faction_id",
		"kills",
		"pilots",
		"systems_controlled",
		"victory_points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFwStatsGetInner := _FwStatsGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFwStatsGetInner)

	if err != nil {
		return err
	}

	*o = FwStatsGetInner(varFwStatsGetInner)

	return err
}

type NullableFwStatsGetInner struct {
	value *FwStatsGetInner
	isSet bool
}

func (v NullableFwStatsGetInner) Get() *FwStatsGetInner {
	return v.value
}

func (v *NullableFwStatsGetInner) Set(val *FwStatsGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFwStatsGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFwStatsGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFwStatsGetInner(val *FwStatsGetInner) *NullableFwStatsGetInner {
	return &NullableFwStatsGetInner{value: val, isSet: true}
}

func (v NullableFwStatsGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFwStatsGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


