/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FreelanceJobsDetailCreator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreelanceJobsDetailCreator{}

// FreelanceJobsDetailCreator struct for FreelanceJobsDetailCreator
type FreelanceJobsDetailCreator struct {
	Character FreelanceJobsDetailCreatorcharacter `json:"character"`
	Corporation FreelanceJobsDetailCreatorcorporation `json:"corporation"`
}

type _FreelanceJobsDetailCreator FreelanceJobsDetailCreator

// NewFreelanceJobsDetailCreator instantiates a new FreelanceJobsDetailCreator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreelanceJobsDetailCreator(character FreelanceJobsDetailCreatorcharacter, corporation FreelanceJobsDetailCreatorcorporation) *FreelanceJobsDetailCreator {
	this := FreelanceJobsDetailCreator{}
	this.Character = character
	this.Corporation = corporation
	return &this
}

// NewFreelanceJobsDetailCreatorWithDefaults instantiates a new FreelanceJobsDetailCreator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreelanceJobsDetailCreatorWithDefaults() *FreelanceJobsDetailCreator {
	this := FreelanceJobsDetailCreator{}
	return &this
}

// GetCharacter returns the Character field value
func (o *FreelanceJobsDetailCreator) GetCharacter() FreelanceJobsDetailCreatorcharacter {
	if o == nil {
		var ret FreelanceJobsDetailCreatorcharacter
		return ret
	}

	return o.Character
}

// GetCharacterOk returns a tuple with the Character field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetailCreator) GetCharacterOk() (*FreelanceJobsDetailCreatorcharacter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Character, true
}

// SetCharacter sets field value
func (o *FreelanceJobsDetailCreator) SetCharacter(v FreelanceJobsDetailCreatorcharacter) {
	o.Character = v
}

// GetCorporation returns the Corporation field value
func (o *FreelanceJobsDetailCreator) GetCorporation() FreelanceJobsDetailCreatorcorporation {
	if o == nil {
		var ret FreelanceJobsDetailCreatorcorporation
		return ret
	}

	return o.Corporation
}

// GetCorporationOk returns a tuple with the Corporation field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetailCreator) GetCorporationOk() (*FreelanceJobsDetailCreatorcorporation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Corporation, true
}

// SetCorporation sets field value
func (o *FreelanceJobsDetailCreator) SetCorporation(v FreelanceJobsDetailCreatorcorporation) {
	o.Corporation = v
}

func (o FreelanceJobsDetailCreator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreelanceJobsDetailCreator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["character"] = o.Character
	toSerialize["corporation"] = o.Corporation
	return toSerialize, nil
}

func (o *FreelanceJobsDetailCreator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"character",
		"corporation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreelanceJobsDetailCreator := _FreelanceJobsDetailCreator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreelanceJobsDetailCreator)

	if err != nil {
		return err
	}

	*o = FreelanceJobsDetailCreator(varFreelanceJobsDetailCreator)

	return err
}

type NullableFreelanceJobsDetailCreator struct {
	value *FreelanceJobsDetailCreator
	isSet bool
}

func (v NullableFreelanceJobsDetailCreator) Get() *FreelanceJobsDetailCreator {
	return v.value
}

func (v *NullableFreelanceJobsDetailCreator) Set(val *FreelanceJobsDetailCreator) {
	v.value = val
	v.isSet = true
}

func (v NullableFreelanceJobsDetailCreator) IsSet() bool {
	return v.isSet
}

func (v *NullableFreelanceJobsDetailCreator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreelanceJobsDetailCreator(val *FreelanceJobsDetailCreator) *NullableFreelanceJobsDetailCreator {
	return &NullableFreelanceJobsDetailCreator{value: val, isSet: true}
}

func (v NullableFreelanceJobsDetailCreator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreelanceJobsDetailCreator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


