/*
EVE Spring Inebriation (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-05-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CharactersStructuresMercenaryDensListingMercenaryden type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersStructuresMercenaryDensListingMercenaryden{}

// CharactersStructuresMercenaryDensListingMercenaryden struct for CharactersStructuresMercenaryDensListingMercenaryden
type CharactersStructuresMercenaryDensListingMercenaryden struct {
	Id int64 `json:"id"`
	PlanetId int64 `json:"planet_id"`
}

type _CharactersStructuresMercenaryDensListingMercenaryden CharactersStructuresMercenaryDensListingMercenaryden

// NewCharactersStructuresMercenaryDensListingMercenaryden instantiates a new CharactersStructuresMercenaryDensListingMercenaryden object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersStructuresMercenaryDensListingMercenaryden(id int64, planetId int64) *CharactersStructuresMercenaryDensListingMercenaryden {
	this := CharactersStructuresMercenaryDensListingMercenaryden{}
	this.Id = id
	this.PlanetId = planetId
	return &this
}

// NewCharactersStructuresMercenaryDensListingMercenarydenWithDefaults instantiates a new CharactersStructuresMercenaryDensListingMercenaryden object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersStructuresMercenaryDensListingMercenarydenWithDefaults() *CharactersStructuresMercenaryDensListingMercenaryden {
	this := CharactersStructuresMercenaryDensListingMercenaryden{}
	return &this
}

// GetId returns the Id field value
func (o *CharactersStructuresMercenaryDensListingMercenaryden) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CharactersStructuresMercenaryDensListingMercenaryden) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CharactersStructuresMercenaryDensListingMercenaryden) SetId(v int64) {
	o.Id = v
}

// GetPlanetId returns the PlanetId field value
func (o *CharactersStructuresMercenaryDensListingMercenaryden) GetPlanetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PlanetId
}

// GetPlanetIdOk returns a tuple with the PlanetId field value
// and a boolean to check if the value has been set.
func (o *CharactersStructuresMercenaryDensListingMercenaryden) GetPlanetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanetId, true
}

// SetPlanetId sets field value
func (o *CharactersStructuresMercenaryDensListingMercenaryden) SetPlanetId(v int64) {
	o.PlanetId = v
}

func (o CharactersStructuresMercenaryDensListingMercenaryden) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersStructuresMercenaryDensListingMercenaryden) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["planet_id"] = o.PlanetId
	return toSerialize, nil
}

func (o *CharactersStructuresMercenaryDensListingMercenaryden) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"planet_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersStructuresMercenaryDensListingMercenaryden := _CharactersStructuresMercenaryDensListingMercenaryden{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersStructuresMercenaryDensListingMercenaryden)

	if err != nil {
		return err
	}

	*o = CharactersStructuresMercenaryDensListingMercenaryden(varCharactersStructuresMercenaryDensListingMercenaryden)

	return err
}

type NullableCharactersStructuresMercenaryDensListingMercenaryden struct {
	value *CharactersStructuresMercenaryDensListingMercenaryden
	isSet bool
}

func (v NullableCharactersStructuresMercenaryDensListingMercenaryden) Get() *CharactersStructuresMercenaryDensListingMercenaryden {
	return v.value
}

func (v *NullableCharactersStructuresMercenaryDensListingMercenaryden) Set(val *CharactersStructuresMercenaryDensListingMercenaryden) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersStructuresMercenaryDensListingMercenaryden) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersStructuresMercenaryDensListingMercenaryden) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersStructuresMercenaryDensListingMercenaryden(val *CharactersStructuresMercenaryDensListingMercenaryden) *NullableCharactersStructuresMercenaryDensListingMercenaryden {
	return &NullableCharactersStructuresMercenaryDensListingMercenaryden{value: val, isSet: true}
}

func (v NullableCharactersStructuresMercenaryDensListingMercenaryden) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersStructuresMercenaryDensListingMercenaryden) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


