/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the CorporationsProjectsDetailConfigurationminematerial type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsProjectsDetailConfigurationminematerial{}

// CorporationsProjectsDetailConfigurationminematerial struct for CorporationsProjectsDetailConfigurationminematerial
type CorporationsProjectsDetailConfigurationminematerial struct {
	// Location to mine
	Locations []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner `json:"locations,omitempty"`
	// Materials to mine
	Materials []CorporationsProjectsDetailConfigurationdeliveritemItemsInner `json:"materials,omitempty"`
}

// NewCorporationsProjectsDetailConfigurationminematerial instantiates a new CorporationsProjectsDetailConfigurationminematerial object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsProjectsDetailConfigurationminematerial() *CorporationsProjectsDetailConfigurationminematerial {
	this := CorporationsProjectsDetailConfigurationminematerial{}
	return &this
}

// NewCorporationsProjectsDetailConfigurationminematerialWithDefaults instantiates a new CorporationsProjectsDetailConfigurationminematerial object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsProjectsDetailConfigurationminematerialWithDefaults() *CorporationsProjectsDetailConfigurationminematerial {
	this := CorporationsProjectsDetailConfigurationminematerial{}
	return &this
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationminematerial) GetLocations() []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner {
	if o == nil || IsNil(o.Locations) {
		var ret []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationminematerial) GetLocationsOk() ([]CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner, bool) {
	if o == nil || IsNil(o.Locations) {
		return nil, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationminematerial) HasLocations() bool {
	if o != nil && !IsNil(o.Locations) {
		return true
	}

	return false
}

// SetLocations gets a reference to the given []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner and assigns it to the Locations field.
func (o *CorporationsProjectsDetailConfigurationminematerial) SetLocations(v []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner) {
	o.Locations = v
}

// GetMaterials returns the Materials field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationminematerial) GetMaterials() []CorporationsProjectsDetailConfigurationdeliveritemItemsInner {
	if o == nil || IsNil(o.Materials) {
		var ret []CorporationsProjectsDetailConfigurationdeliveritemItemsInner
		return ret
	}
	return o.Materials
}

// GetMaterialsOk returns a tuple with the Materials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationminematerial) GetMaterialsOk() ([]CorporationsProjectsDetailConfigurationdeliveritemItemsInner, bool) {
	if o == nil || IsNil(o.Materials) {
		return nil, false
	}
	return o.Materials, true
}

// HasMaterials returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationminematerial) HasMaterials() bool {
	if o != nil && !IsNil(o.Materials) {
		return true
	}

	return false
}

// SetMaterials gets a reference to the given []CorporationsProjectsDetailConfigurationdeliveritemItemsInner and assigns it to the Materials field.
func (o *CorporationsProjectsDetailConfigurationminematerial) SetMaterials(v []CorporationsProjectsDetailConfigurationdeliveritemItemsInner) {
	o.Materials = v
}

func (o CorporationsProjectsDetailConfigurationminematerial) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsProjectsDetailConfigurationminematerial) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Locations) {
		toSerialize["locations"] = o.Locations
	}
	if !IsNil(o.Materials) {
		toSerialize["materials"] = o.Materials
	}
	return toSerialize, nil
}

type NullableCorporationsProjectsDetailConfigurationminematerial struct {
	value *CorporationsProjectsDetailConfigurationminematerial
	isSet bool
}

func (v NullableCorporationsProjectsDetailConfigurationminematerial) Get() *CorporationsProjectsDetailConfigurationminematerial {
	return v.value
}

func (v *NullableCorporationsProjectsDetailConfigurationminematerial) Set(val *CorporationsProjectsDetailConfigurationminematerial) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsProjectsDetailConfigurationminematerial) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsProjectsDetailConfigurationminematerial) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsProjectsDetailConfigurationminematerial(val *CorporationsProjectsDetailConfigurationminematerial) *NullableCorporationsProjectsDetailConfigurationminematerial {
	return &NullableCorporationsProjectsDetailConfigurationminematerial{value: val, isSet: true}
}

func (v NullableCorporationsProjectsDetailConfigurationminematerial) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsProjectsDetailConfigurationminematerial) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


