/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-09-30
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the CaptureFwComplex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptureFwComplex{}

// CaptureFwComplex struct for CaptureFwComplex
type CaptureFwComplex struct {
	CaptureFwComplex *CorporationsProjectsDetailConfigurationcapturefwcomplex `json:"capture_fw_complex,omitempty"`
}

// NewCaptureFwComplex instantiates a new CaptureFwComplex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptureFwComplex() *CaptureFwComplex {
	this := CaptureFwComplex{}
	return &this
}

// NewCaptureFwComplexWithDefaults instantiates a new CaptureFwComplex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptureFwComplexWithDefaults() *CaptureFwComplex {
	this := CaptureFwComplex{}
	return &this
}

// GetCaptureFwComplex returns the CaptureFwComplex field value if set, zero value otherwise.
func (o *CaptureFwComplex) GetCaptureFwComplex() CorporationsProjectsDetailConfigurationcapturefwcomplex {
	if o == nil || IsNil(o.CaptureFwComplex) {
		var ret CorporationsProjectsDetailConfigurationcapturefwcomplex
		return ret
	}
	return *o.CaptureFwComplex
}

// GetCaptureFwComplexOk returns a tuple with the CaptureFwComplex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CaptureFwComplex) GetCaptureFwComplexOk() (*CorporationsProjectsDetailConfigurationcapturefwcomplex, bool) {
	if o == nil || IsNil(o.CaptureFwComplex) {
		return nil, false
	}
	return o.CaptureFwComplex, true
}

// HasCaptureFwComplex returns a boolean if a field has been set.
func (o *CaptureFwComplex) HasCaptureFwComplex() bool {
	if o != nil && !IsNil(o.CaptureFwComplex) {
		return true
	}

	return false
}

// SetCaptureFwComplex gets a reference to the given CorporationsProjectsDetailConfigurationcapturefwcomplex and assigns it to the CaptureFwComplex field.
func (o *CaptureFwComplex) SetCaptureFwComplex(v CorporationsProjectsDetailConfigurationcapturefwcomplex) {
	o.CaptureFwComplex = &v
}

func (o CaptureFwComplex) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptureFwComplex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CaptureFwComplex) {
		toSerialize["capture_fw_complex"] = o.CaptureFwComplex
	}
	return toSerialize, nil
}

type NullableCaptureFwComplex struct {
	value *CaptureFwComplex
	isSet bool
}

func (v NullableCaptureFwComplex) Get() *CaptureFwComplex {
	return v.value
}

func (v *NullableCaptureFwComplex) Set(val *CaptureFwComplex) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptureFwComplex) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptureFwComplex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptureFwComplex(val *CaptureFwComplex) *NullableCaptureFwComplex {
	return &NullableCaptureFwComplex{value: val, isSet: true}
}

func (v NullableCaptureFwComplex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptureFwComplex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


