/*
EVE Swagger Incineration (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-06-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CorporationsStructuresSkyhooksDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsStructuresSkyhooksDetail{}

// CorporationsStructuresSkyhooksDetail struct for CorporationsStructuresSkyhooksDetail
type CorporationsStructuresSkyhooksDetail struct {
	// Skyhook's effective workforce; this can differ from the Skyhook's normal workforce due to the influence of an attached Mercenary Den
	EffectiveWorkforce *int64 `json:"effective_workforce,omitempty"`
	Id int64 `json:"id"`
	// Whether the Skyhook is active and producing workforce/power/reagents
	IsActive bool `json:"is_active"`
	PlanetId int64 `json:"planet_id"`
	// Skyhook's reagents
	Reagents []CorporationsStructuresSkyhooksDetailReagent `json:"reagents,omitempty"`
	ReinforcementTimer *CorporationsStructuresSkyhooksDetailReinforcementtimer `json:"reinforcement_timer,omitempty"`
	// Skyhook's state
	State string `json:"state"`
	TheftVulnerability *CorporationsStructuresSkyhooksDetailTheftvulnerability `json:"theft_vulnerability,omitempty"`
}

type _CorporationsStructuresSkyhooksDetail CorporationsStructuresSkyhooksDetail

// NewCorporationsStructuresSkyhooksDetail instantiates a new CorporationsStructuresSkyhooksDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsStructuresSkyhooksDetail(id int64, isActive bool, planetId int64, state string) *CorporationsStructuresSkyhooksDetail {
	this := CorporationsStructuresSkyhooksDetail{}
	this.Id = id
	this.IsActive = isActive
	this.PlanetId = planetId
	this.State = state
	return &this
}

// NewCorporationsStructuresSkyhooksDetailWithDefaults instantiates a new CorporationsStructuresSkyhooksDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsStructuresSkyhooksDetailWithDefaults() *CorporationsStructuresSkyhooksDetail {
	this := CorporationsStructuresSkyhooksDetail{}
	return &this
}

// GetEffectiveWorkforce returns the EffectiveWorkforce field value if set, zero value otherwise.
func (o *CorporationsStructuresSkyhooksDetail) GetEffectiveWorkforce() int64 {
	if o == nil || IsNil(o.EffectiveWorkforce) {
		var ret int64
		return ret
	}
	return *o.EffectiveWorkforce
}

// GetEffectiveWorkforceOk returns a tuple with the EffectiveWorkforce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetEffectiveWorkforceOk() (*int64, bool) {
	if o == nil || IsNil(o.EffectiveWorkforce) {
		return nil, false
	}
	return o.EffectiveWorkforce, true
}

// HasEffectiveWorkforce returns a boolean if a field has been set.
func (o *CorporationsStructuresSkyhooksDetail) HasEffectiveWorkforce() bool {
	if o != nil && !IsNil(o.EffectiveWorkforce) {
		return true
	}

	return false
}

// SetEffectiveWorkforce gets a reference to the given int64 and assigns it to the EffectiveWorkforce field.
func (o *CorporationsStructuresSkyhooksDetail) SetEffectiveWorkforce(v int64) {
	o.EffectiveWorkforce = &v
}

// GetId returns the Id field value
func (o *CorporationsStructuresSkyhooksDetail) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CorporationsStructuresSkyhooksDetail) SetId(v int64) {
	o.Id = v
}

// GetIsActive returns the IsActive field value
func (o *CorporationsStructuresSkyhooksDetail) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *CorporationsStructuresSkyhooksDetail) SetIsActive(v bool) {
	o.IsActive = v
}

// GetPlanetId returns the PlanetId field value
func (o *CorporationsStructuresSkyhooksDetail) GetPlanetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PlanetId
}

// GetPlanetIdOk returns a tuple with the PlanetId field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetPlanetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanetId, true
}

// SetPlanetId sets field value
func (o *CorporationsStructuresSkyhooksDetail) SetPlanetId(v int64) {
	o.PlanetId = v
}

// GetReagents returns the Reagents field value if set, zero value otherwise.
func (o *CorporationsStructuresSkyhooksDetail) GetReagents() []CorporationsStructuresSkyhooksDetailReagent {
	if o == nil || IsNil(o.Reagents) {
		var ret []CorporationsStructuresSkyhooksDetailReagent
		return ret
	}
	return o.Reagents
}

// GetReagentsOk returns a tuple with the Reagents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetReagentsOk() ([]CorporationsStructuresSkyhooksDetailReagent, bool) {
	if o == nil || IsNil(o.Reagents) {
		return nil, false
	}
	return o.Reagents, true
}

// HasReagents returns a boolean if a field has been set.
func (o *CorporationsStructuresSkyhooksDetail) HasReagents() bool {
	if o != nil && !IsNil(o.Reagents) {
		return true
	}

	return false
}

// SetReagents gets a reference to the given []CorporationsStructuresSkyhooksDetailReagent and assigns it to the Reagents field.
func (o *CorporationsStructuresSkyhooksDetail) SetReagents(v []CorporationsStructuresSkyhooksDetailReagent) {
	o.Reagents = v
}

// GetReinforcementTimer returns the ReinforcementTimer field value if set, zero value otherwise.
func (o *CorporationsStructuresSkyhooksDetail) GetReinforcementTimer() CorporationsStructuresSkyhooksDetailReinforcementtimer {
	if o == nil || IsNil(o.ReinforcementTimer) {
		var ret CorporationsStructuresSkyhooksDetailReinforcementtimer
		return ret
	}
	return *o.ReinforcementTimer
}

// GetReinforcementTimerOk returns a tuple with the ReinforcementTimer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetReinforcementTimerOk() (*CorporationsStructuresSkyhooksDetailReinforcementtimer, bool) {
	if o == nil || IsNil(o.ReinforcementTimer) {
		return nil, false
	}
	return o.ReinforcementTimer, true
}

// HasReinforcementTimer returns a boolean if a field has been set.
func (o *CorporationsStructuresSkyhooksDetail) HasReinforcementTimer() bool {
	if o != nil && !IsNil(o.ReinforcementTimer) {
		return true
	}

	return false
}

// SetReinforcementTimer gets a reference to the given CorporationsStructuresSkyhooksDetailReinforcementtimer and assigns it to the ReinforcementTimer field.
func (o *CorporationsStructuresSkyhooksDetail) SetReinforcementTimer(v CorporationsStructuresSkyhooksDetailReinforcementtimer) {
	o.ReinforcementTimer = &v
}

// GetState returns the State field value
func (o *CorporationsStructuresSkyhooksDetail) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CorporationsStructuresSkyhooksDetail) SetState(v string) {
	o.State = v
}

// GetTheftVulnerability returns the TheftVulnerability field value if set, zero value otherwise.
func (o *CorporationsStructuresSkyhooksDetail) GetTheftVulnerability() CorporationsStructuresSkyhooksDetailTheftvulnerability {
	if o == nil || IsNil(o.TheftVulnerability) {
		var ret CorporationsStructuresSkyhooksDetailTheftvulnerability
		return ret
	}
	return *o.TheftVulnerability
}

// GetTheftVulnerabilityOk returns a tuple with the TheftVulnerability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetail) GetTheftVulnerabilityOk() (*CorporationsStructuresSkyhooksDetailTheftvulnerability, bool) {
	if o == nil || IsNil(o.TheftVulnerability) {
		return nil, false
	}
	return o.TheftVulnerability, true
}

// HasTheftVulnerability returns a boolean if a field has been set.
func (o *CorporationsStructuresSkyhooksDetail) HasTheftVulnerability() bool {
	if o != nil && !IsNil(o.TheftVulnerability) {
		return true
	}

	return false
}

// SetTheftVulnerability gets a reference to the given CorporationsStructuresSkyhooksDetailTheftvulnerability and assigns it to the TheftVulnerability field.
func (o *CorporationsStructuresSkyhooksDetail) SetTheftVulnerability(v CorporationsStructuresSkyhooksDetailTheftvulnerability) {
	o.TheftVulnerability = &v
}

func (o CorporationsStructuresSkyhooksDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsStructuresSkyhooksDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EffectiveWorkforce) {
		toSerialize["effective_workforce"] = o.EffectiveWorkforce
	}
	toSerialize["id"] = o.Id
	toSerialize["is_active"] = o.IsActive
	toSerialize["planet_id"] = o.PlanetId
	if !IsNil(o.Reagents) {
		toSerialize["reagents"] = o.Reagents
	}
	if !IsNil(o.ReinforcementTimer) {
		toSerialize["reinforcement_timer"] = o.ReinforcementTimer
	}
	toSerialize["state"] = o.State
	if !IsNil(o.TheftVulnerability) {
		toSerialize["theft_vulnerability"] = o.TheftVulnerability
	}
	return toSerialize, nil
}

func (o *CorporationsStructuresSkyhooksDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"is_active",
		"planet_id",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsStructuresSkyhooksDetail := _CorporationsStructuresSkyhooksDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsStructuresSkyhooksDetail)

	if err != nil {
		return err
	}

	*o = CorporationsStructuresSkyhooksDetail(varCorporationsStructuresSkyhooksDetail)

	return err
}

type NullableCorporationsStructuresSkyhooksDetail struct {
	value *CorporationsStructuresSkyhooksDetail
	isSet bool
}

func (v NullableCorporationsStructuresSkyhooksDetail) Get() *CorporationsStructuresSkyhooksDetail {
	return v.value
}

func (v *NullableCorporationsStructuresSkyhooksDetail) Set(val *CorporationsStructuresSkyhooksDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsStructuresSkyhooksDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsStructuresSkyhooksDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsStructuresSkyhooksDetail(val *CorporationsStructuresSkyhooksDetail) *NullableCorporationsStructuresSkyhooksDetail {
	return &NullableCorporationsStructuresSkyhooksDetail{value: val, isSet: true}
}

func (v NullableCorporationsStructuresSkyhooksDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsStructuresSkyhooksDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


