/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostCharactersCharacterIdFittingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCharactersCharacterIdFittingsRequest{}

// PostCharactersCharacterIdFittingsRequest struct for PostCharactersCharacterIdFittingsRequest
type PostCharactersCharacterIdFittingsRequest struct {
	Description string `json:"description"`
	Items []PostCharactersCharacterIdFittingsRequestItemsInner `json:"items"`
	Name string `json:"name"`
	ShipTypeId int64 `json:"ship_type_id"`
}

type _PostCharactersCharacterIdFittingsRequest PostCharactersCharacterIdFittingsRequest

// NewPostCharactersCharacterIdFittingsRequest instantiates a new PostCharactersCharacterIdFittingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCharactersCharacterIdFittingsRequest(description string, items []PostCharactersCharacterIdFittingsRequestItemsInner, name string, shipTypeId int64) *PostCharactersCharacterIdFittingsRequest {
	this := PostCharactersCharacterIdFittingsRequest{}
	this.Description = description
	this.Items = items
	this.Name = name
	this.ShipTypeId = shipTypeId
	return &this
}

// NewPostCharactersCharacterIdFittingsRequestWithDefaults instantiates a new PostCharactersCharacterIdFittingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCharactersCharacterIdFittingsRequestWithDefaults() *PostCharactersCharacterIdFittingsRequest {
	this := PostCharactersCharacterIdFittingsRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *PostCharactersCharacterIdFittingsRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PostCharactersCharacterIdFittingsRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PostCharactersCharacterIdFittingsRequest) SetDescription(v string) {
	o.Description = v
}

// GetItems returns the Items field value
func (o *PostCharactersCharacterIdFittingsRequest) GetItems() []PostCharactersCharacterIdFittingsRequestItemsInner {
	if o == nil {
		var ret []PostCharactersCharacterIdFittingsRequestItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PostCharactersCharacterIdFittingsRequest) GetItemsOk() ([]PostCharactersCharacterIdFittingsRequestItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PostCharactersCharacterIdFittingsRequest) SetItems(v []PostCharactersCharacterIdFittingsRequestItemsInner) {
	o.Items = v
}

// GetName returns the Name field value
func (o *PostCharactersCharacterIdFittingsRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PostCharactersCharacterIdFittingsRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PostCharactersCharacterIdFittingsRequest) SetName(v string) {
	o.Name = v
}

// GetShipTypeId returns the ShipTypeId field value
func (o *PostCharactersCharacterIdFittingsRequest) GetShipTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ShipTypeId
}

// GetShipTypeIdOk returns a tuple with the ShipTypeId field value
// and a boolean to check if the value has been set.
func (o *PostCharactersCharacterIdFittingsRequest) GetShipTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipTypeId, true
}

// SetShipTypeId sets field value
func (o *PostCharactersCharacterIdFittingsRequest) SetShipTypeId(v int64) {
	o.ShipTypeId = v
}

func (o PostCharactersCharacterIdFittingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCharactersCharacterIdFittingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["items"] = o.Items
	toSerialize["name"] = o.Name
	toSerialize["ship_type_id"] = o.ShipTypeId
	return toSerialize, nil
}

func (o *PostCharactersCharacterIdFittingsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"items",
		"name",
		"ship_type_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCharactersCharacterIdFittingsRequest := _PostCharactersCharacterIdFittingsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCharactersCharacterIdFittingsRequest)

	if err != nil {
		return err
	}

	*o = PostCharactersCharacterIdFittingsRequest(varPostCharactersCharacterIdFittingsRequest)

	return err
}

type NullablePostCharactersCharacterIdFittingsRequest struct {
	value *PostCharactersCharacterIdFittingsRequest
	isSet bool
}

func (v NullablePostCharactersCharacterIdFittingsRequest) Get() *PostCharactersCharacterIdFittingsRequest {
	return v.value
}

func (v *NullablePostCharactersCharacterIdFittingsRequest) Set(val *PostCharactersCharacterIdFittingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCharactersCharacterIdFittingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCharactersCharacterIdFittingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCharactersCharacterIdFittingsRequest(val *PostCharactersCharacterIdFittingsRequest) *NullablePostCharactersCharacterIdFittingsRequest {
	return &NullablePostCharactersCharacterIdFittingsRequest{value: val, isSet: true}
}

func (v NullablePostCharactersCharacterIdFittingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCharactersCharacterIdFittingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


