/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FreelanceJobsDetailParametermatcher type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreelanceJobsDetailParametermatcher{}

// FreelanceJobsDetailParametermatcher struct for FreelanceJobsDetailParametermatcher
type FreelanceJobsDetailParametermatcher struct {
	// Value type(s) and their value(s)
	Values []FreelanceJobsDetailParametermatchervalue `json:"values"`
}

type _FreelanceJobsDetailParametermatcher FreelanceJobsDetailParametermatcher

// NewFreelanceJobsDetailParametermatcher instantiates a new FreelanceJobsDetailParametermatcher object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreelanceJobsDetailParametermatcher(values []FreelanceJobsDetailParametermatchervalue) *FreelanceJobsDetailParametermatcher {
	this := FreelanceJobsDetailParametermatcher{}
	this.Values = values
	return &this
}

// NewFreelanceJobsDetailParametermatcherWithDefaults instantiates a new FreelanceJobsDetailParametermatcher object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreelanceJobsDetailParametermatcherWithDefaults() *FreelanceJobsDetailParametermatcher {
	this := FreelanceJobsDetailParametermatcher{}
	return &this
}

// GetValues returns the Values field value
func (o *FreelanceJobsDetailParametermatcher) GetValues() []FreelanceJobsDetailParametermatchervalue {
	if o == nil {
		var ret []FreelanceJobsDetailParametermatchervalue
		return ret
	}

	return o.Values
}

// GetValuesOk returns a tuple with the Values field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetailParametermatcher) GetValuesOk() ([]FreelanceJobsDetailParametermatchervalue, bool) {
	if o == nil {
		return nil, false
	}
	return o.Values, true
}

// SetValues sets field value
func (o *FreelanceJobsDetailParametermatcher) SetValues(v []FreelanceJobsDetailParametermatchervalue) {
	o.Values = v
}

func (o FreelanceJobsDetailParametermatcher) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreelanceJobsDetailParametermatcher) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["values"] = o.Values
	return toSerialize, nil
}

func (o *FreelanceJobsDetailParametermatcher) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"values",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreelanceJobsDetailParametermatcher := _FreelanceJobsDetailParametermatcher{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreelanceJobsDetailParametermatcher)

	if err != nil {
		return err
	}

	*o = FreelanceJobsDetailParametermatcher(varFreelanceJobsDetailParametermatcher)

	return err
}

type NullableFreelanceJobsDetailParametermatcher struct {
	value *FreelanceJobsDetailParametermatcher
	isSet bool
}

func (v NullableFreelanceJobsDetailParametermatcher) Get() *FreelanceJobsDetailParametermatcher {
	return v.value
}

func (v *NullableFreelanceJobsDetailParametermatcher) Set(val *FreelanceJobsDetailParametermatcher) {
	v.value = val
	v.isSet = true
}

func (v NullableFreelanceJobsDetailParametermatcher) IsSet() bool {
	return v.isSet
}

func (v *NullableFreelanceJobsDetailParametermatcher) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreelanceJobsDetailParametermatcher(val *FreelanceJobsDetailParametermatcher) *NullableFreelanceJobsDetailParametermatcher {
	return &NullableFreelanceJobsDetailParametermatcher{value: val, isSet: true}
}

func (v NullableFreelanceJobsDetailParametermatcher) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreelanceJobsDetailParametermatcher) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


