/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdMembersTitlesGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdMembersTitlesGetInner{}

// CorporationsCorporationIdMembersTitlesGetInner struct for CorporationsCorporationIdMembersTitlesGetInner
type CorporationsCorporationIdMembersTitlesGetInner struct {
	CharacterId int64 `json:"character_id"`
	// A list of title_id
	Titles []int64 `json:"titles"`
}

type _CorporationsCorporationIdMembersTitlesGetInner CorporationsCorporationIdMembersTitlesGetInner

// NewCorporationsCorporationIdMembersTitlesGetInner instantiates a new CorporationsCorporationIdMembersTitlesGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdMembersTitlesGetInner(characterId int64, titles []int64) *CorporationsCorporationIdMembersTitlesGetInner {
	this := CorporationsCorporationIdMembersTitlesGetInner{}
	this.CharacterId = characterId
	this.Titles = titles
	return &this
}

// NewCorporationsCorporationIdMembersTitlesGetInnerWithDefaults instantiates a new CorporationsCorporationIdMembersTitlesGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdMembersTitlesGetInnerWithDefaults() *CorporationsCorporationIdMembersTitlesGetInner {
	this := CorporationsCorporationIdMembersTitlesGetInner{}
	return &this
}

// GetCharacterId returns the CharacterId field value
func (o *CorporationsCorporationIdMembersTitlesGetInner) GetCharacterId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMembersTitlesGetInner) GetCharacterIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterId, true
}

// SetCharacterId sets field value
func (o *CorporationsCorporationIdMembersTitlesGetInner) SetCharacterId(v int64) {
	o.CharacterId = v
}

// GetTitles returns the Titles field value
func (o *CorporationsCorporationIdMembersTitlesGetInner) GetTitles() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.Titles
}

// GetTitlesOk returns a tuple with the Titles field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMembersTitlesGetInner) GetTitlesOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Titles, true
}

// SetTitles sets field value
func (o *CorporationsCorporationIdMembersTitlesGetInner) SetTitles(v []int64) {
	o.Titles = v
}

func (o CorporationsCorporationIdMembersTitlesGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdMembersTitlesGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["character_id"] = o.CharacterId
	toSerialize["titles"] = o.Titles
	return toSerialize, nil
}

func (o *CorporationsCorporationIdMembersTitlesGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"character_id",
		"titles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdMembersTitlesGetInner := _CorporationsCorporationIdMembersTitlesGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdMembersTitlesGetInner)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdMembersTitlesGetInner(varCorporationsCorporationIdMembersTitlesGetInner)

	return err
}

type NullableCorporationsCorporationIdMembersTitlesGetInner struct {
	value *CorporationsCorporationIdMembersTitlesGetInner
	isSet bool
}

func (v NullableCorporationsCorporationIdMembersTitlesGetInner) Get() *CorporationsCorporationIdMembersTitlesGetInner {
	return v.value
}

func (v *NullableCorporationsCorporationIdMembersTitlesGetInner) Set(val *CorporationsCorporationIdMembersTitlesGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdMembersTitlesGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdMembersTitlesGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdMembersTitlesGetInner(val *CorporationsCorporationIdMembersTitlesGetInner) *NullableCorporationsCorporationIdMembersTitlesGetInner {
	return &NullableCorporationsCorporationIdMembersTitlesGetInner{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdMembersTitlesGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdMembersTitlesGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


