/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the DestroyNpc type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DestroyNpc{}

// DestroyNpc struct for DestroyNpc
type DestroyNpc struct {
	DestroyNpc *CorporationsProjectsDetailConfigurationdestroynpc `json:"destroy_npc,omitempty"`
}

// NewDestroyNpc instantiates a new DestroyNpc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestroyNpc() *DestroyNpc {
	this := DestroyNpc{}
	return &this
}

// NewDestroyNpcWithDefaults instantiates a new DestroyNpc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestroyNpcWithDefaults() *DestroyNpc {
	this := DestroyNpc{}
	return &this
}

// GetDestroyNpc returns the DestroyNpc field value if set, zero value otherwise.
func (o *DestroyNpc) GetDestroyNpc() CorporationsProjectsDetailConfigurationdestroynpc {
	if o == nil || IsNil(o.DestroyNpc) {
		var ret CorporationsProjectsDetailConfigurationdestroynpc
		return ret
	}
	return *o.DestroyNpc
}

// GetDestroyNpcOk returns a tuple with the DestroyNpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestroyNpc) GetDestroyNpcOk() (*CorporationsProjectsDetailConfigurationdestroynpc, bool) {
	if o == nil || IsNil(o.DestroyNpc) {
		return nil, false
	}
	return o.DestroyNpc, true
}

// HasDestroyNpc returns a boolean if a field has been set.
func (o *DestroyNpc) HasDestroyNpc() bool {
	if o != nil && !IsNil(o.DestroyNpc) {
		return true
	}

	return false
}

// SetDestroyNpc gets a reference to the given CorporationsProjectsDetailConfigurationdestroynpc and assigns it to the DestroyNpc field.
func (o *DestroyNpc) SetDestroyNpc(v CorporationsProjectsDetailConfigurationdestroynpc) {
	o.DestroyNpc = &v
}

func (o DestroyNpc) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DestroyNpc) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DestroyNpc) {
		toSerialize["destroy_npc"] = o.DestroyNpc
	}
	return toSerialize, nil
}

type NullableDestroyNpc struct {
	value *DestroyNpc
	isSet bool
}

func (v NullableDestroyNpc) Get() *DestroyNpc {
	return v.value
}

func (v *NullableDestroyNpc) Set(val *DestroyNpc) {
	v.value = val
	v.isSet = true
}

func (v NullableDestroyNpc) IsSet() bool {
	return v.isSet
}

func (v *NullableDestroyNpc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestroyNpc(val *DestroyNpc) *NullableDestroyNpc {
	return &NullableDestroyNpc{value: val, isSet: true}
}

func (v NullableDestroyNpc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestroyNpc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


