/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the LostShip type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LostShip{}

// LostShip struct for LostShip
type LostShip struct {
	LostShip *CorporationsProjectsDetailConfigurationlostship `json:"lost_ship,omitempty"`
}

// NewLostShip instantiates a new LostShip object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLostShip() *LostShip {
	this := LostShip{}
	return &this
}

// NewLostShipWithDefaults instantiates a new LostShip object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLostShipWithDefaults() *LostShip {
	this := LostShip{}
	return &this
}

// GetLostShip returns the LostShip field value if set, zero value otherwise.
func (o *LostShip) GetLostShip() CorporationsProjectsDetailConfigurationlostship {
	if o == nil || IsNil(o.LostShip) {
		var ret CorporationsProjectsDetailConfigurationlostship
		return ret
	}
	return *o.LostShip
}

// GetLostShipOk returns a tuple with the LostShip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LostShip) GetLostShipOk() (*CorporationsProjectsDetailConfigurationlostship, bool) {
	if o == nil || IsNil(o.LostShip) {
		return nil, false
	}
	return o.LostShip, true
}

// HasLostShip returns a boolean if a field has been set.
func (o *LostShip) HasLostShip() bool {
	if o != nil && !IsNil(o.LostShip) {
		return true
	}

	return false
}

// SetLostShip gets a reference to the given CorporationsProjectsDetailConfigurationlostship and assigns it to the LostShip field.
func (o *LostShip) SetLostShip(v CorporationsProjectsDetailConfigurationlostship) {
	o.LostShip = &v
}

func (o LostShip) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LostShip) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LostShip) {
		toSerialize["lost_ship"] = o.LostShip
	}
	return toSerialize, nil
}

type NullableLostShip struct {
	value *LostShip
	isSet bool
}

func (v NullableLostShip) Get() *LostShip {
	return v.value
}

func (v *NullableLostShip) Set(val *LostShip) {
	v.value = val
	v.isSet = true
}

func (v NullableLostShip) IsSet() bool {
	return v.isSet
}

func (v *NullableLostShip) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLostShip(val *LostShip) *NullableLostShip {
	return &NullableLostShip{value: val, isSet: true}
}

func (v NullableLostShip) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLostShip) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


