/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FreelanceJobsDetailProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreelanceJobsDetailProgress{}

// FreelanceJobsDetailProgress struct for FreelanceJobsDetailProgress
type FreelanceJobsDetailProgress struct {
	// Current progress
	Current int64 `json:"current"`
	// Desired progress
	Desired int64 `json:"desired"`
}

type _FreelanceJobsDetailProgress FreelanceJobsDetailProgress

// NewFreelanceJobsDetailProgress instantiates a new FreelanceJobsDetailProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreelanceJobsDetailProgress(current int64, desired int64) *FreelanceJobsDetailProgress {
	this := FreelanceJobsDetailProgress{}
	this.Current = current
	this.Desired = desired
	return &this
}

// NewFreelanceJobsDetailProgressWithDefaults instantiates a new FreelanceJobsDetailProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreelanceJobsDetailProgressWithDefaults() *FreelanceJobsDetailProgress {
	this := FreelanceJobsDetailProgress{}
	return &this
}

// GetCurrent returns the Current field value
func (o *FreelanceJobsDetailProgress) GetCurrent() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetailProgress) GetCurrentOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *FreelanceJobsDetailProgress) SetCurrent(v int64) {
	o.Current = v
}

// GetDesired returns the Desired field value
func (o *FreelanceJobsDetailProgress) GetDesired() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Desired
}

// GetDesiredOk returns a tuple with the Desired field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetailProgress) GetDesiredOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Desired, true
}

// SetDesired sets field value
func (o *FreelanceJobsDetailProgress) SetDesired(v int64) {
	o.Desired = v
}

func (o FreelanceJobsDetailProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreelanceJobsDetailProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["current"] = o.Current
	toSerialize["desired"] = o.Desired
	return toSerialize, nil
}

func (o *FreelanceJobsDetailProgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"current",
		"desired",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreelanceJobsDetailProgress := _FreelanceJobsDetailProgress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreelanceJobsDetailProgress)

	if err != nil {
		return err
	}

	*o = FreelanceJobsDetailProgress(varFreelanceJobsDetailProgress)

	return err
}

type NullableFreelanceJobsDetailProgress struct {
	value *FreelanceJobsDetailProgress
	isSet bool
}

func (v NullableFreelanceJobsDetailProgress) Get() *FreelanceJobsDetailProgress {
	return v.value
}

func (v *NullableFreelanceJobsDetailProgress) Set(val *FreelanceJobsDetailProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableFreelanceJobsDetailProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableFreelanceJobsDetailProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreelanceJobsDetailProgress(val *FreelanceJobsDetailProgress) *NullableFreelanceJobsDetailProgress {
	return &NullableFreelanceJobsDetailProgress{value: val, isSet: true}
}

func (v NullableFreelanceJobsDetailProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreelanceJobsDetailProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


