/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CharactersCharacterIdFittingsGetInnerItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersCharacterIdFittingsGetInnerItemsInner{}

// CharactersCharacterIdFittingsGetInnerItemsInner item object
type CharactersCharacterIdFittingsGetInnerItemsInner struct {
	Flag string `json:"flag"`
	Quantity int64 `json:"quantity"`
	TypeId int64 `json:"type_id"`
}

type _CharactersCharacterIdFittingsGetInnerItemsInner CharactersCharacterIdFittingsGetInnerItemsInner

// NewCharactersCharacterIdFittingsGetInnerItemsInner instantiates a new CharactersCharacterIdFittingsGetInnerItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersCharacterIdFittingsGetInnerItemsInner(flag string, quantity int64, typeId int64) *CharactersCharacterIdFittingsGetInnerItemsInner {
	this := CharactersCharacterIdFittingsGetInnerItemsInner{}
	this.Flag = flag
	this.Quantity = quantity
	this.TypeId = typeId
	return &this
}

// NewCharactersCharacterIdFittingsGetInnerItemsInnerWithDefaults instantiates a new CharactersCharacterIdFittingsGetInnerItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersCharacterIdFittingsGetInnerItemsInnerWithDefaults() *CharactersCharacterIdFittingsGetInnerItemsInner {
	this := CharactersCharacterIdFittingsGetInnerItemsInner{}
	return &this
}

// GetFlag returns the Flag field value
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) GetFlag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Flag
}

// GetFlagOk returns a tuple with the Flag field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) GetFlagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Flag, true
}

// SetFlag sets field value
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) SetFlag(v string) {
	o.Flag = v
}

// GetQuantity returns the Quantity field value
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) GetQuantity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) GetQuantityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) SetQuantity(v int64) {
	o.Quantity = v
}

// GetTypeId returns the TypeId field value
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) GetTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) GetTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeId, true
}

// SetTypeId sets field value
func (o *CharactersCharacterIdFittingsGetInnerItemsInner) SetTypeId(v int64) {
	o.TypeId = v
}

func (o CharactersCharacterIdFittingsGetInnerItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersCharacterIdFittingsGetInnerItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["flag"] = o.Flag
	toSerialize["quantity"] = o.Quantity
	toSerialize["type_id"] = o.TypeId
	return toSerialize, nil
}

func (o *CharactersCharacterIdFittingsGetInnerItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"flag",
		"quantity",
		"type_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersCharacterIdFittingsGetInnerItemsInner := _CharactersCharacterIdFittingsGetInnerItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersCharacterIdFittingsGetInnerItemsInner)

	if err != nil {
		return err
	}

	*o = CharactersCharacterIdFittingsGetInnerItemsInner(varCharactersCharacterIdFittingsGetInnerItemsInner)

	return err
}

type NullableCharactersCharacterIdFittingsGetInnerItemsInner struct {
	value *CharactersCharacterIdFittingsGetInnerItemsInner
	isSet bool
}

func (v NullableCharactersCharacterIdFittingsGetInnerItemsInner) Get() *CharactersCharacterIdFittingsGetInnerItemsInner {
	return v.value
}

func (v *NullableCharactersCharacterIdFittingsGetInnerItemsInner) Set(val *CharactersCharacterIdFittingsGetInnerItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersCharacterIdFittingsGetInnerItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersCharacterIdFittingsGetInnerItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersCharacterIdFittingsGetInnerItemsInner(val *CharactersCharacterIdFittingsGetInnerItemsInner) *NullableCharactersCharacterIdFittingsGetInnerItemsInner {
	return &NullableCharactersCharacterIdFittingsGetInnerItemsInner{value: val, isSet: true}
}

func (v NullableCharactersCharacterIdFittingsGetInnerItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersCharacterIdFittingsGetInnerItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


