/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostUiOpenwindowNewmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostUiOpenwindowNewmailRequest{}

// PostUiOpenwindowNewmailRequest struct for PostUiOpenwindowNewmailRequest
type PostUiOpenwindowNewmailRequest struct {
	Body string `json:"body"`
	Recipients []int64 `json:"recipients"`
	Subject string `json:"subject"`
	ToCorpOrAllianceId *int64 `json:"to_corp_or_alliance_id,omitempty"`
	// Corporations, alliances and mailing lists are all types of mailing groups. You may only send to one mailing group, at a time, so you may fill out either this field or the to_corp_or_alliance_ids field
	ToMailingListId *int64 `json:"to_mailing_list_id,omitempty"`
}

type _PostUiOpenwindowNewmailRequest PostUiOpenwindowNewmailRequest

// NewPostUiOpenwindowNewmailRequest instantiates a new PostUiOpenwindowNewmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostUiOpenwindowNewmailRequest(body string, recipients []int64, subject string) *PostUiOpenwindowNewmailRequest {
	this := PostUiOpenwindowNewmailRequest{}
	this.Body = body
	this.Recipients = recipients
	this.Subject = subject
	return &this
}

// NewPostUiOpenwindowNewmailRequestWithDefaults instantiates a new PostUiOpenwindowNewmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostUiOpenwindowNewmailRequestWithDefaults() *PostUiOpenwindowNewmailRequest {
	this := PostUiOpenwindowNewmailRequest{}
	return &this
}

// GetBody returns the Body field value
func (o *PostUiOpenwindowNewmailRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *PostUiOpenwindowNewmailRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *PostUiOpenwindowNewmailRequest) SetBody(v string) {
	o.Body = v
}

// GetRecipients returns the Recipients field value
func (o *PostUiOpenwindowNewmailRequest) GetRecipients() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value
// and a boolean to check if the value has been set.
func (o *PostUiOpenwindowNewmailRequest) GetRecipientsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipients, true
}

// SetRecipients sets field value
func (o *PostUiOpenwindowNewmailRequest) SetRecipients(v []int64) {
	o.Recipients = v
}

// GetSubject returns the Subject field value
func (o *PostUiOpenwindowNewmailRequest) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *PostUiOpenwindowNewmailRequest) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *PostUiOpenwindowNewmailRequest) SetSubject(v string) {
	o.Subject = v
}

// GetToCorpOrAllianceId returns the ToCorpOrAllianceId field value if set, zero value otherwise.
func (o *PostUiOpenwindowNewmailRequest) GetToCorpOrAllianceId() int64 {
	if o == nil || IsNil(o.ToCorpOrAllianceId) {
		var ret int64
		return ret
	}
	return *o.ToCorpOrAllianceId
}

// GetToCorpOrAllianceIdOk returns a tuple with the ToCorpOrAllianceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostUiOpenwindowNewmailRequest) GetToCorpOrAllianceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ToCorpOrAllianceId) {
		return nil, false
	}
	return o.ToCorpOrAllianceId, true
}

// HasToCorpOrAllianceId returns a boolean if a field has been set.
func (o *PostUiOpenwindowNewmailRequest) HasToCorpOrAllianceId() bool {
	if o != nil && !IsNil(o.ToCorpOrAllianceId) {
		return true
	}

	return false
}

// SetToCorpOrAllianceId gets a reference to the given int64 and assigns it to the ToCorpOrAllianceId field.
func (o *PostUiOpenwindowNewmailRequest) SetToCorpOrAllianceId(v int64) {
	o.ToCorpOrAllianceId = &v
}

// GetToMailingListId returns the ToMailingListId field value if set, zero value otherwise.
func (o *PostUiOpenwindowNewmailRequest) GetToMailingListId() int64 {
	if o == nil || IsNil(o.ToMailingListId) {
		var ret int64
		return ret
	}
	return *o.ToMailingListId
}

// GetToMailingListIdOk returns a tuple with the ToMailingListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostUiOpenwindowNewmailRequest) GetToMailingListIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ToMailingListId) {
		return nil, false
	}
	return o.ToMailingListId, true
}

// HasToMailingListId returns a boolean if a field has been set.
func (o *PostUiOpenwindowNewmailRequest) HasToMailingListId() bool {
	if o != nil && !IsNil(o.ToMailingListId) {
		return true
	}

	return false
}

// SetToMailingListId gets a reference to the given int64 and assigns it to the ToMailingListId field.
func (o *PostUiOpenwindowNewmailRequest) SetToMailingListId(v int64) {
	o.ToMailingListId = &v
}

func (o PostUiOpenwindowNewmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostUiOpenwindowNewmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["body"] = o.Body
	toSerialize["recipients"] = o.Recipients
	toSerialize["subject"] = o.Subject
	if !IsNil(o.ToCorpOrAllianceId) {
		toSerialize["to_corp_or_alliance_id"] = o.ToCorpOrAllianceId
	}
	if !IsNil(o.ToMailingListId) {
		toSerialize["to_mailing_list_id"] = o.ToMailingListId
	}
	return toSerialize, nil
}

func (o *PostUiOpenwindowNewmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"body",
		"recipients",
		"subject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostUiOpenwindowNewmailRequest := _PostUiOpenwindowNewmailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostUiOpenwindowNewmailRequest)

	if err != nil {
		return err
	}

	*o = PostUiOpenwindowNewmailRequest(varPostUiOpenwindowNewmailRequest)

	return err
}

type NullablePostUiOpenwindowNewmailRequest struct {
	value *PostUiOpenwindowNewmailRequest
	isSet bool
}

func (v NullablePostUiOpenwindowNewmailRequest) Get() *PostUiOpenwindowNewmailRequest {
	return v.value
}

func (v *NullablePostUiOpenwindowNewmailRequest) Set(val *PostUiOpenwindowNewmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostUiOpenwindowNewmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostUiOpenwindowNewmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostUiOpenwindowNewmailRequest(val *PostUiOpenwindowNewmailRequest) *NullablePostUiOpenwindowNewmailRequest {
	return &NullablePostUiOpenwindowNewmailRequest{value: val, isSet: true}
}

func (v NullablePostUiOpenwindowNewmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostUiOpenwindowNewmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


