/*
EVE SKINR Ingenuity (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-08-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the Remaining type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Remaining{}

// Remaining struct for Remaining
type Remaining struct {
	// Runs remaining on license
	Remaining *int64 `json:"remaining,omitempty"`
}

// NewRemaining instantiates a new Remaining object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemaining() *Remaining {
	this := Remaining{}
	return &this
}

// NewRemainingWithDefaults instantiates a new Remaining object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemainingWithDefaults() *Remaining {
	this := Remaining{}
	return &this
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *Remaining) GetRemaining() int64 {
	if o == nil || IsNil(o.Remaining) {
		var ret int64
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Remaining) GetRemainingOk() (*int64, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *Remaining) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given int64 and assigns it to the Remaining field.
func (o *Remaining) SetRemaining(v int64) {
	o.Remaining = &v
}

func (o Remaining) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Remaining) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	return toSerialize, nil
}

type NullableRemaining struct {
	value *Remaining
	isSet bool
}

func (v NullableRemaining) Get() *Remaining {
	return v.value
}

func (v *NullableRemaining) Set(val *Remaining) {
	v.value = val
	v.isSet = true
}

func (v NullableRemaining) IsSet() bool {
	return v.isSet
}

func (v *NullableRemaining) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemaining(val *Remaining) *NullableRemaining {
	return &NullableRemaining{value: val, isSet: true}
}

func (v NullableRemaining) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemaining) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


