/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CharactersCharacterIdPlanetsGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersCharacterIdPlanetsGetInner{}

// CharactersCharacterIdPlanetsGetInner struct for CharactersCharacterIdPlanetsGetInner
type CharactersCharacterIdPlanetsGetInner struct {
	LastUpdate time.Time `json:"last_update"`
	NumPins int64 `json:"num_pins"`
	OwnerId int64 `json:"owner_id"`
	PlanetId int64 `json:"planet_id"`
	PlanetType string `json:"planet_type"`
	SolarSystemId int64 `json:"solar_system_id"`
	UpgradeLevel int64 `json:"upgrade_level"`
}

type _CharactersCharacterIdPlanetsGetInner CharactersCharacterIdPlanetsGetInner

// NewCharactersCharacterIdPlanetsGetInner instantiates a new CharactersCharacterIdPlanetsGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersCharacterIdPlanetsGetInner(lastUpdate time.Time, numPins int64, ownerId int64, planetId int64, planetType string, solarSystemId int64, upgradeLevel int64) *CharactersCharacterIdPlanetsGetInner {
	this := CharactersCharacterIdPlanetsGetInner{}
	this.LastUpdate = lastUpdate
	this.NumPins = numPins
	this.OwnerId = ownerId
	this.PlanetId = planetId
	this.PlanetType = planetType
	this.SolarSystemId = solarSystemId
	this.UpgradeLevel = upgradeLevel
	return &this
}

// NewCharactersCharacterIdPlanetsGetInnerWithDefaults instantiates a new CharactersCharacterIdPlanetsGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersCharacterIdPlanetsGetInnerWithDefaults() *CharactersCharacterIdPlanetsGetInner {
	this := CharactersCharacterIdPlanetsGetInner{}
	return &this
}

// GetLastUpdate returns the LastUpdate field value
func (o *CharactersCharacterIdPlanetsGetInner) GetLastUpdate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetLastUpdateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetLastUpdate(v time.Time) {
	o.LastUpdate = v
}

// GetNumPins returns the NumPins field value
func (o *CharactersCharacterIdPlanetsGetInner) GetNumPins() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NumPins
}

// GetNumPinsOk returns a tuple with the NumPins field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetNumPinsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumPins, true
}

// SetNumPins sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetNumPins(v int64) {
	o.NumPins = v
}

// GetOwnerId returns the OwnerId field value
func (o *CharactersCharacterIdPlanetsGetInner) GetOwnerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetOwnerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerId, true
}

// SetOwnerId sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetOwnerId(v int64) {
	o.OwnerId = v
}

// GetPlanetId returns the PlanetId field value
func (o *CharactersCharacterIdPlanetsGetInner) GetPlanetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PlanetId
}

// GetPlanetIdOk returns a tuple with the PlanetId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetPlanetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanetId, true
}

// SetPlanetId sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetPlanetId(v int64) {
	o.PlanetId = v
}

// GetPlanetType returns the PlanetType field value
func (o *CharactersCharacterIdPlanetsGetInner) GetPlanetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanetType
}

// GetPlanetTypeOk returns a tuple with the PlanetType field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetPlanetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanetType, true
}

// SetPlanetType sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetPlanetType(v string) {
	o.PlanetType = v
}

// GetSolarSystemId returns the SolarSystemId field value
func (o *CharactersCharacterIdPlanetsGetInner) GetSolarSystemId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SolarSystemId
}

// GetSolarSystemIdOk returns a tuple with the SolarSystemId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetSolarSystemIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SolarSystemId, true
}

// SetSolarSystemId sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetSolarSystemId(v int64) {
	o.SolarSystemId = v
}

// GetUpgradeLevel returns the UpgradeLevel field value
func (o *CharactersCharacterIdPlanetsGetInner) GetUpgradeLevel() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UpgradeLevel
}

// GetUpgradeLevelOk returns a tuple with the UpgradeLevel field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsGetInner) GetUpgradeLevelOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpgradeLevel, true
}

// SetUpgradeLevel sets field value
func (o *CharactersCharacterIdPlanetsGetInner) SetUpgradeLevel(v int64) {
	o.UpgradeLevel = v
}

func (o CharactersCharacterIdPlanetsGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersCharacterIdPlanetsGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["last_update"] = o.LastUpdate
	toSerialize["num_pins"] = o.NumPins
	toSerialize["owner_id"] = o.OwnerId
	toSerialize["planet_id"] = o.PlanetId
	toSerialize["planet_type"] = o.PlanetType
	toSerialize["solar_system_id"] = o.SolarSystemId
	toSerialize["upgrade_level"] = o.UpgradeLevel
	return toSerialize, nil
}

func (o *CharactersCharacterIdPlanetsGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"last_update",
		"num_pins",
		"owner_id",
		"planet_id",
		"planet_type",
		"solar_system_id",
		"upgrade_level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersCharacterIdPlanetsGetInner := _CharactersCharacterIdPlanetsGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersCharacterIdPlanetsGetInner)

	if err != nil {
		return err
	}

	*o = CharactersCharacterIdPlanetsGetInner(varCharactersCharacterIdPlanetsGetInner)

	return err
}

type NullableCharactersCharacterIdPlanetsGetInner struct {
	value *CharactersCharacterIdPlanetsGetInner
	isSet bool
}

func (v NullableCharactersCharacterIdPlanetsGetInner) Get() *CharactersCharacterIdPlanetsGetInner {
	return v.value
}

func (v *NullableCharactersCharacterIdPlanetsGetInner) Set(val *CharactersCharacterIdPlanetsGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersCharacterIdPlanetsGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersCharacterIdPlanetsGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersCharacterIdPlanetsGetInner(val *CharactersCharacterIdPlanetsGetInner) *NullableCharactersCharacterIdPlanetsGetInner {
	return &NullableCharactersCharacterIdPlanetsGetInner{value: val, isSet: true}
}

func (v NullableCharactersCharacterIdPlanetsGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersCharacterIdPlanetsGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


