/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdOrdersHistoryGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdOrdersHistoryGetInner{}

// CorporationsCorporationIdOrdersHistoryGetInner struct for CorporationsCorporationIdOrdersHistoryGetInner
type CorporationsCorporationIdOrdersHistoryGetInner struct {
	// Number of days the order was valid for (starting from the issued date). An order expires at time issued + duration
	Duration int64 `json:"duration"`
	// For buy orders, the amount of ISK in escrow
	Escrow *float64 `json:"escrow,omitempty"`
	// True if the order is a bid (buy) order
	IsBuyOrder *bool `json:"is_buy_order,omitempty"`
	// Date and time when this order was issued
	Issued time.Time `json:"issued"`
	// The character who issued this order
	IssuedBy *int64 `json:"issued_by,omitempty"`
	// ID of the location where order was placed
	LocationId int64 `json:"location_id"`
	// For buy orders, the minimum quantity that will be accepted in a matching sell order
	MinVolume *int64 `json:"min_volume,omitempty"`
	// Unique order ID
	OrderId int64 `json:"order_id"`
	// Cost per unit for this order
	Price float64 `json:"price"`
	// Valid order range, numbers are ranges in jumps
	Range string `json:"range"`
	// ID of the region where order was placed
	RegionId int64 `json:"region_id"`
	// Current order state
	State string `json:"state"`
	// The type ID of the item transacted in this order
	TypeId int64 `json:"type_id"`
	// Quantity of items still required or offered
	VolumeRemain int64 `json:"volume_remain"`
	// Quantity of items required or offered at time order was placed
	VolumeTotal int64 `json:"volume_total"`
	// The corporation wallet division used for this order
	WalletDivision int64 `json:"wallet_division"`
}

type _CorporationsCorporationIdOrdersHistoryGetInner CorporationsCorporationIdOrdersHistoryGetInner

// NewCorporationsCorporationIdOrdersHistoryGetInner instantiates a new CorporationsCorporationIdOrdersHistoryGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdOrdersHistoryGetInner(duration int64, issued time.Time, locationId int64, orderId int64, price float64, range_ string, regionId int64, state string, typeId int64, volumeRemain int64, volumeTotal int64, walletDivision int64) *CorporationsCorporationIdOrdersHistoryGetInner {
	this := CorporationsCorporationIdOrdersHistoryGetInner{}
	this.Duration = duration
	this.Issued = issued
	this.LocationId = locationId
	this.OrderId = orderId
	this.Price = price
	this.Range = range_
	this.RegionId = regionId
	this.State = state
	this.TypeId = typeId
	this.VolumeRemain = volumeRemain
	this.VolumeTotal = volumeTotal
	this.WalletDivision = walletDivision
	return &this
}

// NewCorporationsCorporationIdOrdersHistoryGetInnerWithDefaults instantiates a new CorporationsCorporationIdOrdersHistoryGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdOrdersHistoryGetInnerWithDefaults() *CorporationsCorporationIdOrdersHistoryGetInner {
	this := CorporationsCorporationIdOrdersHistoryGetInner{}
	return &this
}

// GetDuration returns the Duration field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetDuration() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetDurationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetDuration(v int64) {
	o.Duration = v
}

// GetEscrow returns the Escrow field value if set, zero value otherwise.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetEscrow() float64 {
	if o == nil || IsNil(o.Escrow) {
		var ret float64
		return ret
	}
	return *o.Escrow
}

// GetEscrowOk returns a tuple with the Escrow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetEscrowOk() (*float64, bool) {
	if o == nil || IsNil(o.Escrow) {
		return nil, false
	}
	return o.Escrow, true
}

// HasEscrow returns a boolean if a field has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) HasEscrow() bool {
	if o != nil && !IsNil(o.Escrow) {
		return true
	}

	return false
}

// SetEscrow gets a reference to the given float64 and assigns it to the Escrow field.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetEscrow(v float64) {
	o.Escrow = &v
}

// GetIsBuyOrder returns the IsBuyOrder field value if set, zero value otherwise.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetIsBuyOrder() bool {
	if o == nil || IsNil(o.IsBuyOrder) {
		var ret bool
		return ret
	}
	return *o.IsBuyOrder
}

// GetIsBuyOrderOk returns a tuple with the IsBuyOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetIsBuyOrderOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBuyOrder) {
		return nil, false
	}
	return o.IsBuyOrder, true
}

// HasIsBuyOrder returns a boolean if a field has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) HasIsBuyOrder() bool {
	if o != nil && !IsNil(o.IsBuyOrder) {
		return true
	}

	return false
}

// SetIsBuyOrder gets a reference to the given bool and assigns it to the IsBuyOrder field.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetIsBuyOrder(v bool) {
	o.IsBuyOrder = &v
}

// GetIssued returns the Issued field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetIssued() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Issued
}

// GetIssuedOk returns a tuple with the Issued field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetIssuedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issued, true
}

// SetIssued sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetIssued(v time.Time) {
	o.Issued = v
}

// GetIssuedBy returns the IssuedBy field value if set, zero value otherwise.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetIssuedBy() int64 {
	if o == nil || IsNil(o.IssuedBy) {
		var ret int64
		return ret
	}
	return *o.IssuedBy
}

// GetIssuedByOk returns a tuple with the IssuedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetIssuedByOk() (*int64, bool) {
	if o == nil || IsNil(o.IssuedBy) {
		return nil, false
	}
	return o.IssuedBy, true
}

// HasIssuedBy returns a boolean if a field has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) HasIssuedBy() bool {
	if o != nil && !IsNil(o.IssuedBy) {
		return true
	}

	return false
}

// SetIssuedBy gets a reference to the given int64 and assigns it to the IssuedBy field.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetIssuedBy(v int64) {
	o.IssuedBy = &v
}

// GetLocationId returns the LocationId field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetLocationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetLocationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetLocationId(v int64) {
	o.LocationId = v
}

// GetMinVolume returns the MinVolume field value if set, zero value otherwise.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetMinVolume() int64 {
	if o == nil || IsNil(o.MinVolume) {
		var ret int64
		return ret
	}
	return *o.MinVolume
}

// GetMinVolumeOk returns a tuple with the MinVolume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetMinVolumeOk() (*int64, bool) {
	if o == nil || IsNil(o.MinVolume) {
		return nil, false
	}
	return o.MinVolume, true
}

// HasMinVolume returns a boolean if a field has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) HasMinVolume() bool {
	if o != nil && !IsNil(o.MinVolume) {
		return true
	}

	return false
}

// SetMinVolume gets a reference to the given int64 and assigns it to the MinVolume field.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetMinVolume(v int64) {
	o.MinVolume = &v
}

// GetOrderId returns the OrderId field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetOrderId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetOrderIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetOrderId(v int64) {
	o.OrderId = v
}

// GetPrice returns the Price field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetPrice() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetPriceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetPrice(v float64) {
	o.Price = v
}

// GetRange returns the Range field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetRange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetRangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Range, true
}

// SetRange sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetRange(v string) {
	o.Range = v
}

// GetRegionId returns the RegionId field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetRegionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetRegionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetRegionId(v int64) {
	o.RegionId = v
}

// GetState returns the State field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetState(v string) {
	o.State = v
}

// GetTypeId returns the TypeId field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeId, true
}

// SetTypeId sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetTypeId(v int64) {
	o.TypeId = v
}

// GetVolumeRemain returns the VolumeRemain field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetVolumeRemain() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.VolumeRemain
}

// GetVolumeRemainOk returns a tuple with the VolumeRemain field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetVolumeRemainOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VolumeRemain, true
}

// SetVolumeRemain sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetVolumeRemain(v int64) {
	o.VolumeRemain = v
}

// GetVolumeTotal returns the VolumeTotal field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetVolumeTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.VolumeTotal
}

// GetVolumeTotalOk returns a tuple with the VolumeTotal field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetVolumeTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VolumeTotal, true
}

// SetVolumeTotal sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetVolumeTotal(v int64) {
	o.VolumeTotal = v
}

// GetWalletDivision returns the WalletDivision field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetWalletDivision() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WalletDivision
}

// GetWalletDivisionOk returns a tuple with the WalletDivision field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdOrdersHistoryGetInner) GetWalletDivisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletDivision, true
}

// SetWalletDivision sets field value
func (o *CorporationsCorporationIdOrdersHistoryGetInner) SetWalletDivision(v int64) {
	o.WalletDivision = v
}

func (o CorporationsCorporationIdOrdersHistoryGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdOrdersHistoryGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["duration"] = o.Duration
	if !IsNil(o.Escrow) {
		toSerialize["escrow"] = o.Escrow
	}
	if !IsNil(o.IsBuyOrder) {
		toSerialize["is_buy_order"] = o.IsBuyOrder
	}
	toSerialize["issued"] = o.Issued
	if !IsNil(o.IssuedBy) {
		toSerialize["issued_by"] = o.IssuedBy
	}
	toSerialize["location_id"] = o.LocationId
	if !IsNil(o.MinVolume) {
		toSerialize["min_volume"] = o.MinVolume
	}
	toSerialize["order_id"] = o.OrderId
	toSerialize["price"] = o.Price
	toSerialize["range"] = o.Range
	toSerialize["region_id"] = o.RegionId
	toSerialize["state"] = o.State
	toSerialize["type_id"] = o.TypeId
	toSerialize["volume_remain"] = o.VolumeRemain
	toSerialize["volume_total"] = o.VolumeTotal
	toSerialize["wallet_division"] = o.WalletDivision
	return toSerialize, nil
}

func (o *CorporationsCorporationIdOrdersHistoryGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"duration",
		"issued",
		"location_id",
		"order_id",
		"price",
		"range",
		"region_id",
		"state",
		"type_id",
		"volume_remain",
		"volume_total",
		"wallet_division",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdOrdersHistoryGetInner := _CorporationsCorporationIdOrdersHistoryGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdOrdersHistoryGetInner)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdOrdersHistoryGetInner(varCorporationsCorporationIdOrdersHistoryGetInner)

	return err
}

type NullableCorporationsCorporationIdOrdersHistoryGetInner struct {
	value *CorporationsCorporationIdOrdersHistoryGetInner
	isSet bool
}

func (v NullableCorporationsCorporationIdOrdersHistoryGetInner) Get() *CorporationsCorporationIdOrdersHistoryGetInner {
	return v.value
}

func (v *NullableCorporationsCorporationIdOrdersHistoryGetInner) Set(val *CorporationsCorporationIdOrdersHistoryGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdOrdersHistoryGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdOrdersHistoryGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdOrdersHistoryGetInner(val *CorporationsCorporationIdOrdersHistoryGetInner) *NullableCorporationsCorporationIdOrdersHistoryGetInner {
	return &NullableCorporationsCorporationIdOrdersHistoryGetInner{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdOrdersHistoryGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdOrdersHistoryGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


