/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner{}

// CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner head object
type CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner struct {
	HeadId int64 `json:"head_id"`
	Latitude float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type _CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner

// NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner instantiates a new CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner(headId int64, latitude float64, longitude float64) *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner {
	this := CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner{}
	this.HeadId = headId
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerWithDefaults instantiates a new CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInnerWithDefaults() *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner {
	this := CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner{}
	return &this
}

// GetHeadId returns the HeadId field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) GetHeadId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.HeadId
}

// GetHeadIdOk returns a tuple with the HeadId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) GetHeadIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeadId, true
}

// SetHeadId sets field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) SetHeadId(v int64) {
	o.HeadId = v
}

// GetLatitude returns the Latitude field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) SetLatitude(v float64) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) SetLongitude(v float64) {
	o.Longitude = v
}

func (o CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["head_id"] = o.HeadId
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	return toSerialize, nil
}

func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"head_id",
		"latitude",
		"longitude",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner := _CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner)

	if err != nil {
		return err
	}

	*o = CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner(varCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner)

	return err
}

type NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner struct {
	value *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner
	isSet bool
}

func (v NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) Get() *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner {
	return v.value
}

func (v *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) Set(val *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner(val *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner {
	return &NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner{value: val, isSet: true}
}

func (v NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


