/*
EVE Swagger Incineration (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-07-17
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CorporationsStructuresSkyhooksDetailReagent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsStructuresSkyhooksDetailReagent{}

// CorporationsStructuresSkyhooksDetailReagent struct for CorporationsStructuresSkyhooksDetailReagent
type CorporationsStructuresSkyhooksDetailReagent struct {
	// Moment the 'SecureStock'/'UnsecuredStock' value had its last cycle; use SDE to calculate the current values
	LastCycle time.Time `json:"last_cycle"`
	// Secured stock of the reagent at the time of 'last_cycle'
	SecuredStock int64 `json:"secured_stock"`
	TypeId int64 `json:"type_id"`
	// Unsecured stock of the reagent at the time of 'last_cycle'
	UnsecuredStock int64 `json:"unsecured_stock"`
}

type _CorporationsStructuresSkyhooksDetailReagent CorporationsStructuresSkyhooksDetailReagent

// NewCorporationsStructuresSkyhooksDetailReagent instantiates a new CorporationsStructuresSkyhooksDetailReagent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsStructuresSkyhooksDetailReagent(lastCycle time.Time, securedStock int64, typeId int64, unsecuredStock int64) *CorporationsStructuresSkyhooksDetailReagent {
	this := CorporationsStructuresSkyhooksDetailReagent{}
	this.LastCycle = lastCycle
	this.SecuredStock = securedStock
	this.TypeId = typeId
	this.UnsecuredStock = unsecuredStock
	return &this
}

// NewCorporationsStructuresSkyhooksDetailReagentWithDefaults instantiates a new CorporationsStructuresSkyhooksDetailReagent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsStructuresSkyhooksDetailReagentWithDefaults() *CorporationsStructuresSkyhooksDetailReagent {
	this := CorporationsStructuresSkyhooksDetailReagent{}
	return &this
}

// GetLastCycle returns the LastCycle field value
func (o *CorporationsStructuresSkyhooksDetailReagent) GetLastCycle() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastCycle
}

// GetLastCycleOk returns a tuple with the LastCycle field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetailReagent) GetLastCycleOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastCycle, true
}

// SetLastCycle sets field value
func (o *CorporationsStructuresSkyhooksDetailReagent) SetLastCycle(v time.Time) {
	o.LastCycle = v
}

// GetSecuredStock returns the SecuredStock field value
func (o *CorporationsStructuresSkyhooksDetailReagent) GetSecuredStock() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SecuredStock
}

// GetSecuredStockOk returns a tuple with the SecuredStock field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetailReagent) GetSecuredStockOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecuredStock, true
}

// SetSecuredStock sets field value
func (o *CorporationsStructuresSkyhooksDetailReagent) SetSecuredStock(v int64) {
	o.SecuredStock = v
}

// GetTypeId returns the TypeId field value
func (o *CorporationsStructuresSkyhooksDetailReagent) GetTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetailReagent) GetTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeId, true
}

// SetTypeId sets field value
func (o *CorporationsStructuresSkyhooksDetailReagent) SetTypeId(v int64) {
	o.TypeId = v
}

// GetUnsecuredStock returns the UnsecuredStock field value
func (o *CorporationsStructuresSkyhooksDetailReagent) GetUnsecuredStock() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UnsecuredStock
}

// GetUnsecuredStockOk returns a tuple with the UnsecuredStock field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSkyhooksDetailReagent) GetUnsecuredStockOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnsecuredStock, true
}

// SetUnsecuredStock sets field value
func (o *CorporationsStructuresSkyhooksDetailReagent) SetUnsecuredStock(v int64) {
	o.UnsecuredStock = v
}

func (o CorporationsStructuresSkyhooksDetailReagent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsStructuresSkyhooksDetailReagent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["last_cycle"] = o.LastCycle
	toSerialize["secured_stock"] = o.SecuredStock
	toSerialize["type_id"] = o.TypeId
	toSerialize["unsecured_stock"] = o.UnsecuredStock
	return toSerialize, nil
}

func (o *CorporationsStructuresSkyhooksDetailReagent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"last_cycle",
		"secured_stock",
		"type_id",
		"unsecured_stock",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsStructuresSkyhooksDetailReagent := _CorporationsStructuresSkyhooksDetailReagent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsStructuresSkyhooksDetailReagent)

	if err != nil {
		return err
	}

	*o = CorporationsStructuresSkyhooksDetailReagent(varCorporationsStructuresSkyhooksDetailReagent)

	return err
}

type NullableCorporationsStructuresSkyhooksDetailReagent struct {
	value *CorporationsStructuresSkyhooksDetailReagent
	isSet bool
}

func (v NullableCorporationsStructuresSkyhooksDetailReagent) Get() *CorporationsStructuresSkyhooksDetailReagent {
	return v.value
}

func (v *NullableCorporationsStructuresSkyhooksDetailReagent) Set(val *CorporationsStructuresSkyhooksDetailReagent) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsStructuresSkyhooksDetailReagent) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsStructuresSkyhooksDetailReagent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsStructuresSkyhooksDetailReagent(val *CorporationsStructuresSkyhooksDetailReagent) *NullableCorporationsStructuresSkyhooksDetailReagent {
	return &NullableCorporationsStructuresSkyhooksDetailReagent{value: val, isSet: true}
}

func (v NullableCorporationsStructuresSkyhooksDetailReagent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsStructuresSkyhooksDetailReagent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


