/*
EVE SKINR Ingenuity (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-08-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MilitaryCampaignsListing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MilitaryCampaignsListing{}

// MilitaryCampaignsListing struct for MilitaryCampaignsListing
type MilitaryCampaignsListing struct {
	// List of military campaigns
	Campaigns []MilitaryCampaignsDetailCampaign `json:"campaigns"`
}

type _MilitaryCampaignsListing MilitaryCampaignsListing

// NewMilitaryCampaignsListing instantiates a new MilitaryCampaignsListing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMilitaryCampaignsListing(campaigns []MilitaryCampaignsDetailCampaign) *MilitaryCampaignsListing {
	this := MilitaryCampaignsListing{}
	this.Campaigns = campaigns
	return &this
}

// NewMilitaryCampaignsListingWithDefaults instantiates a new MilitaryCampaignsListing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMilitaryCampaignsListingWithDefaults() *MilitaryCampaignsListing {
	this := MilitaryCampaignsListing{}
	return &this
}

// GetCampaigns returns the Campaigns field value
func (o *MilitaryCampaignsListing) GetCampaigns() []MilitaryCampaignsDetailCampaign {
	if o == nil {
		var ret []MilitaryCampaignsDetailCampaign
		return ret
	}

	return o.Campaigns
}

// GetCampaignsOk returns a tuple with the Campaigns field value
// and a boolean to check if the value has been set.
func (o *MilitaryCampaignsListing) GetCampaignsOk() ([]MilitaryCampaignsDetailCampaign, bool) {
	if o == nil {
		return nil, false
	}
	return o.Campaigns, true
}

// SetCampaigns sets field value
func (o *MilitaryCampaignsListing) SetCampaigns(v []MilitaryCampaignsDetailCampaign) {
	o.Campaigns = v
}

func (o MilitaryCampaignsListing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MilitaryCampaignsListing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaigns"] = o.Campaigns
	return toSerialize, nil
}

func (o *MilitaryCampaignsListing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"campaigns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMilitaryCampaignsListing := _MilitaryCampaignsListing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMilitaryCampaignsListing)

	if err != nil {
		return err
	}

	*o = MilitaryCampaignsListing(varMilitaryCampaignsListing)

	return err
}

type NullableMilitaryCampaignsListing struct {
	value *MilitaryCampaignsListing
	isSet bool
}

func (v NullableMilitaryCampaignsListing) Get() *MilitaryCampaignsListing {
	return v.value
}

func (v *NullableMilitaryCampaignsListing) Set(val *MilitaryCampaignsListing) {
	v.value = val
	v.isSet = true
}

func (v NullableMilitaryCampaignsListing) IsSet() bool {
	return v.isSet
}

func (v *NullableMilitaryCampaignsListing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMilitaryCampaignsListing(val *MilitaryCampaignsListing) *NullableMilitaryCampaignsListing {
	return &NullableMilitaryCampaignsListing{value: val, isSet: true}
}

func (v NullableMilitaryCampaignsListing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMilitaryCampaignsListing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


