/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CharactersDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersDetail{}

// CharactersDetail struct for CharactersDetail
type CharactersDetail struct {
	AllianceId *int64 `json:"alliance_id,omitempty"`
	// Character's creation date
	Birthday time.Time `json:"birthday"`
	BloodlineId int64 `json:"bloodline_id"`
	CorporationId int64 `json:"corporation_id"`
	// Character's description (biography)
	Description *string `json:"description,omitempty"`
	FactionId *int64 `json:"faction_id,omitempty"`
	// Character's gender
	Gender string `json:"gender"`
	// Character's name
	Name string `json:"name"`
	RaceId int64 `json:"race_id"`
	// Character's security status
	SecurityStatus *float64 `json:"security_status,omitempty"`
	// Character's corporation title
	Title *string `json:"title,omitempty"`
}

type _CharactersDetail CharactersDetail

// NewCharactersDetail instantiates a new CharactersDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersDetail(birthday time.Time, bloodlineId int64, corporationId int64, gender string, name string, raceId int64) *CharactersDetail {
	this := CharactersDetail{}
	this.Birthday = birthday
	this.BloodlineId = bloodlineId
	this.CorporationId = corporationId
	this.Gender = gender
	this.Name = name
	this.RaceId = raceId
	return &this
}

// NewCharactersDetailWithDefaults instantiates a new CharactersDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersDetailWithDefaults() *CharactersDetail {
	this := CharactersDetail{}
	return &this
}

// GetAllianceId returns the AllianceId field value if set, zero value otherwise.
func (o *CharactersDetail) GetAllianceId() int64 {
	if o == nil || IsNil(o.AllianceId) {
		var ret int64
		return ret
	}
	return *o.AllianceId
}

// GetAllianceIdOk returns a tuple with the AllianceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetAllianceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.AllianceId) {
		return nil, false
	}
	return o.AllianceId, true
}

// HasAllianceId returns a boolean if a field has been set.
func (o *CharactersDetail) HasAllianceId() bool {
	if o != nil && !IsNil(o.AllianceId) {
		return true
	}

	return false
}

// SetAllianceId gets a reference to the given int64 and assigns it to the AllianceId field.
func (o *CharactersDetail) SetAllianceId(v int64) {
	o.AllianceId = &v
}

// GetBirthday returns the Birthday field value
func (o *CharactersDetail) GetBirthday() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Birthday
}

// GetBirthdayOk returns a tuple with the Birthday field value
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetBirthdayOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Birthday, true
}

// SetBirthday sets field value
func (o *CharactersDetail) SetBirthday(v time.Time) {
	o.Birthday = v
}

// GetBloodlineId returns the BloodlineId field value
func (o *CharactersDetail) GetBloodlineId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BloodlineId
}

// GetBloodlineIdOk returns a tuple with the BloodlineId field value
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetBloodlineIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BloodlineId, true
}

// SetBloodlineId sets field value
func (o *CharactersDetail) SetBloodlineId(v int64) {
	o.BloodlineId = v
}

// GetCorporationId returns the CorporationId field value
func (o *CharactersDetail) GetCorporationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CorporationId
}

// GetCorporationIdOk returns a tuple with the CorporationId field value
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetCorporationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorporationId, true
}

// SetCorporationId sets field value
func (o *CharactersDetail) SetCorporationId(v int64) {
	o.CorporationId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CharactersDetail) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CharactersDetail) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CharactersDetail) SetDescription(v string) {
	o.Description = &v
}

// GetFactionId returns the FactionId field value if set, zero value otherwise.
func (o *CharactersDetail) GetFactionId() int64 {
	if o == nil || IsNil(o.FactionId) {
		var ret int64
		return ret
	}
	return *o.FactionId
}

// GetFactionIdOk returns a tuple with the FactionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetFactionIdOk() (*int64, bool) {
	if o == nil || IsNil(o.FactionId) {
		return nil, false
	}
	return o.FactionId, true
}

// HasFactionId returns a boolean if a field has been set.
func (o *CharactersDetail) HasFactionId() bool {
	if o != nil && !IsNil(o.FactionId) {
		return true
	}

	return false
}

// SetFactionId gets a reference to the given int64 and assigns it to the FactionId field.
func (o *CharactersDetail) SetFactionId(v int64) {
	o.FactionId = &v
}

// GetGender returns the Gender field value
func (o *CharactersDetail) GetGender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gender
}

// GetGenderOk returns a tuple with the Gender field value
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetGenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gender, true
}

// SetGender sets field value
func (o *CharactersDetail) SetGender(v string) {
	o.Gender = v
}

// GetName returns the Name field value
func (o *CharactersDetail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CharactersDetail) SetName(v string) {
	o.Name = v
}

// GetRaceId returns the RaceId field value
func (o *CharactersDetail) GetRaceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RaceId
}

// GetRaceIdOk returns a tuple with the RaceId field value
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetRaceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RaceId, true
}

// SetRaceId sets field value
func (o *CharactersDetail) SetRaceId(v int64) {
	o.RaceId = v
}

// GetSecurityStatus returns the SecurityStatus field value if set, zero value otherwise.
func (o *CharactersDetail) GetSecurityStatus() float64 {
	if o == nil || IsNil(o.SecurityStatus) {
		var ret float64
		return ret
	}
	return *o.SecurityStatus
}

// GetSecurityStatusOk returns a tuple with the SecurityStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetSecurityStatusOk() (*float64, bool) {
	if o == nil || IsNil(o.SecurityStatus) {
		return nil, false
	}
	return o.SecurityStatus, true
}

// HasSecurityStatus returns a boolean if a field has been set.
func (o *CharactersDetail) HasSecurityStatus() bool {
	if o != nil && !IsNil(o.SecurityStatus) {
		return true
	}

	return false
}

// SetSecurityStatus gets a reference to the given float64 and assigns it to the SecurityStatus field.
func (o *CharactersDetail) SetSecurityStatus(v float64) {
	o.SecurityStatus = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CharactersDetail) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersDetail) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CharactersDetail) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CharactersDetail) SetTitle(v string) {
	o.Title = &v
}

func (o CharactersDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllianceId) {
		toSerialize["alliance_id"] = o.AllianceId
	}
	toSerialize["birthday"] = o.Birthday
	toSerialize["bloodline_id"] = o.BloodlineId
	toSerialize["corporation_id"] = o.CorporationId
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.FactionId) {
		toSerialize["faction_id"] = o.FactionId
	}
	toSerialize["gender"] = o.Gender
	toSerialize["name"] = o.Name
	toSerialize["race_id"] = o.RaceId
	if !IsNil(o.SecurityStatus) {
		toSerialize["security_status"] = o.SecurityStatus
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

func (o *CharactersDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"birthday",
		"bloodline_id",
		"corporation_id",
		"gender",
		"name",
		"race_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersDetail := _CharactersDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersDetail)

	if err != nil {
		return err
	}

	*o = CharactersDetail(varCharactersDetail)

	return err
}

type NullableCharactersDetail struct {
	value *CharactersDetail
	isSet bool
}

func (v NullableCharactersDetail) Get() *CharactersDetail {
	return v.value
}

func (v *NullableCharactersDetail) Set(val *CharactersDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersDetail(val *CharactersDetail) *NullableCharactersDetail {
	return &NullableCharactersDetail{value: val, isSet: true}
}

func (v NullableCharactersDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


