/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the PutCharactersCharacterIdMailMailIdRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutCharactersCharacterIdMailMailIdRequest{}

// PutCharactersCharacterIdMailMailIdRequest struct for PutCharactersCharacterIdMailMailIdRequest
type PutCharactersCharacterIdMailMailIdRequest struct {
	// Labels to assign to the mail. Pre-existing labels are unassigned.
	Labels []int64 `json:"labels,omitempty"`
	// Whether the mail is flagged as read
	Read *bool `json:"read,omitempty"`
}

// NewPutCharactersCharacterIdMailMailIdRequest instantiates a new PutCharactersCharacterIdMailMailIdRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutCharactersCharacterIdMailMailIdRequest() *PutCharactersCharacterIdMailMailIdRequest {
	this := PutCharactersCharacterIdMailMailIdRequest{}
	return &this
}

// NewPutCharactersCharacterIdMailMailIdRequestWithDefaults instantiates a new PutCharactersCharacterIdMailMailIdRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutCharactersCharacterIdMailMailIdRequestWithDefaults() *PutCharactersCharacterIdMailMailIdRequest {
	this := PutCharactersCharacterIdMailMailIdRequest{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *PutCharactersCharacterIdMailMailIdRequest) GetLabels() []int64 {
	if o == nil || IsNil(o.Labels) {
		var ret []int64
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutCharactersCharacterIdMailMailIdRequest) GetLabelsOk() ([]int64, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *PutCharactersCharacterIdMailMailIdRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []int64 and assigns it to the Labels field.
func (o *PutCharactersCharacterIdMailMailIdRequest) SetLabels(v []int64) {
	o.Labels = v
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *PutCharactersCharacterIdMailMailIdRequest) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutCharactersCharacterIdMailMailIdRequest) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *PutCharactersCharacterIdMailMailIdRequest) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *PutCharactersCharacterIdMailMailIdRequest) SetRead(v bool) {
	o.Read = &v
}

func (o PutCharactersCharacterIdMailMailIdRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutCharactersCharacterIdMailMailIdRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	return toSerialize, nil
}

type NullablePutCharactersCharacterIdMailMailIdRequest struct {
	value *PutCharactersCharacterIdMailMailIdRequest
	isSet bool
}

func (v NullablePutCharactersCharacterIdMailMailIdRequest) Get() *PutCharactersCharacterIdMailMailIdRequest {
	return v.value
}

func (v *NullablePutCharactersCharacterIdMailMailIdRequest) Set(val *PutCharactersCharacterIdMailMailIdRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutCharactersCharacterIdMailMailIdRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutCharactersCharacterIdMailMailIdRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutCharactersCharacterIdMailMailIdRequest(val *PutCharactersCharacterIdMailMailIdRequest) *NullablePutCharactersCharacterIdMailMailIdRequest {
	return &NullablePutCharactersCharacterIdMailMailIdRequest{value: val, isSet: true}
}

func (v NullablePutCharactersCharacterIdMailMailIdRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutCharactersCharacterIdMailMailIdRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


