/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdContainersLogsGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdContainersLogsGetInner{}

// CorporationsCorporationIdContainersLogsGetInner struct for CorporationsCorporationIdContainersLogsGetInner
type CorporationsCorporationIdContainersLogsGetInner struct {
	Action string `json:"action"`
	// ID of the character who performed the action.
	CharacterId int64 `json:"character_id"`
	// ID of the container
	ContainerId int64 `json:"container_id"`
	// Type ID of the container
	ContainerTypeId int64 `json:"container_type_id"`
	LocationFlag string `json:"location_flag"`
	LocationId int64 `json:"location_id"`
	// Timestamp when this log was created
	LoggedAt time.Time `json:"logged_at"`
	NewConfigBitmask *int64 `json:"new_config_bitmask,omitempty"`
	OldConfigBitmask *int64 `json:"old_config_bitmask,omitempty"`
	// Type of password set if action is of type SetPassword or EnterPassword
	PasswordType *string `json:"password_type,omitempty"`
	// Quantity of the item being acted upon
	Quantity *int64 `json:"quantity,omitempty"`
	// Type ID of the item being acted upon
	TypeId *int64 `json:"type_id,omitempty"`
}

type _CorporationsCorporationIdContainersLogsGetInner CorporationsCorporationIdContainersLogsGetInner

// NewCorporationsCorporationIdContainersLogsGetInner instantiates a new CorporationsCorporationIdContainersLogsGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdContainersLogsGetInner(action string, characterId int64, containerId int64, containerTypeId int64, locationFlag string, locationId int64, loggedAt time.Time) *CorporationsCorporationIdContainersLogsGetInner {
	this := CorporationsCorporationIdContainersLogsGetInner{}
	this.Action = action
	this.CharacterId = characterId
	this.ContainerId = containerId
	this.ContainerTypeId = containerTypeId
	this.LocationFlag = locationFlag
	this.LocationId = locationId
	this.LoggedAt = loggedAt
	return &this
}

// NewCorporationsCorporationIdContainersLogsGetInnerWithDefaults instantiates a new CorporationsCorporationIdContainersLogsGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdContainersLogsGetInnerWithDefaults() *CorporationsCorporationIdContainersLogsGetInner {
	this := CorporationsCorporationIdContainersLogsGetInner{}
	return &this
}

// GetAction returns the Action field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetAction(v string) {
	o.Action = v
}

// GetCharacterId returns the CharacterId field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetCharacterId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetCharacterIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterId, true
}

// SetCharacterId sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetCharacterId(v int64) {
	o.CharacterId = v
}

// GetContainerId returns the ContainerId field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetContainerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ContainerId
}

// GetContainerIdOk returns a tuple with the ContainerId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetContainerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerId, true
}

// SetContainerId sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetContainerId(v int64) {
	o.ContainerId = v
}

// GetContainerTypeId returns the ContainerTypeId field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetContainerTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ContainerTypeId
}

// GetContainerTypeIdOk returns a tuple with the ContainerTypeId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetContainerTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContainerTypeId, true
}

// SetContainerTypeId sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetContainerTypeId(v int64) {
	o.ContainerTypeId = v
}

// GetLocationFlag returns the LocationFlag field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetLocationFlag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationFlag
}

// GetLocationFlagOk returns a tuple with the LocationFlag field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetLocationFlagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationFlag, true
}

// SetLocationFlag sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetLocationFlag(v string) {
	o.LocationFlag = v
}

// GetLocationId returns the LocationId field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetLocationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetLocationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetLocationId(v int64) {
	o.LocationId = v
}

// GetLoggedAt returns the LoggedAt field value
func (o *CorporationsCorporationIdContainersLogsGetInner) GetLoggedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LoggedAt
}

// GetLoggedAtOk returns a tuple with the LoggedAt field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetLoggedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LoggedAt, true
}

// SetLoggedAt sets field value
func (o *CorporationsCorporationIdContainersLogsGetInner) SetLoggedAt(v time.Time) {
	o.LoggedAt = v
}

// GetNewConfigBitmask returns the NewConfigBitmask field value if set, zero value otherwise.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetNewConfigBitmask() int64 {
	if o == nil || IsNil(o.NewConfigBitmask) {
		var ret int64
		return ret
	}
	return *o.NewConfigBitmask
}

// GetNewConfigBitmaskOk returns a tuple with the NewConfigBitmask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetNewConfigBitmaskOk() (*int64, bool) {
	if o == nil || IsNil(o.NewConfigBitmask) {
		return nil, false
	}
	return o.NewConfigBitmask, true
}

// HasNewConfigBitmask returns a boolean if a field has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) HasNewConfigBitmask() bool {
	if o != nil && !IsNil(o.NewConfigBitmask) {
		return true
	}

	return false
}

// SetNewConfigBitmask gets a reference to the given int64 and assigns it to the NewConfigBitmask field.
func (o *CorporationsCorporationIdContainersLogsGetInner) SetNewConfigBitmask(v int64) {
	o.NewConfigBitmask = &v
}

// GetOldConfigBitmask returns the OldConfigBitmask field value if set, zero value otherwise.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetOldConfigBitmask() int64 {
	if o == nil || IsNil(o.OldConfigBitmask) {
		var ret int64
		return ret
	}
	return *o.OldConfigBitmask
}

// GetOldConfigBitmaskOk returns a tuple with the OldConfigBitmask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetOldConfigBitmaskOk() (*int64, bool) {
	if o == nil || IsNil(o.OldConfigBitmask) {
		return nil, false
	}
	return o.OldConfigBitmask, true
}

// HasOldConfigBitmask returns a boolean if a field has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) HasOldConfigBitmask() bool {
	if o != nil && !IsNil(o.OldConfigBitmask) {
		return true
	}

	return false
}

// SetOldConfigBitmask gets a reference to the given int64 and assigns it to the OldConfigBitmask field.
func (o *CorporationsCorporationIdContainersLogsGetInner) SetOldConfigBitmask(v int64) {
	o.OldConfigBitmask = &v
}

// GetPasswordType returns the PasswordType field value if set, zero value otherwise.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetPasswordType() string {
	if o == nil || IsNil(o.PasswordType) {
		var ret string
		return ret
	}
	return *o.PasswordType
}

// GetPasswordTypeOk returns a tuple with the PasswordType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetPasswordTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PasswordType) {
		return nil, false
	}
	return o.PasswordType, true
}

// HasPasswordType returns a boolean if a field has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) HasPasswordType() bool {
	if o != nil && !IsNil(o.PasswordType) {
		return true
	}

	return false
}

// SetPasswordType gets a reference to the given string and assigns it to the PasswordType field.
func (o *CorporationsCorporationIdContainersLogsGetInner) SetPasswordType(v string) {
	o.PasswordType = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetQuantity() int64 {
	if o == nil || IsNil(o.Quantity) {
		var ret int64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetQuantityOk() (*int64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int64 and assigns it to the Quantity field.
func (o *CorporationsCorporationIdContainersLogsGetInner) SetQuantity(v int64) {
	o.Quantity = &v
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetTypeId() int64 {
	if o == nil || IsNil(o.TypeId) {
		var ret int64
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) GetTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.TypeId) {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *CorporationsCorporationIdContainersLogsGetInner) HasTypeId() bool {
	if o != nil && !IsNil(o.TypeId) {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given int64 and assigns it to the TypeId field.
func (o *CorporationsCorporationIdContainersLogsGetInner) SetTypeId(v int64) {
	o.TypeId = &v
}

func (o CorporationsCorporationIdContainersLogsGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdContainersLogsGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["character_id"] = o.CharacterId
	toSerialize["container_id"] = o.ContainerId
	toSerialize["container_type_id"] = o.ContainerTypeId
	toSerialize["location_flag"] = o.LocationFlag
	toSerialize["location_id"] = o.LocationId
	toSerialize["logged_at"] = o.LoggedAt
	if !IsNil(o.NewConfigBitmask) {
		toSerialize["new_config_bitmask"] = o.NewConfigBitmask
	}
	if !IsNil(o.OldConfigBitmask) {
		toSerialize["old_config_bitmask"] = o.OldConfigBitmask
	}
	if !IsNil(o.PasswordType) {
		toSerialize["password_type"] = o.PasswordType
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.TypeId) {
		toSerialize["type_id"] = o.TypeId
	}
	return toSerialize, nil
}

func (o *CorporationsCorporationIdContainersLogsGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"character_id",
		"container_id",
		"container_type_id",
		"location_flag",
		"location_id",
		"logged_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdContainersLogsGetInner := _CorporationsCorporationIdContainersLogsGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdContainersLogsGetInner)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdContainersLogsGetInner(varCorporationsCorporationIdContainersLogsGetInner)

	return err
}

type NullableCorporationsCorporationIdContainersLogsGetInner struct {
	value *CorporationsCorporationIdContainersLogsGetInner
	isSet bool
}

func (v NullableCorporationsCorporationIdContainersLogsGetInner) Get() *CorporationsCorporationIdContainersLogsGetInner {
	return v.value
}

func (v *NullableCorporationsCorporationIdContainersLogsGetInner) Set(val *CorporationsCorporationIdContainersLogsGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdContainersLogsGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdContainersLogsGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdContainersLogsGetInner(val *CorporationsCorporationIdContainersLogsGetInner) *NullableCorporationsCorporationIdContainersLogsGetInner {
	return &NullableCorporationsCorporationIdContainersLogsGetInner{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdContainersLogsGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdContainersLogsGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


