/*
EVE Spring Inebriation (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-05-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SovereigntySystemsAlliance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SovereigntySystemsAlliance{}

// SovereigntySystemsAlliance struct for SovereigntySystemsAlliance
type SovereigntySystemsAlliance struct {
	AllianceId int64 `json:"alliance_id"`
	// Time the claim was made
	ClaimedSince time.Time `json:"claimed_since"`
	CorporationId int64 `json:"corporation_id"`
	Development SovereigntySystemsDevelopment `json:"development"`
	// Whether the system is the capital system of the alliance
	IsCapitalSystem bool `json:"is_capital_system"`
	SovereigntyHub SovereigntySystemsSovereigntyhub `json:"sovereignty_hub"`
}

type _SovereigntySystemsAlliance SovereigntySystemsAlliance

// NewSovereigntySystemsAlliance instantiates a new SovereigntySystemsAlliance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSovereigntySystemsAlliance(allianceId int64, claimedSince time.Time, corporationId int64, development SovereigntySystemsDevelopment, isCapitalSystem bool, sovereigntyHub SovereigntySystemsSovereigntyhub) *SovereigntySystemsAlliance {
	this := SovereigntySystemsAlliance{}
	this.AllianceId = allianceId
	this.ClaimedSince = claimedSince
	this.CorporationId = corporationId
	this.Development = development
	this.IsCapitalSystem = isCapitalSystem
	this.SovereigntyHub = sovereigntyHub
	return &this
}

// NewSovereigntySystemsAllianceWithDefaults instantiates a new SovereigntySystemsAlliance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSovereigntySystemsAllianceWithDefaults() *SovereigntySystemsAlliance {
	this := SovereigntySystemsAlliance{}
	return &this
}

// GetAllianceId returns the AllianceId field value
func (o *SovereigntySystemsAlliance) GetAllianceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AllianceId
}

// GetAllianceIdOk returns a tuple with the AllianceId field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsAlliance) GetAllianceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllianceId, true
}

// SetAllianceId sets field value
func (o *SovereigntySystemsAlliance) SetAllianceId(v int64) {
	o.AllianceId = v
}

// GetClaimedSince returns the ClaimedSince field value
func (o *SovereigntySystemsAlliance) GetClaimedSince() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ClaimedSince
}

// GetClaimedSinceOk returns a tuple with the ClaimedSince field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsAlliance) GetClaimedSinceOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimedSince, true
}

// SetClaimedSince sets field value
func (o *SovereigntySystemsAlliance) SetClaimedSince(v time.Time) {
	o.ClaimedSince = v
}

// GetCorporationId returns the CorporationId field value
func (o *SovereigntySystemsAlliance) GetCorporationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CorporationId
}

// GetCorporationIdOk returns a tuple with the CorporationId field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsAlliance) GetCorporationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorporationId, true
}

// SetCorporationId sets field value
func (o *SovereigntySystemsAlliance) SetCorporationId(v int64) {
	o.CorporationId = v
}

// GetDevelopment returns the Development field value
func (o *SovereigntySystemsAlliance) GetDevelopment() SovereigntySystemsDevelopment {
	if o == nil {
		var ret SovereigntySystemsDevelopment
		return ret
	}

	return o.Development
}

// GetDevelopmentOk returns a tuple with the Development field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsAlliance) GetDevelopmentOk() (*SovereigntySystemsDevelopment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Development, true
}

// SetDevelopment sets field value
func (o *SovereigntySystemsAlliance) SetDevelopment(v SovereigntySystemsDevelopment) {
	o.Development = v
}

// GetIsCapitalSystem returns the IsCapitalSystem field value
func (o *SovereigntySystemsAlliance) GetIsCapitalSystem() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCapitalSystem
}

// GetIsCapitalSystemOk returns a tuple with the IsCapitalSystem field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsAlliance) GetIsCapitalSystemOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCapitalSystem, true
}

// SetIsCapitalSystem sets field value
func (o *SovereigntySystemsAlliance) SetIsCapitalSystem(v bool) {
	o.IsCapitalSystem = v
}

// GetSovereigntyHub returns the SovereigntyHub field value
func (o *SovereigntySystemsAlliance) GetSovereigntyHub() SovereigntySystemsSovereigntyhub {
	if o == nil {
		var ret SovereigntySystemsSovereigntyhub
		return ret
	}

	return o.SovereigntyHub
}

// GetSovereigntyHubOk returns a tuple with the SovereigntyHub field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsAlliance) GetSovereigntyHubOk() (*SovereigntySystemsSovereigntyhub, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SovereigntyHub, true
}

// SetSovereigntyHub sets field value
func (o *SovereigntySystemsAlliance) SetSovereigntyHub(v SovereigntySystemsSovereigntyhub) {
	o.SovereigntyHub = v
}

func (o SovereigntySystemsAlliance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SovereigntySystemsAlliance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alliance_id"] = o.AllianceId
	toSerialize["claimed_since"] = o.ClaimedSince
	toSerialize["corporation_id"] = o.CorporationId
	toSerialize["development"] = o.Development
	toSerialize["is_capital_system"] = o.IsCapitalSystem
	toSerialize["sovereignty_hub"] = o.SovereigntyHub
	return toSerialize, nil
}

func (o *SovereigntySystemsAlliance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alliance_id",
		"claimed_since",
		"corporation_id",
		"development",
		"is_capital_system",
		"sovereignty_hub",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSovereigntySystemsAlliance := _SovereigntySystemsAlliance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSovereigntySystemsAlliance)

	if err != nil {
		return err
	}

	*o = SovereigntySystemsAlliance(varSovereigntySystemsAlliance)

	return err
}

type NullableSovereigntySystemsAlliance struct {
	value *SovereigntySystemsAlliance
	isSet bool
}

func (v NullableSovereigntySystemsAlliance) Get() *SovereigntySystemsAlliance {
	return v.value
}

func (v *NullableSovereigntySystemsAlliance) Set(val *SovereigntySystemsAlliance) {
	v.value = val
	v.isSet = true
}

func (v NullableSovereigntySystemsAlliance) IsSet() bool {
	return v.isSet
}

func (v *NullableSovereigntySystemsAlliance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSovereigntySystemsAlliance(val *SovereigntySystemsAlliance) *NullableSovereigntySystemsAlliance {
	return &NullableSovereigntySystemsAlliance{value: val, isSet: true}
}

func (v NullableSovereigntySystemsAlliance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSovereigntySystemsAlliance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


