/*
EVE Swagger Incineration (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-07-17
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CharactersMercenaryTacticalOperationsDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersMercenaryTacticalOperationsDetail{}

// CharactersMercenaryTacticalOperationsDetail struct for CharactersMercenaryTacticalOperationsDetail
type CharactersMercenaryTacticalOperationsDetail struct {
	DungeonTypeId int64 `json:"dungeon_type_id"`
	// Moment the operation will expire
	Expires time.Time `json:"expires"`
	Id string `json:"id"`
	MercenaryDenId int64 `json:"mercenary_den_id"`
	// Operation's state
	State string `json:"state"`
}

type _CharactersMercenaryTacticalOperationsDetail CharactersMercenaryTacticalOperationsDetail

// NewCharactersMercenaryTacticalOperationsDetail instantiates a new CharactersMercenaryTacticalOperationsDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersMercenaryTacticalOperationsDetail(dungeonTypeId int64, expires time.Time, id string, mercenaryDenId int64, state string) *CharactersMercenaryTacticalOperationsDetail {
	this := CharactersMercenaryTacticalOperationsDetail{}
	this.DungeonTypeId = dungeonTypeId
	this.Expires = expires
	this.Id = id
	this.MercenaryDenId = mercenaryDenId
	this.State = state
	return &this
}

// NewCharactersMercenaryTacticalOperationsDetailWithDefaults instantiates a new CharactersMercenaryTacticalOperationsDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersMercenaryTacticalOperationsDetailWithDefaults() *CharactersMercenaryTacticalOperationsDetail {
	this := CharactersMercenaryTacticalOperationsDetail{}
	return &this
}

// GetDungeonTypeId returns the DungeonTypeId field value
func (o *CharactersMercenaryTacticalOperationsDetail) GetDungeonTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DungeonTypeId
}

// GetDungeonTypeIdOk returns a tuple with the DungeonTypeId field value
// and a boolean to check if the value has been set.
func (o *CharactersMercenaryTacticalOperationsDetail) GetDungeonTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DungeonTypeId, true
}

// SetDungeonTypeId sets field value
func (o *CharactersMercenaryTacticalOperationsDetail) SetDungeonTypeId(v int64) {
	o.DungeonTypeId = v
}

// GetExpires returns the Expires field value
func (o *CharactersMercenaryTacticalOperationsDetail) GetExpires() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value
// and a boolean to check if the value has been set.
func (o *CharactersMercenaryTacticalOperationsDetail) GetExpiresOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expires, true
}

// SetExpires sets field value
func (o *CharactersMercenaryTacticalOperationsDetail) SetExpires(v time.Time) {
	o.Expires = v
}

// GetId returns the Id field value
func (o *CharactersMercenaryTacticalOperationsDetail) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CharactersMercenaryTacticalOperationsDetail) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CharactersMercenaryTacticalOperationsDetail) SetId(v string) {
	o.Id = v
}

// GetMercenaryDenId returns the MercenaryDenId field value
func (o *CharactersMercenaryTacticalOperationsDetail) GetMercenaryDenId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MercenaryDenId
}

// GetMercenaryDenIdOk returns a tuple with the MercenaryDenId field value
// and a boolean to check if the value has been set.
func (o *CharactersMercenaryTacticalOperationsDetail) GetMercenaryDenIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MercenaryDenId, true
}

// SetMercenaryDenId sets field value
func (o *CharactersMercenaryTacticalOperationsDetail) SetMercenaryDenId(v int64) {
	o.MercenaryDenId = v
}

// GetState returns the State field value
func (o *CharactersMercenaryTacticalOperationsDetail) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CharactersMercenaryTacticalOperationsDetail) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CharactersMercenaryTacticalOperationsDetail) SetState(v string) {
	o.State = v
}

func (o CharactersMercenaryTacticalOperationsDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersMercenaryTacticalOperationsDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dungeon_type_id"] = o.DungeonTypeId
	toSerialize["expires"] = o.Expires
	toSerialize["id"] = o.Id
	toSerialize["mercenary_den_id"] = o.MercenaryDenId
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *CharactersMercenaryTacticalOperationsDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dungeon_type_id",
		"expires",
		"id",
		"mercenary_den_id",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersMercenaryTacticalOperationsDetail := _CharactersMercenaryTacticalOperationsDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersMercenaryTacticalOperationsDetail)

	if err != nil {
		return err
	}

	*o = CharactersMercenaryTacticalOperationsDetail(varCharactersMercenaryTacticalOperationsDetail)

	return err
}

type NullableCharactersMercenaryTacticalOperationsDetail struct {
	value *CharactersMercenaryTacticalOperationsDetail
	isSet bool
}

func (v NullableCharactersMercenaryTacticalOperationsDetail) Get() *CharactersMercenaryTacticalOperationsDetail {
	return v.value
}

func (v *NullableCharactersMercenaryTacticalOperationsDetail) Set(val *CharactersMercenaryTacticalOperationsDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersMercenaryTacticalOperationsDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersMercenaryTacticalOperationsDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersMercenaryTacticalOperationsDetail(val *CharactersMercenaryTacticalOperationsDetail) *NullableCharactersMercenaryTacticalOperationsDetail {
	return &NullableCharactersMercenaryTacticalOperationsDetail{value: val, isSet: true}
}

func (v NullableCharactersMercenaryTacticalOperationsDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersMercenaryTacticalOperationsDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


