/*
EVE SKINR Ingenuity (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-08-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CosmeticsSkinrTier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CosmeticsSkinrTier{}

// CosmeticsSkinrTier struct for CosmeticsSkinrTier
type CosmeticsSkinrTier struct {
	// SKINR tier level
	Level int64 `json:"level"`
}

type _CosmeticsSkinrTier CosmeticsSkinrTier

// NewCosmeticsSkinrTier instantiates a new CosmeticsSkinrTier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCosmeticsSkinrTier(level int64) *CosmeticsSkinrTier {
	this := CosmeticsSkinrTier{}
	this.Level = level
	return &this
}

// NewCosmeticsSkinrTierWithDefaults instantiates a new CosmeticsSkinrTier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCosmeticsSkinrTierWithDefaults() *CosmeticsSkinrTier {
	this := CosmeticsSkinrTier{}
	return &this
}

// GetLevel returns the Level field value
func (o *CosmeticsSkinrTier) GetLevel() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinrTier) GetLevelOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *CosmeticsSkinrTier) SetLevel(v int64) {
	o.Level = v
}

func (o CosmeticsSkinrTier) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CosmeticsSkinrTier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	return toSerialize, nil
}

func (o *CosmeticsSkinrTier) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCosmeticsSkinrTier := _CosmeticsSkinrTier{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCosmeticsSkinrTier)

	if err != nil {
		return err
	}

	*o = CosmeticsSkinrTier(varCosmeticsSkinrTier)

	return err
}

type NullableCosmeticsSkinrTier struct {
	value *CosmeticsSkinrTier
	isSet bool
}

func (v NullableCosmeticsSkinrTier) Get() *CosmeticsSkinrTier {
	return v.value
}

func (v *NullableCosmeticsSkinrTier) Set(val *CosmeticsSkinrTier) {
	v.value = val
	v.isSet = true
}

func (v NullableCosmeticsSkinrTier) IsSet() bool {
	return v.isSet
}

func (v *NullableCosmeticsSkinrTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCosmeticsSkinrTier(val *CosmeticsSkinrTier) *NullableCosmeticsSkinrTier {
	return &NullableCosmeticsSkinrTier{value: val, isSet: true}
}

func (v NullableCosmeticsSkinrTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCosmeticsSkinrTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


