/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdWalletsGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdWalletsGetInner{}

// CorporationsCorporationIdWalletsGetInner struct for CorporationsCorporationIdWalletsGetInner
type CorporationsCorporationIdWalletsGetInner struct {
	Balance float64 `json:"balance"`
	Division int64 `json:"division"`
}

type _CorporationsCorporationIdWalletsGetInner CorporationsCorporationIdWalletsGetInner

// NewCorporationsCorporationIdWalletsGetInner instantiates a new CorporationsCorporationIdWalletsGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdWalletsGetInner(balance float64, division int64) *CorporationsCorporationIdWalletsGetInner {
	this := CorporationsCorporationIdWalletsGetInner{}
	this.Balance = balance
	this.Division = division
	return &this
}

// NewCorporationsCorporationIdWalletsGetInnerWithDefaults instantiates a new CorporationsCorporationIdWalletsGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdWalletsGetInnerWithDefaults() *CorporationsCorporationIdWalletsGetInner {
	this := CorporationsCorporationIdWalletsGetInner{}
	return &this
}

// GetBalance returns the Balance field value
func (o *CorporationsCorporationIdWalletsGetInner) GetBalance() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdWalletsGetInner) GetBalanceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *CorporationsCorporationIdWalletsGetInner) SetBalance(v float64) {
	o.Balance = v
}

// GetDivision returns the Division field value
func (o *CorporationsCorporationIdWalletsGetInner) GetDivision() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Division
}

// GetDivisionOk returns a tuple with the Division field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdWalletsGetInner) GetDivisionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Division, true
}

// SetDivision sets field value
func (o *CorporationsCorporationIdWalletsGetInner) SetDivision(v int64) {
	o.Division = v
}

func (o CorporationsCorporationIdWalletsGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdWalletsGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["balance"] = o.Balance
	toSerialize["division"] = o.Division
	return toSerialize, nil
}

func (o *CorporationsCorporationIdWalletsGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"balance",
		"division",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdWalletsGetInner := _CorporationsCorporationIdWalletsGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdWalletsGetInner)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdWalletsGetInner(varCorporationsCorporationIdWalletsGetInner)

	return err
}

type NullableCorporationsCorporationIdWalletsGetInner struct {
	value *CorporationsCorporationIdWalletsGetInner
	isSet bool
}

func (v NullableCorporationsCorporationIdWalletsGetInner) Get() *CorporationsCorporationIdWalletsGetInner {
	return v.value
}

func (v *NullableCorporationsCorporationIdWalletsGetInner) Set(val *CorporationsCorporationIdWalletsGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdWalletsGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdWalletsGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdWalletsGetInner(val *CorporationsCorporationIdWalletsGetInner) *NullableCorporationsCorporationIdWalletsGetInner {
	return &NullableCorporationsCorporationIdWalletsGetInner{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdWalletsGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdWalletsGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


