/*
EVE Spring Inebriation (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-06-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the Faction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Faction{}

// Faction struct for Faction
type Faction struct {
	Faction *SovereigntySystemsFaction `json:"faction,omitempty"`
}

// NewFaction instantiates a new Faction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaction() *Faction {
	this := Faction{}
	return &this
}

// NewFactionWithDefaults instantiates a new Faction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFactionWithDefaults() *Faction {
	this := Faction{}
	return &this
}

// GetFaction returns the Faction field value if set, zero value otherwise.
func (o *Faction) GetFaction() SovereigntySystemsFaction {
	if o == nil || IsNil(o.Faction) {
		var ret SovereigntySystemsFaction
		return ret
	}
	return *o.Faction
}

// GetFactionOk returns a tuple with the Faction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faction) GetFactionOk() (*SovereigntySystemsFaction, bool) {
	if o == nil || IsNil(o.Faction) {
		return nil, false
	}
	return o.Faction, true
}

// HasFaction returns a boolean if a field has been set.
func (o *Faction) HasFaction() bool {
	if o != nil && !IsNil(o.Faction) {
		return true
	}

	return false
}

// SetFaction gets a reference to the given SovereigntySystemsFaction and assigns it to the Faction field.
func (o *Faction) SetFaction(v SovereigntySystemsFaction) {
	o.Faction = &v
}

func (o Faction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Faction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Faction) {
		toSerialize["faction"] = o.Faction
	}
	return toSerialize, nil
}

type NullableFaction struct {
	value *Faction
	isSet bool
}

func (v NullableFaction) Get() *Faction {
	return v.value
}

func (v *NullableFaction) Set(val *Faction) {
	v.value = val
	v.isSet = true
}

func (v NullableFaction) IsSet() bool {
	return v.isSet
}

func (v *NullableFaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaction(val *Faction) *NullableFaction {
	return &NullableFaction{value: val, isSet: true}
}

func (v NullableFaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


