/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-09-30
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the CorporationsProjectsDetailConfigurationscansignature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsProjectsDetailConfigurationscansignature{}

// CorporationsProjectsDetailConfigurationscansignature struct for CorporationsProjectsDetailConfigurationscansignature
type CorporationsProjectsDetailConfigurationscansignature struct {
	// Locations of signatures
	Locations []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner `json:"locations,omitempty"`
	// Signatures to scan
	Signatures []CorporationsProjectsDetailConfigurationmatchersignature `json:"signatures,omitempty"`
}

// NewCorporationsProjectsDetailConfigurationscansignature instantiates a new CorporationsProjectsDetailConfigurationscansignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsProjectsDetailConfigurationscansignature() *CorporationsProjectsDetailConfigurationscansignature {
	this := CorporationsProjectsDetailConfigurationscansignature{}
	return &this
}

// NewCorporationsProjectsDetailConfigurationscansignatureWithDefaults instantiates a new CorporationsProjectsDetailConfigurationscansignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsProjectsDetailConfigurationscansignatureWithDefaults() *CorporationsProjectsDetailConfigurationscansignature {
	this := CorporationsProjectsDetailConfigurationscansignature{}
	return &this
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationscansignature) GetLocations() []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner {
	if o == nil || IsNil(o.Locations) {
		var ret []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationscansignature) GetLocationsOk() ([]CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner, bool) {
	if o == nil || IsNil(o.Locations) {
		return nil, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationscansignature) HasLocations() bool {
	if o != nil && !IsNil(o.Locations) {
		return true
	}

	return false
}

// SetLocations gets a reference to the given []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner and assigns it to the Locations field.
func (o *CorporationsProjectsDetailConfigurationscansignature) SetLocations(v []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner) {
	o.Locations = v
}

// GetSignatures returns the Signatures field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationscansignature) GetSignatures() []CorporationsProjectsDetailConfigurationmatchersignature {
	if o == nil || IsNil(o.Signatures) {
		var ret []CorporationsProjectsDetailConfigurationmatchersignature
		return ret
	}
	return o.Signatures
}

// GetSignaturesOk returns a tuple with the Signatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationscansignature) GetSignaturesOk() ([]CorporationsProjectsDetailConfigurationmatchersignature, bool) {
	if o == nil || IsNil(o.Signatures) {
		return nil, false
	}
	return o.Signatures, true
}

// HasSignatures returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationscansignature) HasSignatures() bool {
	if o != nil && !IsNil(o.Signatures) {
		return true
	}

	return false
}

// SetSignatures gets a reference to the given []CorporationsProjectsDetailConfigurationmatchersignature and assigns it to the Signatures field.
func (o *CorporationsProjectsDetailConfigurationscansignature) SetSignatures(v []CorporationsProjectsDetailConfigurationmatchersignature) {
	o.Signatures = v
}

func (o CorporationsProjectsDetailConfigurationscansignature) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsProjectsDetailConfigurationscansignature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Locations) {
		toSerialize["locations"] = o.Locations
	}
	if !IsNil(o.Signatures) {
		toSerialize["signatures"] = o.Signatures
	}
	return toSerialize, nil
}

type NullableCorporationsProjectsDetailConfigurationscansignature struct {
	value *CorporationsProjectsDetailConfigurationscansignature
	isSet bool
}

func (v NullableCorporationsProjectsDetailConfigurationscansignature) Get() *CorporationsProjectsDetailConfigurationscansignature {
	return v.value
}

func (v *NullableCorporationsProjectsDetailConfigurationscansignature) Set(val *CorporationsProjectsDetailConfigurationscansignature) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsProjectsDetailConfigurationscansignature) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsProjectsDetailConfigurationscansignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsProjectsDetailConfigurationscansignature(val *CorporationsProjectsDetailConfigurationscansignature) *NullableCorporationsProjectsDetailConfigurationscansignature {
	return &NullableCorporationsProjectsDetailConfigurationscansignature{value: val, isSet: true}
}

func (v NullableCorporationsProjectsDetailConfigurationscansignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsProjectsDetailConfigurationscansignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


