/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-11-06
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the ManufactureItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManufactureItem{}

// ManufactureItem struct for ManufactureItem
type ManufactureItem struct {
	ManufactureItem *CorporationsProjectsDetailConfigurationmanufactureitem `json:"manufacture_item,omitempty"`
}

// NewManufactureItem instantiates a new ManufactureItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManufactureItem() *ManufactureItem {
	this := ManufactureItem{}
	return &this
}

// NewManufactureItemWithDefaults instantiates a new ManufactureItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManufactureItemWithDefaults() *ManufactureItem {
	this := ManufactureItem{}
	return &this
}

// GetManufactureItem returns the ManufactureItem field value if set, zero value otherwise.
func (o *ManufactureItem) GetManufactureItem() CorporationsProjectsDetailConfigurationmanufactureitem {
	if o == nil || IsNil(o.ManufactureItem) {
		var ret CorporationsProjectsDetailConfigurationmanufactureitem
		return ret
	}
	return *o.ManufactureItem
}

// GetManufactureItemOk returns a tuple with the ManufactureItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManufactureItem) GetManufactureItemOk() (*CorporationsProjectsDetailConfigurationmanufactureitem, bool) {
	if o == nil || IsNil(o.ManufactureItem) {
		return nil, false
	}
	return o.ManufactureItem, true
}

// HasManufactureItem returns a boolean if a field has been set.
func (o *ManufactureItem) HasManufactureItem() bool {
	if o != nil && !IsNil(o.ManufactureItem) {
		return true
	}

	return false
}

// SetManufactureItem gets a reference to the given CorporationsProjectsDetailConfigurationmanufactureitem and assigns it to the ManufactureItem field.
func (o *ManufactureItem) SetManufactureItem(v CorporationsProjectsDetailConfigurationmanufactureitem) {
	o.ManufactureItem = &v
}

func (o ManufactureItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManufactureItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ManufactureItem) {
		toSerialize["manufacture_item"] = o.ManufactureItem
	}
	return toSerialize, nil
}

type NullableManufactureItem struct {
	value *ManufactureItem
	isSet bool
}

func (v NullableManufactureItem) Get() *ManufactureItem {
	return v.value
}

func (v *NullableManufactureItem) Set(val *ManufactureItem) {
	v.value = val
	v.isSet = true
}

func (v NullableManufactureItem) IsSet() bool {
	return v.isSet
}

func (v *NullableManufactureItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManufactureItem(val *ManufactureItem) *NullableManufactureItem {
	return &NullableManufactureItem{value: val, isSet: true}
}

func (v NullableManufactureItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManufactureItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


