/*
EVE Swagger Incineration (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-06-09
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CorporationsStructuresSovereigntyHubsDetailResourcepower type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsStructuresSovereigntyHubsDetailResourcepower{}

// CorporationsStructuresSovereigntyHubsDetailResourcepower struct for CorporationsStructuresSovereigntyHubsDetailResourcepower
type CorporationsStructuresSovereigntyHubsDetailResourcepower struct {
	// Allocated power
	Allocated int64 `json:"allocated"`
	// Available power
	Available int64 `json:"available"`
}

type _CorporationsStructuresSovereigntyHubsDetailResourcepower CorporationsStructuresSovereigntyHubsDetailResourcepower

// NewCorporationsStructuresSovereigntyHubsDetailResourcepower instantiates a new CorporationsStructuresSovereigntyHubsDetailResourcepower object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsStructuresSovereigntyHubsDetailResourcepower(allocated int64, available int64) *CorporationsStructuresSovereigntyHubsDetailResourcepower {
	this := CorporationsStructuresSovereigntyHubsDetailResourcepower{}
	this.Allocated = allocated
	this.Available = available
	return &this
}

// NewCorporationsStructuresSovereigntyHubsDetailResourcepowerWithDefaults instantiates a new CorporationsStructuresSovereigntyHubsDetailResourcepower object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsStructuresSovereigntyHubsDetailResourcepowerWithDefaults() *CorporationsStructuresSovereigntyHubsDetailResourcepower {
	this := CorporationsStructuresSovereigntyHubsDetailResourcepower{}
	return &this
}

// GetAllocated returns the Allocated field value
func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) GetAllocated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Allocated
}

// GetAllocatedOk returns a tuple with the Allocated field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) GetAllocatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Allocated, true
}

// SetAllocated sets field value
func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) SetAllocated(v int64) {
	o.Allocated = v
}

// GetAvailable returns the Available field value
func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) GetAvailable() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) GetAvailableOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) SetAvailable(v int64) {
	o.Available = v
}

func (o CorporationsStructuresSovereigntyHubsDetailResourcepower) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsStructuresSovereigntyHubsDetailResourcepower) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allocated"] = o.Allocated
	toSerialize["available"] = o.Available
	return toSerialize, nil
}

func (o *CorporationsStructuresSovereigntyHubsDetailResourcepower) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allocated",
		"available",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsStructuresSovereigntyHubsDetailResourcepower := _CorporationsStructuresSovereigntyHubsDetailResourcepower{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsStructuresSovereigntyHubsDetailResourcepower)

	if err != nil {
		return err
	}

	*o = CorporationsStructuresSovereigntyHubsDetailResourcepower(varCorporationsStructuresSovereigntyHubsDetailResourcepower)

	return err
}

type NullableCorporationsStructuresSovereigntyHubsDetailResourcepower struct {
	value *CorporationsStructuresSovereigntyHubsDetailResourcepower
	isSet bool
}

func (v NullableCorporationsStructuresSovereigntyHubsDetailResourcepower) Get() *CorporationsStructuresSovereigntyHubsDetailResourcepower {
	return v.value
}

func (v *NullableCorporationsStructuresSovereigntyHubsDetailResourcepower) Set(val *CorporationsStructuresSovereigntyHubsDetailResourcepower) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsStructuresSovereigntyHubsDetailResourcepower) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsStructuresSovereigntyHubsDetailResourcepower) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsStructuresSovereigntyHubsDetailResourcepower(val *CorporationsStructuresSovereigntyHubsDetailResourcepower) *NullableCorporationsStructuresSovereigntyHubsDetailResourcepower {
	return &NullableCorporationsStructuresSovereigntyHubsDetailResourcepower{value: val, isSet: true}
}

func (v NullableCorporationsStructuresSovereigntyHubsDetailResourcepower) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsStructuresSovereigntyHubsDetailResourcepower) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


