/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FreelanceJobsDetailParameterboolean type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreelanceJobsDetailParameterboolean{}

// FreelanceJobsDetailParameterboolean struct for FreelanceJobsDetailParameterboolean
type FreelanceJobsDetailParameterboolean struct {
	// Boolean value
	Value bool `json:"value"`
}

type _FreelanceJobsDetailParameterboolean FreelanceJobsDetailParameterboolean

// NewFreelanceJobsDetailParameterboolean instantiates a new FreelanceJobsDetailParameterboolean object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreelanceJobsDetailParameterboolean(value bool) *FreelanceJobsDetailParameterboolean {
	this := FreelanceJobsDetailParameterboolean{}
	this.Value = value
	return &this
}

// NewFreelanceJobsDetailParameterbooleanWithDefaults instantiates a new FreelanceJobsDetailParameterboolean object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreelanceJobsDetailParameterbooleanWithDefaults() *FreelanceJobsDetailParameterboolean {
	this := FreelanceJobsDetailParameterboolean{}
	return &this
}

// GetValue returns the Value field value
func (o *FreelanceJobsDetailParameterboolean) GetValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetailParameterboolean) GetValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *FreelanceJobsDetailParameterboolean) SetValue(v bool) {
	o.Value = v
}

func (o FreelanceJobsDetailParameterboolean) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreelanceJobsDetailParameterboolean) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *FreelanceJobsDetailParameterboolean) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreelanceJobsDetailParameterboolean := _FreelanceJobsDetailParameterboolean{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreelanceJobsDetailParameterboolean)

	if err != nil {
		return err
	}

	*o = FreelanceJobsDetailParameterboolean(varFreelanceJobsDetailParameterboolean)

	return err
}

type NullableFreelanceJobsDetailParameterboolean struct {
	value *FreelanceJobsDetailParameterboolean
	isSet bool
}

func (v NullableFreelanceJobsDetailParameterboolean) Get() *FreelanceJobsDetailParameterboolean {
	return v.value
}

func (v *NullableFreelanceJobsDetailParameterboolean) Set(val *FreelanceJobsDetailParameterboolean) {
	v.value = val
	v.isSet = true
}

func (v NullableFreelanceJobsDetailParameterboolean) IsSet() bool {
	return v.isSet
}

func (v *NullableFreelanceJobsDetailParameterboolean) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreelanceJobsDetailParameterboolean(val *FreelanceJobsDetailParameterboolean) *NullableFreelanceJobsDetailParameterboolean {
	return &NullableFreelanceJobsDetailParameterboolean{value: val, isSet: true}
}

func (v NullableFreelanceJobsDetailParameterboolean) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreelanceJobsDetailParameterboolean) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


