/*
EVE Spring Inebriation (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-05-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the Import1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Import1{}

// Import1 struct for Import1
type Import1 struct {
	Import *CorporationsStructuresSovereigntyHubsDetailTransportstateimport `json:"import,omitempty"`
}

// NewImport1 instantiates a new Import1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImport1() *Import1 {
	this := Import1{}
	return &this
}

// NewImport1WithDefaults instantiates a new Import1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImport1WithDefaults() *Import1 {
	this := Import1{}
	return &this
}

// GetImport returns the Import field value if set, zero value otherwise.
func (o *Import1) GetImport() CorporationsStructuresSovereigntyHubsDetailTransportstateimport {
	if o == nil || IsNil(o.Import) {
		var ret CorporationsStructuresSovereigntyHubsDetailTransportstateimport
		return ret
	}
	return *o.Import
}

// GetImportOk returns a tuple with the Import field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Import1) GetImportOk() (*CorporationsStructuresSovereigntyHubsDetailTransportstateimport, bool) {
	if o == nil || IsNil(o.Import) {
		return nil, false
	}
	return o.Import, true
}

// HasImport returns a boolean if a field has been set.
func (o *Import1) HasImport() bool {
	if o != nil && !IsNil(o.Import) {
		return true
	}

	return false
}

// SetImport gets a reference to the given CorporationsStructuresSovereigntyHubsDetailTransportstateimport and assigns it to the Import field.
func (o *Import1) SetImport(v CorporationsStructuresSovereigntyHubsDetailTransportstateimport) {
	o.Import = &v
}

func (o Import1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Import1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Import) {
		toSerialize["import"] = o.Import
	}
	return toSerialize, nil
}

type NullableImport1 struct {
	value *Import1
	isSet bool
}

func (v NullableImport1) Get() *Import1 {
	return v.value
}

func (v *NullableImport1) Set(val *Import1) {
	v.value = val
	v.isSet = true
}

func (v NullableImport1) IsSet() bool {
	return v.isSet
}

func (v *NullableImport1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImport1(val *Import1) *NullableImport1 {
	return &NullableImport1{value: val, isSet: true}
}

func (v NullableImport1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImport1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


