/*
EVE SKINR Ingenuity (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-08-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ParagonHubSkinr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParagonHubSkinr{}

// ParagonHubSkinr struct for ParagonHubSkinr
type ParagonHubSkinr struct {
	Cursor *Cursor `json:"cursor,omitempty"`
	// Page of public SKINR listings
	Listings []ParagonHubSkinrInternalItem `json:"listings"`
}

type _ParagonHubSkinr ParagonHubSkinr

// NewParagonHubSkinr instantiates a new ParagonHubSkinr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParagonHubSkinr(listings []ParagonHubSkinrInternalItem) *ParagonHubSkinr {
	this := ParagonHubSkinr{}
	this.Listings = listings
	return &this
}

// NewParagonHubSkinrWithDefaults instantiates a new ParagonHubSkinr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParagonHubSkinrWithDefaults() *ParagonHubSkinr {
	this := ParagonHubSkinr{}
	return &this
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ParagonHubSkinr) GetCursor() Cursor {
	if o == nil || IsNil(o.Cursor) {
		var ret Cursor
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParagonHubSkinr) GetCursorOk() (*Cursor, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ParagonHubSkinr) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given Cursor and assigns it to the Cursor field.
func (o *ParagonHubSkinr) SetCursor(v Cursor) {
	o.Cursor = &v
}

// GetListings returns the Listings field value
func (o *ParagonHubSkinr) GetListings() []ParagonHubSkinrInternalItem {
	if o == nil {
		var ret []ParagonHubSkinrInternalItem
		return ret
	}

	return o.Listings
}

// GetListingsOk returns a tuple with the Listings field value
// and a boolean to check if the value has been set.
func (o *ParagonHubSkinr) GetListingsOk() ([]ParagonHubSkinrInternalItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Listings, true
}

// SetListings sets field value
func (o *ParagonHubSkinr) SetListings(v []ParagonHubSkinrInternalItem) {
	o.Listings = v
}

func (o ParagonHubSkinr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParagonHubSkinr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	toSerialize["listings"] = o.Listings
	return toSerialize, nil
}

func (o *ParagonHubSkinr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"listings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParagonHubSkinr := _ParagonHubSkinr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varParagonHubSkinr)

	if err != nil {
		return err
	}

	*o = ParagonHubSkinr(varParagonHubSkinr)

	return err
}

type NullableParagonHubSkinr struct {
	value *ParagonHubSkinr
	isSet bool
}

func (v NullableParagonHubSkinr) Get() *ParagonHubSkinr {
	return v.value
}

func (v *NullableParagonHubSkinr) Set(val *ParagonHubSkinr) {
	v.value = val
	v.isSet = true
}

func (v NullableParagonHubSkinr) IsSet() bool {
	return v.isSet
}

func (v *NullableParagonHubSkinr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParagonHubSkinr(val *ParagonHubSkinr) *NullableParagonHubSkinr {
	return &NullableParagonHubSkinr{value: val, isSet: true}
}

func (v NullableParagonHubSkinr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParagonHubSkinr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


