/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-11-06
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
)

// checks if the CorporationsProjectsDetailConfigurationremoterepairarmor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsProjectsDetailConfigurationremoterepairarmor{}

// CorporationsProjectsDetailConfigurationremoterepairarmor struct for CorporationsProjectsDetailConfigurationremoterepairarmor
type CorporationsProjectsDetailConfigurationremoterepairarmor struct {
	// Identity of capsuleer to repair
	Identities []CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner `json:"identities,omitempty"`
	// Location of capsuleer's ship to repair
	Locations []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner `json:"locations,omitempty"`
	// Ship-type of capsuleer's ship to repair
	Ships []CorporationsProjectsDetailConfigurationdamageshipShipsInner `json:"ships,omitempty"`
}

// NewCorporationsProjectsDetailConfigurationremoterepairarmor instantiates a new CorporationsProjectsDetailConfigurationremoterepairarmor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsProjectsDetailConfigurationremoterepairarmor() *CorporationsProjectsDetailConfigurationremoterepairarmor {
	this := CorporationsProjectsDetailConfigurationremoterepairarmor{}
	return &this
}

// NewCorporationsProjectsDetailConfigurationremoterepairarmorWithDefaults instantiates a new CorporationsProjectsDetailConfigurationremoterepairarmor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsProjectsDetailConfigurationremoterepairarmorWithDefaults() *CorporationsProjectsDetailConfigurationremoterepairarmor {
	this := CorporationsProjectsDetailConfigurationremoterepairarmor{}
	return &this
}

// GetIdentities returns the Identities field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) GetIdentities() []CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner {
	if o == nil || IsNil(o.Identities) {
		var ret []CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner
		return ret
	}
	return o.Identities
}

// GetIdentitiesOk returns a tuple with the Identities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) GetIdentitiesOk() ([]CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner, bool) {
	if o == nil || IsNil(o.Identities) {
		return nil, false
	}
	return o.Identities, true
}

// HasIdentities returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) HasIdentities() bool {
	if o != nil && !IsNil(o.Identities) {
		return true
	}

	return false
}

// SetIdentities gets a reference to the given []CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner and assigns it to the Identities field.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) SetIdentities(v []CorporationsProjectsDetailConfigurationdamageshipIdentitiesInner) {
	o.Identities = v
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) GetLocations() []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner {
	if o == nil || IsNil(o.Locations) {
		var ret []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) GetLocationsOk() ([]CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner, bool) {
	if o == nil || IsNil(o.Locations) {
		return nil, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) HasLocations() bool {
	if o != nil && !IsNil(o.Locations) {
		return true
	}

	return false
}

// SetLocations gets a reference to the given []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner and assigns it to the Locations field.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) SetLocations(v []CorporationsProjectsDetailConfigurationcapturefwcomplexLocationsInner) {
	o.Locations = v
}

// GetShips returns the Ships field value if set, zero value otherwise.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) GetShips() []CorporationsProjectsDetailConfigurationdamageshipShipsInner {
	if o == nil || IsNil(o.Ships) {
		var ret []CorporationsProjectsDetailConfigurationdamageshipShipsInner
		return ret
	}
	return o.Ships
}

// GetShipsOk returns a tuple with the Ships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) GetShipsOk() ([]CorporationsProjectsDetailConfigurationdamageshipShipsInner, bool) {
	if o == nil || IsNil(o.Ships) {
		return nil, false
	}
	return o.Ships, true
}

// HasShips returns a boolean if a field has been set.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) HasShips() bool {
	if o != nil && !IsNil(o.Ships) {
		return true
	}

	return false
}

// SetShips gets a reference to the given []CorporationsProjectsDetailConfigurationdamageshipShipsInner and assigns it to the Ships field.
func (o *CorporationsProjectsDetailConfigurationremoterepairarmor) SetShips(v []CorporationsProjectsDetailConfigurationdamageshipShipsInner) {
	o.Ships = v
}

func (o CorporationsProjectsDetailConfigurationremoterepairarmor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsProjectsDetailConfigurationremoterepairarmor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Identities) {
		toSerialize["identities"] = o.Identities
	}
	if !IsNil(o.Locations) {
		toSerialize["locations"] = o.Locations
	}
	if !IsNil(o.Ships) {
		toSerialize["ships"] = o.Ships
	}
	return toSerialize, nil
}

type NullableCorporationsProjectsDetailConfigurationremoterepairarmor struct {
	value *CorporationsProjectsDetailConfigurationremoterepairarmor
	isSet bool
}

func (v NullableCorporationsProjectsDetailConfigurationremoterepairarmor) Get() *CorporationsProjectsDetailConfigurationremoterepairarmor {
	return v.value
}

func (v *NullableCorporationsProjectsDetailConfigurationremoterepairarmor) Set(val *CorporationsProjectsDetailConfigurationremoterepairarmor) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsProjectsDetailConfigurationremoterepairarmor) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsProjectsDetailConfigurationremoterepairarmor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsProjectsDetailConfigurationremoterepairarmor(val *CorporationsProjectsDetailConfigurationremoterepairarmor) *NullableCorporationsProjectsDetailConfigurationremoterepairarmor {
	return &NullableCorporationsProjectsDetailConfigurationremoterepairarmor{value: val, isSet: true}
}

func (v NullableCorporationsProjectsDetailConfigurationremoterepairarmor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsProjectsDetailConfigurationremoterepairarmor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


