/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CharactersCharacterIdMedalsGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersCharacterIdMedalsGetInner{}

// CharactersCharacterIdMedalsGetInner struct for CharactersCharacterIdMedalsGetInner
type CharactersCharacterIdMedalsGetInner struct {
	CorporationId int64 `json:"corporation_id"`
	Date time.Time `json:"date"`
	Description string `json:"description"`
	Graphics []CharactersCharacterIdMedalsGetInnerGraphicsInner `json:"graphics"`
	IssuerId int64 `json:"issuer_id"`
	MedalId int64 `json:"medal_id"`
	Reason string `json:"reason"`
	Status string `json:"status"`
	Title string `json:"title"`
}

type _CharactersCharacterIdMedalsGetInner CharactersCharacterIdMedalsGetInner

// NewCharactersCharacterIdMedalsGetInner instantiates a new CharactersCharacterIdMedalsGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersCharacterIdMedalsGetInner(corporationId int64, date time.Time, description string, graphics []CharactersCharacterIdMedalsGetInnerGraphicsInner, issuerId int64, medalId int64, reason string, status string, title string) *CharactersCharacterIdMedalsGetInner {
	this := CharactersCharacterIdMedalsGetInner{}
	this.CorporationId = corporationId
	this.Date = date
	this.Description = description
	this.Graphics = graphics
	this.IssuerId = issuerId
	this.MedalId = medalId
	this.Reason = reason
	this.Status = status
	this.Title = title
	return &this
}

// NewCharactersCharacterIdMedalsGetInnerWithDefaults instantiates a new CharactersCharacterIdMedalsGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersCharacterIdMedalsGetInnerWithDefaults() *CharactersCharacterIdMedalsGetInner {
	this := CharactersCharacterIdMedalsGetInner{}
	return &this
}

// GetCorporationId returns the CorporationId field value
func (o *CharactersCharacterIdMedalsGetInner) GetCorporationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CorporationId
}

// GetCorporationIdOk returns a tuple with the CorporationId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetCorporationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorporationId, true
}

// SetCorporationId sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetCorporationId(v int64) {
	o.CorporationId = v
}

// GetDate returns the Date field value
func (o *CharactersCharacterIdMedalsGetInner) GetDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetDate(v time.Time) {
	o.Date = v
}

// GetDescription returns the Description field value
func (o *CharactersCharacterIdMedalsGetInner) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetDescription(v string) {
	o.Description = v
}

// GetGraphics returns the Graphics field value
func (o *CharactersCharacterIdMedalsGetInner) GetGraphics() []CharactersCharacterIdMedalsGetInnerGraphicsInner {
	if o == nil {
		var ret []CharactersCharacterIdMedalsGetInnerGraphicsInner
		return ret
	}

	return o.Graphics
}

// GetGraphicsOk returns a tuple with the Graphics field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetGraphicsOk() ([]CharactersCharacterIdMedalsGetInnerGraphicsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Graphics, true
}

// SetGraphics sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetGraphics(v []CharactersCharacterIdMedalsGetInnerGraphicsInner) {
	o.Graphics = v
}

// GetIssuerId returns the IssuerId field value
func (o *CharactersCharacterIdMedalsGetInner) GetIssuerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IssuerId
}

// GetIssuerIdOk returns a tuple with the IssuerId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetIssuerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerId, true
}

// SetIssuerId sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetIssuerId(v int64) {
	o.IssuerId = v
}

// GetMedalId returns the MedalId field value
func (o *CharactersCharacterIdMedalsGetInner) GetMedalId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MedalId
}

// GetMedalIdOk returns a tuple with the MedalId field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetMedalIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MedalId, true
}

// SetMedalId sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetMedalId(v int64) {
	o.MedalId = v
}

// GetReason returns the Reason field value
func (o *CharactersCharacterIdMedalsGetInner) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetReason(v string) {
	o.Reason = v
}

// GetStatus returns the Status field value
func (o *CharactersCharacterIdMedalsGetInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetStatus(v string) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *CharactersCharacterIdMedalsGetInner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdMedalsGetInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CharactersCharacterIdMedalsGetInner) SetTitle(v string) {
	o.Title = v
}

func (o CharactersCharacterIdMedalsGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersCharacterIdMedalsGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["corporation_id"] = o.CorporationId
	toSerialize["date"] = o.Date
	toSerialize["description"] = o.Description
	toSerialize["graphics"] = o.Graphics
	toSerialize["issuer_id"] = o.IssuerId
	toSerialize["medal_id"] = o.MedalId
	toSerialize["reason"] = o.Reason
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *CharactersCharacterIdMedalsGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"corporation_id",
		"date",
		"description",
		"graphics",
		"issuer_id",
		"medal_id",
		"reason",
		"status",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersCharacterIdMedalsGetInner := _CharactersCharacterIdMedalsGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersCharacterIdMedalsGetInner)

	if err != nil {
		return err
	}

	*o = CharactersCharacterIdMedalsGetInner(varCharactersCharacterIdMedalsGetInner)

	return err
}

type NullableCharactersCharacterIdMedalsGetInner struct {
	value *CharactersCharacterIdMedalsGetInner
	isSet bool
}

func (v NullableCharactersCharacterIdMedalsGetInner) Get() *CharactersCharacterIdMedalsGetInner {
	return v.value
}

func (v *NullableCharactersCharacterIdMedalsGetInner) Set(val *CharactersCharacterIdMedalsGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersCharacterIdMedalsGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersCharacterIdMedalsGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersCharacterIdMedalsGetInner(val *CharactersCharacterIdMedalsGetInner) *NullableCharactersCharacterIdMedalsGetInner {
	return &NullableCharactersCharacterIdMedalsGetInner{value: val, isSet: true}
}

func (v NullableCharactersCharacterIdMedalsGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersCharacterIdMedalsGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


