/*
EVE Spring Inebriation (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-05-19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SovereigntySystemsFaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SovereigntySystemsFaction{}

// SovereigntySystemsFaction struct for SovereigntySystemsFaction
type SovereigntySystemsFaction struct {
	FactionId int64 `json:"faction_id"`
}

type _SovereigntySystemsFaction SovereigntySystemsFaction

// NewSovereigntySystemsFaction instantiates a new SovereigntySystemsFaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSovereigntySystemsFaction(factionId int64) *SovereigntySystemsFaction {
	this := SovereigntySystemsFaction{}
	this.FactionId = factionId
	return &this
}

// NewSovereigntySystemsFactionWithDefaults instantiates a new SovereigntySystemsFaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSovereigntySystemsFactionWithDefaults() *SovereigntySystemsFaction {
	this := SovereigntySystemsFaction{}
	return &this
}

// GetFactionId returns the FactionId field value
func (o *SovereigntySystemsFaction) GetFactionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FactionId
}

// GetFactionIdOk returns a tuple with the FactionId field value
// and a boolean to check if the value has been set.
func (o *SovereigntySystemsFaction) GetFactionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FactionId, true
}

// SetFactionId sets field value
func (o *SovereigntySystemsFaction) SetFactionId(v int64) {
	o.FactionId = v
}

func (o SovereigntySystemsFaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SovereigntySystemsFaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["faction_id"] = o.FactionId
	return toSerialize, nil
}

func (o *SovereigntySystemsFaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"faction_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSovereigntySystemsFaction := _SovereigntySystemsFaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSovereigntySystemsFaction)

	if err != nil {
		return err
	}

	*o = SovereigntySystemsFaction(varSovereigntySystemsFaction)

	return err
}

type NullableSovereigntySystemsFaction struct {
	value *SovereigntySystemsFaction
	isSet bool
}

func (v NullableSovereigntySystemsFaction) Get() *SovereigntySystemsFaction {
	return v.value
}

func (v *NullableSovereigntySystemsFaction) Set(val *SovereigntySystemsFaction) {
	v.value = val
	v.isSet = true
}

func (v NullableSovereigntySystemsFaction) IsSet() bool {
	return v.isSet
}

func (v *NullableSovereigntySystemsFaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSovereigntySystemsFaction(val *SovereigntySystemsFaction) *NullableSovereigntySystemsFaction {
	return &NullableSovereigntySystemsFaction{value: val, isSet: true}
}

func (v NullableSovereigntySystemsFaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSovereigntySystemsFaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


