/*
EVE SKINR Ingenuity (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-08-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MilitaryCampaignsDetailCampaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MilitaryCampaignsDetailCampaign{}

// MilitaryCampaignsDetailCampaign struct for MilitaryCampaignsDetailCampaign
type MilitaryCampaignsDetailCampaign struct {
	// Moment the campaign transitioned to a non-active state
	Finished *time.Time `json:"finished,omitempty"`
	Id string `json:"id"`
	// Campaign's progress
	Progress int64 `json:"progress"`
	// Moment the campaign started
	Started *time.Time `json:"started,omitempty"`
	// Campaign's state
	State string `json:"state"`
}

type _MilitaryCampaignsDetailCampaign MilitaryCampaignsDetailCampaign

// NewMilitaryCampaignsDetailCampaign instantiates a new MilitaryCampaignsDetailCampaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMilitaryCampaignsDetailCampaign(id string, progress int64, state string) *MilitaryCampaignsDetailCampaign {
	this := MilitaryCampaignsDetailCampaign{}
	this.Id = id
	this.Progress = progress
	this.State = state
	return &this
}

// NewMilitaryCampaignsDetailCampaignWithDefaults instantiates a new MilitaryCampaignsDetailCampaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMilitaryCampaignsDetailCampaignWithDefaults() *MilitaryCampaignsDetailCampaign {
	this := MilitaryCampaignsDetailCampaign{}
	return &this
}

// GetFinished returns the Finished field value if set, zero value otherwise.
func (o *MilitaryCampaignsDetailCampaign) GetFinished() time.Time {
	if o == nil || IsNil(o.Finished) {
		var ret time.Time
		return ret
	}
	return *o.Finished
}

// GetFinishedOk returns a tuple with the Finished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilitaryCampaignsDetailCampaign) GetFinishedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Finished) {
		return nil, false
	}
	return o.Finished, true
}

// HasFinished returns a boolean if a field has been set.
func (o *MilitaryCampaignsDetailCampaign) HasFinished() bool {
	if o != nil && !IsNil(o.Finished) {
		return true
	}

	return false
}

// SetFinished gets a reference to the given time.Time and assigns it to the Finished field.
func (o *MilitaryCampaignsDetailCampaign) SetFinished(v time.Time) {
	o.Finished = &v
}

// GetId returns the Id field value
func (o *MilitaryCampaignsDetailCampaign) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MilitaryCampaignsDetailCampaign) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MilitaryCampaignsDetailCampaign) SetId(v string) {
	o.Id = v
}

// GetProgress returns the Progress field value
func (o *MilitaryCampaignsDetailCampaign) GetProgress() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *MilitaryCampaignsDetailCampaign) GetProgressOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *MilitaryCampaignsDetailCampaign) SetProgress(v int64) {
	o.Progress = v
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *MilitaryCampaignsDetailCampaign) GetStarted() time.Time {
	if o == nil || IsNil(o.Started) {
		var ret time.Time
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilitaryCampaignsDetailCampaign) GetStartedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *MilitaryCampaignsDetailCampaign) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given time.Time and assigns it to the Started field.
func (o *MilitaryCampaignsDetailCampaign) SetStarted(v time.Time) {
	o.Started = &v
}

// GetState returns the State field value
func (o *MilitaryCampaignsDetailCampaign) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *MilitaryCampaignsDetailCampaign) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *MilitaryCampaignsDetailCampaign) SetState(v string) {
	o.State = v
}

func (o MilitaryCampaignsDetailCampaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MilitaryCampaignsDetailCampaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Finished) {
		toSerialize["finished"] = o.Finished
	}
	toSerialize["id"] = o.Id
	toSerialize["progress"] = o.Progress
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *MilitaryCampaignsDetailCampaign) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"progress",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMilitaryCampaignsDetailCampaign := _MilitaryCampaignsDetailCampaign{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMilitaryCampaignsDetailCampaign)

	if err != nil {
		return err
	}

	*o = MilitaryCampaignsDetailCampaign(varMilitaryCampaignsDetailCampaign)

	return err
}

type NullableMilitaryCampaignsDetailCampaign struct {
	value *MilitaryCampaignsDetailCampaign
	isSet bool
}

func (v NullableMilitaryCampaignsDetailCampaign) Get() *MilitaryCampaignsDetailCampaign {
	return v.value
}

func (v *NullableMilitaryCampaignsDetailCampaign) Set(val *MilitaryCampaignsDetailCampaign) {
	v.value = val
	v.isSet = true
}

func (v NullableMilitaryCampaignsDetailCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableMilitaryCampaignsDetailCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMilitaryCampaignsDetailCampaign(val *MilitaryCampaignsDetailCampaign) *NullableMilitaryCampaignsDetailCampaign {
	return &NullableMilitaryCampaignsDetailCampaign{value: val, isSet: true}
}

func (v NullableMilitaryCampaignsDetailCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMilitaryCampaignsDetailCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


