/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdRolesHistoryGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdRolesHistoryGetInner{}

// CorporationsCorporationIdRolesHistoryGetInner struct for CorporationsCorporationIdRolesHistoryGetInner
type CorporationsCorporationIdRolesHistoryGetInner struct {
	ChangedAt time.Time `json:"changed_at"`
	// The character whose roles are changed
	CharacterId int64 `json:"character_id"`
	// ID of the character who issued this change
	IssuerId int64 `json:"issuer_id"`
	NewRoles []string `json:"new_roles"`
	OldRoles []string `json:"old_roles"`
	RoleType string `json:"role_type"`
}

type _CorporationsCorporationIdRolesHistoryGetInner CorporationsCorporationIdRolesHistoryGetInner

// NewCorporationsCorporationIdRolesHistoryGetInner instantiates a new CorporationsCorporationIdRolesHistoryGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdRolesHistoryGetInner(changedAt time.Time, characterId int64, issuerId int64, newRoles []string, oldRoles []string, roleType string) *CorporationsCorporationIdRolesHistoryGetInner {
	this := CorporationsCorporationIdRolesHistoryGetInner{}
	this.ChangedAt = changedAt
	this.CharacterId = characterId
	this.IssuerId = issuerId
	this.NewRoles = newRoles
	this.OldRoles = oldRoles
	this.RoleType = roleType
	return &this
}

// NewCorporationsCorporationIdRolesHistoryGetInnerWithDefaults instantiates a new CorporationsCorporationIdRolesHistoryGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdRolesHistoryGetInnerWithDefaults() *CorporationsCorporationIdRolesHistoryGetInner {
	this := CorporationsCorporationIdRolesHistoryGetInner{}
	return &this
}

// GetChangedAt returns the ChangedAt field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetChangedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ChangedAt
}

// GetChangedAtOk returns a tuple with the ChangedAt field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetChangedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangedAt, true
}

// SetChangedAt sets field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) SetChangedAt(v time.Time) {
	o.ChangedAt = v
}

// GetCharacterId returns the CharacterId field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetCharacterId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetCharacterIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterId, true
}

// SetCharacterId sets field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) SetCharacterId(v int64) {
	o.CharacterId = v
}

// GetIssuerId returns the IssuerId field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetIssuerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IssuerId
}

// GetIssuerIdOk returns a tuple with the IssuerId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetIssuerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerId, true
}

// SetIssuerId sets field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) SetIssuerId(v int64) {
	o.IssuerId = v
}

// GetNewRoles returns the NewRoles field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetNewRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.NewRoles
}

// GetNewRolesOk returns a tuple with the NewRoles field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetNewRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewRoles, true
}

// SetNewRoles sets field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) SetNewRoles(v []string) {
	o.NewRoles = v
}

// GetOldRoles returns the OldRoles field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetOldRoles() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OldRoles
}

// GetOldRolesOk returns a tuple with the OldRoles field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetOldRolesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OldRoles, true
}

// SetOldRoles sets field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) SetOldRoles(v []string) {
	o.OldRoles = v
}

// GetRoleType returns the RoleType field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetRoleType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleType
}

// GetRoleTypeOk returns a tuple with the RoleType field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdRolesHistoryGetInner) GetRoleTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleType, true
}

// SetRoleType sets field value
func (o *CorporationsCorporationIdRolesHistoryGetInner) SetRoleType(v string) {
	o.RoleType = v
}

func (o CorporationsCorporationIdRolesHistoryGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdRolesHistoryGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["changed_at"] = o.ChangedAt
	toSerialize["character_id"] = o.CharacterId
	toSerialize["issuer_id"] = o.IssuerId
	toSerialize["new_roles"] = o.NewRoles
	toSerialize["old_roles"] = o.OldRoles
	toSerialize["role_type"] = o.RoleType
	return toSerialize, nil
}

func (o *CorporationsCorporationIdRolesHistoryGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"changed_at",
		"character_id",
		"issuer_id",
		"new_roles",
		"old_roles",
		"role_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdRolesHistoryGetInner := _CorporationsCorporationIdRolesHistoryGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdRolesHistoryGetInner)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdRolesHistoryGetInner(varCorporationsCorporationIdRolesHistoryGetInner)

	return err
}

type NullableCorporationsCorporationIdRolesHistoryGetInner struct {
	value *CorporationsCorporationIdRolesHistoryGetInner
	isSet bool
}

func (v NullableCorporationsCorporationIdRolesHistoryGetInner) Get() *CorporationsCorporationIdRolesHistoryGetInner {
	return v.value
}

func (v *NullableCorporationsCorporationIdRolesHistoryGetInner) Set(val *CorporationsCorporationIdRolesHistoryGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdRolesHistoryGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdRolesHistoryGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdRolesHistoryGetInner(val *CorporationsCorporationIdRolesHistoryGetInner) *NullableCorporationsCorporationIdRolesHistoryGetInner {
	return &NullableCorporationsCorporationIdRolesHistoryGetInner{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdRolesHistoryGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdRolesHistoryGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


