/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails{}

// CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails struct for CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
type CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails struct {
	// in seconds
	CycleTime *int64 `json:"cycle_time,omitempty"`
	HeadRadius *float64 `json:"head_radius,omitempty"`
	Heads []CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner `json:"heads"`
	ProductTypeId *int64 `json:"product_type_id,omitempty"`
	QtyPerCycle *int64 `json:"qty_per_cycle,omitempty"`
}

type _CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails

// NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails instantiates a new CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails(heads []CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
	this := CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails{}
	this.Heads = heads
	return &this
}

// NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsWithDefaults instantiates a new CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsWithDefaults() *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
	this := CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails{}
	return &this
}

// GetCycleTime returns the CycleTime field value if set, zero value otherwise.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetCycleTime() int64 {
	if o == nil || IsNil(o.CycleTime) {
		var ret int64
		return ret
	}
	return *o.CycleTime
}

// GetCycleTimeOk returns a tuple with the CycleTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetCycleTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.CycleTime) {
		return nil, false
	}
	return o.CycleTime, true
}

// HasCycleTime returns a boolean if a field has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) HasCycleTime() bool {
	if o != nil && !IsNil(o.CycleTime) {
		return true
	}

	return false
}

// SetCycleTime gets a reference to the given int64 and assigns it to the CycleTime field.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) SetCycleTime(v int64) {
	o.CycleTime = &v
}

// GetHeadRadius returns the HeadRadius field value if set, zero value otherwise.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetHeadRadius() float64 {
	if o == nil || IsNil(o.HeadRadius) {
		var ret float64
		return ret
	}
	return *o.HeadRadius
}

// GetHeadRadiusOk returns a tuple with the HeadRadius field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetHeadRadiusOk() (*float64, bool) {
	if o == nil || IsNil(o.HeadRadius) {
		return nil, false
	}
	return o.HeadRadius, true
}

// HasHeadRadius returns a boolean if a field has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) HasHeadRadius() bool {
	if o != nil && !IsNil(o.HeadRadius) {
		return true
	}

	return false
}

// SetHeadRadius gets a reference to the given float64 and assigns it to the HeadRadius field.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) SetHeadRadius(v float64) {
	o.HeadRadius = &v
}

// GetHeads returns the Heads field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetHeads() []CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner {
	if o == nil {
		var ret []CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner
		return ret
	}

	return o.Heads
}

// GetHeadsOk returns a tuple with the Heads field value
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetHeadsOk() ([]CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Heads, true
}

// SetHeads sets field value
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) SetHeads(v []CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetailsHeadsInner) {
	o.Heads = v
}

// GetProductTypeId returns the ProductTypeId field value if set, zero value otherwise.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetProductTypeId() int64 {
	if o == nil || IsNil(o.ProductTypeId) {
		var ret int64
		return ret
	}
	return *o.ProductTypeId
}

// GetProductTypeIdOk returns a tuple with the ProductTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetProductTypeIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProductTypeId) {
		return nil, false
	}
	return o.ProductTypeId, true
}

// HasProductTypeId returns a boolean if a field has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) HasProductTypeId() bool {
	if o != nil && !IsNil(o.ProductTypeId) {
		return true
	}

	return false
}

// SetProductTypeId gets a reference to the given int64 and assigns it to the ProductTypeId field.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) SetProductTypeId(v int64) {
	o.ProductTypeId = &v
}

// GetQtyPerCycle returns the QtyPerCycle field value if set, zero value otherwise.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetQtyPerCycle() int64 {
	if o == nil || IsNil(o.QtyPerCycle) {
		var ret int64
		return ret
	}
	return *o.QtyPerCycle
}

// GetQtyPerCycleOk returns a tuple with the QtyPerCycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) GetQtyPerCycleOk() (*int64, bool) {
	if o == nil || IsNil(o.QtyPerCycle) {
		return nil, false
	}
	return o.QtyPerCycle, true
}

// HasQtyPerCycle returns a boolean if a field has been set.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) HasQtyPerCycle() bool {
	if o != nil && !IsNil(o.QtyPerCycle) {
		return true
	}

	return false
}

// SetQtyPerCycle gets a reference to the given int64 and assigns it to the QtyPerCycle field.
func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) SetQtyPerCycle(v int64) {
	o.QtyPerCycle = &v
}

func (o CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CycleTime) {
		toSerialize["cycle_time"] = o.CycleTime
	}
	if !IsNil(o.HeadRadius) {
		toSerialize["head_radius"] = o.HeadRadius
	}
	toSerialize["heads"] = o.Heads
	if !IsNil(o.ProductTypeId) {
		toSerialize["product_type_id"] = o.ProductTypeId
	}
	if !IsNil(o.QtyPerCycle) {
		toSerialize["qty_per_cycle"] = o.QtyPerCycle
	}
	return toSerialize, nil
}

func (o *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"heads",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails := _CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails)

	if err != nil {
		return err
	}

	*o = CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails(varCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails)

	return err
}

type NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails struct {
	value *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
	isSet bool
}

func (v NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) Get() *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
	return v.value
}

func (v *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) Set(val *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails(val *CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails {
	return &NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails{value: val, isSet: true}
}

func (v NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


