/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdMedalsIssuedGetInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdMedalsIssuedGetInner{}

// CorporationsCorporationIdMedalsIssuedGetInner struct for CorporationsCorporationIdMedalsIssuedGetInner
type CorporationsCorporationIdMedalsIssuedGetInner struct {
	// ID of the character who was rewarded this medal
	CharacterId int64 `json:"character_id"`
	IssuedAt time.Time `json:"issued_at"`
	// ID of the character who issued the medal
	IssuerId int64 `json:"issuer_id"`
	MedalId int64 `json:"medal_id"`
	Reason string `json:"reason"`
	Status string `json:"status"`
}

type _CorporationsCorporationIdMedalsIssuedGetInner CorporationsCorporationIdMedalsIssuedGetInner

// NewCorporationsCorporationIdMedalsIssuedGetInner instantiates a new CorporationsCorporationIdMedalsIssuedGetInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdMedalsIssuedGetInner(characterId int64, issuedAt time.Time, issuerId int64, medalId int64, reason string, status string) *CorporationsCorporationIdMedalsIssuedGetInner {
	this := CorporationsCorporationIdMedalsIssuedGetInner{}
	this.CharacterId = characterId
	this.IssuedAt = issuedAt
	this.IssuerId = issuerId
	this.MedalId = medalId
	this.Reason = reason
	this.Status = status
	return &this
}

// NewCorporationsCorporationIdMedalsIssuedGetInnerWithDefaults instantiates a new CorporationsCorporationIdMedalsIssuedGetInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdMedalsIssuedGetInnerWithDefaults() *CorporationsCorporationIdMedalsIssuedGetInner {
	this := CorporationsCorporationIdMedalsIssuedGetInner{}
	return &this
}

// GetCharacterId returns the CharacterId field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetCharacterId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetCharacterIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterId, true
}

// SetCharacterId sets field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) SetCharacterId(v int64) {
	o.CharacterId = v
}

// GetIssuedAt returns the IssuedAt field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetIssuedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.IssuedAt
}

// GetIssuedAtOk returns a tuple with the IssuedAt field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetIssuedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuedAt, true
}

// SetIssuedAt sets field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) SetIssuedAt(v time.Time) {
	o.IssuedAt = v
}

// GetIssuerId returns the IssuerId field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetIssuerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IssuerId
}

// GetIssuerIdOk returns a tuple with the IssuerId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetIssuerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerId, true
}

// SetIssuerId sets field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) SetIssuerId(v int64) {
	o.IssuerId = v
}

// GetMedalId returns the MedalId field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetMedalId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MedalId
}

// GetMedalIdOk returns a tuple with the MedalId field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetMedalIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MedalId, true
}

// SetMedalId sets field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) SetMedalId(v int64) {
	o.MedalId = v
}

// GetReason returns the Reason field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) SetReason(v string) {
	o.Reason = v
}

// GetStatus returns the Status field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdMedalsIssuedGetInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CorporationsCorporationIdMedalsIssuedGetInner) SetStatus(v string) {
	o.Status = v
}

func (o CorporationsCorporationIdMedalsIssuedGetInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdMedalsIssuedGetInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["character_id"] = o.CharacterId
	toSerialize["issued_at"] = o.IssuedAt
	toSerialize["issuer_id"] = o.IssuerId
	toSerialize["medal_id"] = o.MedalId
	toSerialize["reason"] = o.Reason
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *CorporationsCorporationIdMedalsIssuedGetInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"character_id",
		"issued_at",
		"issuer_id",
		"medal_id",
		"reason",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdMedalsIssuedGetInner := _CorporationsCorporationIdMedalsIssuedGetInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdMedalsIssuedGetInner)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdMedalsIssuedGetInner(varCorporationsCorporationIdMedalsIssuedGetInner)

	return err
}

type NullableCorporationsCorporationIdMedalsIssuedGetInner struct {
	value *CorporationsCorporationIdMedalsIssuedGetInner
	isSet bool
}

func (v NullableCorporationsCorporationIdMedalsIssuedGetInner) Get() *CorporationsCorporationIdMedalsIssuedGetInner {
	return v.value
}

func (v *NullableCorporationsCorporationIdMedalsIssuedGetInner) Set(val *CorporationsCorporationIdMedalsIssuedGetInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdMedalsIssuedGetInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdMedalsIssuedGetInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdMedalsIssuedGetInner(val *CorporationsCorporationIdMedalsIssuedGetInner) *NullableCorporationsCorporationIdMedalsIssuedGetInner {
	return &NullableCorporationsCorporationIdMedalsIssuedGetInner{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdMedalsIssuedGetInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdMedalsIssuedGetInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


