/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2020-01-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CorporationsCorporationIdFwStatsGetKills type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorporationsCorporationIdFwStatsGetKills{}

// CorporationsCorporationIdFwStatsGetKills Summary of kills done by the given corporation against enemy factions
type CorporationsCorporationIdFwStatsGetKills struct {
	// Last week's total number of kills by members of the given corporation against enemy factions
	LastWeek int64 `json:"last_week"`
	// Total number of kills by members of the given corporation against enemy factions since the corporation enlisted
	Total int64 `json:"total"`
	// Yesterday's total number of kills by members of the given corporation against enemy factions
	Yesterday int64 `json:"yesterday"`
}

type _CorporationsCorporationIdFwStatsGetKills CorporationsCorporationIdFwStatsGetKills

// NewCorporationsCorporationIdFwStatsGetKills instantiates a new CorporationsCorporationIdFwStatsGetKills object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorporationsCorporationIdFwStatsGetKills(lastWeek int64, total int64, yesterday int64) *CorporationsCorporationIdFwStatsGetKills {
	this := CorporationsCorporationIdFwStatsGetKills{}
	this.LastWeek = lastWeek
	this.Total = total
	this.Yesterday = yesterday
	return &this
}

// NewCorporationsCorporationIdFwStatsGetKillsWithDefaults instantiates a new CorporationsCorporationIdFwStatsGetKills object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorporationsCorporationIdFwStatsGetKillsWithDefaults() *CorporationsCorporationIdFwStatsGetKills {
	this := CorporationsCorporationIdFwStatsGetKills{}
	return &this
}

// GetLastWeek returns the LastWeek field value
func (o *CorporationsCorporationIdFwStatsGetKills) GetLastWeek() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastWeek
}

// GetLastWeekOk returns a tuple with the LastWeek field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdFwStatsGetKills) GetLastWeekOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastWeek, true
}

// SetLastWeek sets field value
func (o *CorporationsCorporationIdFwStatsGetKills) SetLastWeek(v int64) {
	o.LastWeek = v
}

// GetTotal returns the Total field value
func (o *CorporationsCorporationIdFwStatsGetKills) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdFwStatsGetKills) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CorporationsCorporationIdFwStatsGetKills) SetTotal(v int64) {
	o.Total = v
}

// GetYesterday returns the Yesterday field value
func (o *CorporationsCorporationIdFwStatsGetKills) GetYesterday() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Yesterday
}

// GetYesterdayOk returns a tuple with the Yesterday field value
// and a boolean to check if the value has been set.
func (o *CorporationsCorporationIdFwStatsGetKills) GetYesterdayOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Yesterday, true
}

// SetYesterday sets field value
func (o *CorporationsCorporationIdFwStatsGetKills) SetYesterday(v int64) {
	o.Yesterday = v
}

func (o CorporationsCorporationIdFwStatsGetKills) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorporationsCorporationIdFwStatsGetKills) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["last_week"] = o.LastWeek
	toSerialize["total"] = o.Total
	toSerialize["yesterday"] = o.Yesterday
	return toSerialize, nil
}

func (o *CorporationsCorporationIdFwStatsGetKills) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"last_week",
		"total",
		"yesterday",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCorporationsCorporationIdFwStatsGetKills := _CorporationsCorporationIdFwStatsGetKills{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCorporationsCorporationIdFwStatsGetKills)

	if err != nil {
		return err
	}

	*o = CorporationsCorporationIdFwStatsGetKills(varCorporationsCorporationIdFwStatsGetKills)

	return err
}

type NullableCorporationsCorporationIdFwStatsGetKills struct {
	value *CorporationsCorporationIdFwStatsGetKills
	isSet bool
}

func (v NullableCorporationsCorporationIdFwStatsGetKills) Get() *CorporationsCorporationIdFwStatsGetKills {
	return v.value
}

func (v *NullableCorporationsCorporationIdFwStatsGetKills) Set(val *CorporationsCorporationIdFwStatsGetKills) {
	v.value = val
	v.isSet = true
}

func (v NullableCorporationsCorporationIdFwStatsGetKills) IsSet() bool {
	return v.isSet
}

func (v *NullableCorporationsCorporationIdFwStatsGetKills) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorporationsCorporationIdFwStatsGetKills(val *CorporationsCorporationIdFwStatsGetKills) *NullableCorporationsCorporationIdFwStatsGetKills {
	return &NullableCorporationsCorporationIdFwStatsGetKills{value: val, isSet: true}
}

func (v NullableCorporationsCorporationIdFwStatsGetKills) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorporationsCorporationIdFwStatsGetKills) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


