/*
EVE Stable Infrastructure (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-12-16
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FreelanceJobsDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreelanceJobsDetail{}

// FreelanceJobsDetail struct for FreelanceJobsDetail
type FreelanceJobsDetail struct {
	AccessAndVisibility FreelanceJobsDetailAccessandvisibility `json:"access_and_visibility"`
	Configuration FreelanceJobsDetailConfiguration `json:"configuration"`
	Contribution *FreelanceJobsDetailContribution `json:"contribution,omitempty"`
	Details FreelanceJobsDetailDetails `json:"details"`
	Id string `json:"id"`
	// Job's last modified
	LastModified time.Time `json:"last_modified"`
	// Job's name
	Name string `json:"name"`
	Progress FreelanceJobsDetailProgress `json:"progress"`
	Reward *FreelanceJobsDetailReward `json:"reward,omitempty"`
	// Job's state
	State string `json:"state"`
}

type _FreelanceJobsDetail FreelanceJobsDetail

// NewFreelanceJobsDetail instantiates a new FreelanceJobsDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreelanceJobsDetail(accessAndVisibility FreelanceJobsDetailAccessandvisibility, configuration FreelanceJobsDetailConfiguration, details FreelanceJobsDetailDetails, id string, lastModified time.Time, name string, progress FreelanceJobsDetailProgress, state string) *FreelanceJobsDetail {
	this := FreelanceJobsDetail{}
	this.AccessAndVisibility = accessAndVisibility
	this.Configuration = configuration
	this.Details = details
	this.Id = id
	this.LastModified = lastModified
	this.Name = name
	this.Progress = progress
	this.State = state
	return &this
}

// NewFreelanceJobsDetailWithDefaults instantiates a new FreelanceJobsDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreelanceJobsDetailWithDefaults() *FreelanceJobsDetail {
	this := FreelanceJobsDetail{}
	return &this
}

// GetAccessAndVisibility returns the AccessAndVisibility field value
func (o *FreelanceJobsDetail) GetAccessAndVisibility() FreelanceJobsDetailAccessandvisibility {
	if o == nil {
		var ret FreelanceJobsDetailAccessandvisibility
		return ret
	}

	return o.AccessAndVisibility
}

// GetAccessAndVisibilityOk returns a tuple with the AccessAndVisibility field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetAccessAndVisibilityOk() (*FreelanceJobsDetailAccessandvisibility, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessAndVisibility, true
}

// SetAccessAndVisibility sets field value
func (o *FreelanceJobsDetail) SetAccessAndVisibility(v FreelanceJobsDetailAccessandvisibility) {
	o.AccessAndVisibility = v
}

// GetConfiguration returns the Configuration field value
func (o *FreelanceJobsDetail) GetConfiguration() FreelanceJobsDetailConfiguration {
	if o == nil {
		var ret FreelanceJobsDetailConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetConfigurationOk() (*FreelanceJobsDetailConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *FreelanceJobsDetail) SetConfiguration(v FreelanceJobsDetailConfiguration) {
	o.Configuration = v
}

// GetContribution returns the Contribution field value if set, zero value otherwise.
func (o *FreelanceJobsDetail) GetContribution() FreelanceJobsDetailContribution {
	if o == nil || IsNil(o.Contribution) {
		var ret FreelanceJobsDetailContribution
		return ret
	}
	return *o.Contribution
}

// GetContributionOk returns a tuple with the Contribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetContributionOk() (*FreelanceJobsDetailContribution, bool) {
	if o == nil || IsNil(o.Contribution) {
		return nil, false
	}
	return o.Contribution, true
}

// HasContribution returns a boolean if a field has been set.
func (o *FreelanceJobsDetail) HasContribution() bool {
	if o != nil && !IsNil(o.Contribution) {
		return true
	}

	return false
}

// SetContribution gets a reference to the given FreelanceJobsDetailContribution and assigns it to the Contribution field.
func (o *FreelanceJobsDetail) SetContribution(v FreelanceJobsDetailContribution) {
	o.Contribution = &v
}

// GetDetails returns the Details field value
func (o *FreelanceJobsDetail) GetDetails() FreelanceJobsDetailDetails {
	if o == nil {
		var ret FreelanceJobsDetailDetails
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetDetailsOk() (*FreelanceJobsDetailDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *FreelanceJobsDetail) SetDetails(v FreelanceJobsDetailDetails) {
	o.Details = v
}

// GetId returns the Id field value
func (o *FreelanceJobsDetail) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FreelanceJobsDetail) SetId(v string) {
	o.Id = v
}

// GetLastModified returns the LastModified field value
func (o *FreelanceJobsDetail) GetLastModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetLastModifiedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModified, true
}

// SetLastModified sets field value
func (o *FreelanceJobsDetail) SetLastModified(v time.Time) {
	o.LastModified = v
}

// GetName returns the Name field value
func (o *FreelanceJobsDetail) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FreelanceJobsDetail) SetName(v string) {
	o.Name = v
}

// GetProgress returns the Progress field value
func (o *FreelanceJobsDetail) GetProgress() FreelanceJobsDetailProgress {
	if o == nil {
		var ret FreelanceJobsDetailProgress
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetProgressOk() (*FreelanceJobsDetailProgress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *FreelanceJobsDetail) SetProgress(v FreelanceJobsDetailProgress) {
	o.Progress = v
}

// GetReward returns the Reward field value if set, zero value otherwise.
func (o *FreelanceJobsDetail) GetReward() FreelanceJobsDetailReward {
	if o == nil || IsNil(o.Reward) {
		var ret FreelanceJobsDetailReward
		return ret
	}
	return *o.Reward
}

// GetRewardOk returns a tuple with the Reward field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetRewardOk() (*FreelanceJobsDetailReward, bool) {
	if o == nil || IsNil(o.Reward) {
		return nil, false
	}
	return o.Reward, true
}

// HasReward returns a boolean if a field has been set.
func (o *FreelanceJobsDetail) HasReward() bool {
	if o != nil && !IsNil(o.Reward) {
		return true
	}

	return false
}

// SetReward gets a reference to the given FreelanceJobsDetailReward and assigns it to the Reward field.
func (o *FreelanceJobsDetail) SetReward(v FreelanceJobsDetailReward) {
	o.Reward = &v
}

// GetState returns the State field value
func (o *FreelanceJobsDetail) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *FreelanceJobsDetail) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *FreelanceJobsDetail) SetState(v string) {
	o.State = v
}

func (o FreelanceJobsDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreelanceJobsDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_and_visibility"] = o.AccessAndVisibility
	toSerialize["configuration"] = o.Configuration
	if !IsNil(o.Contribution) {
		toSerialize["contribution"] = o.Contribution
	}
	toSerialize["details"] = o.Details
	toSerialize["id"] = o.Id
	toSerialize["last_modified"] = o.LastModified
	toSerialize["name"] = o.Name
	toSerialize["progress"] = o.Progress
	if !IsNil(o.Reward) {
		toSerialize["reward"] = o.Reward
	}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *FreelanceJobsDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_and_visibility",
		"configuration",
		"details",
		"id",
		"last_modified",
		"name",
		"progress",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreelanceJobsDetail := _FreelanceJobsDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreelanceJobsDetail)

	if err != nil {
		return err
	}

	*o = FreelanceJobsDetail(varFreelanceJobsDetail)

	return err
}

type NullableFreelanceJobsDetail struct {
	value *FreelanceJobsDetail
	isSet bool
}

func (v NullableFreelanceJobsDetail) Get() *FreelanceJobsDetail {
	return v.value
}

func (v *NullableFreelanceJobsDetail) Set(val *FreelanceJobsDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableFreelanceJobsDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableFreelanceJobsDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreelanceJobsDetail(val *FreelanceJobsDetail) *NullableFreelanceJobsDetail {
	return &NullableFreelanceJobsDetail{value: val, isSet: true}
}

func (v NullableFreelanceJobsDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreelanceJobsDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


