/*
EVE SKINR Ingenuity (ESI) - tranquility

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2026-08-18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package esi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CosmeticsSkinr type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CosmeticsSkinr{}

// CosmeticsSkinr struct for CosmeticsSkinr
type CosmeticsSkinr struct {
	CreatorId int64 `json:"creator_id"`
	// SKINR ID
	Id string `json:"id"`
	Layout CosmeticsSkinrLayout `json:"layout"`
	// SKINR line name
	Line *string `json:"line,omitempty"`
	// SKINR name
	Name string `json:"name"`
	ShipTypeId int64 `json:"ship_type_id"`
	Tier CosmeticsSkinrTier `json:"tier"`
}

type _CosmeticsSkinr CosmeticsSkinr

// NewCosmeticsSkinr instantiates a new CosmeticsSkinr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCosmeticsSkinr(creatorId int64, id string, layout CosmeticsSkinrLayout, name string, shipTypeId int64, tier CosmeticsSkinrTier) *CosmeticsSkinr {
	this := CosmeticsSkinr{}
	this.CreatorId = creatorId
	this.Id = id
	this.Layout = layout
	this.Name = name
	this.ShipTypeId = shipTypeId
	this.Tier = tier
	return &this
}

// NewCosmeticsSkinrWithDefaults instantiates a new CosmeticsSkinr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCosmeticsSkinrWithDefaults() *CosmeticsSkinr {
	this := CosmeticsSkinr{}
	return &this
}

// GetCreatorId returns the CreatorId field value
func (o *CosmeticsSkinr) GetCreatorId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatorId
}

// GetCreatorIdOk returns a tuple with the CreatorId field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetCreatorIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatorId, true
}

// SetCreatorId sets field value
func (o *CosmeticsSkinr) SetCreatorId(v int64) {
	o.CreatorId = v
}

// GetId returns the Id field value
func (o *CosmeticsSkinr) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CosmeticsSkinr) SetId(v string) {
	o.Id = v
}

// GetLayout returns the Layout field value
func (o *CosmeticsSkinr) GetLayout() CosmeticsSkinrLayout {
	if o == nil {
		var ret CosmeticsSkinrLayout
		return ret
	}

	return o.Layout
}

// GetLayoutOk returns a tuple with the Layout field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetLayoutOk() (*CosmeticsSkinrLayout, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Layout, true
}

// SetLayout sets field value
func (o *CosmeticsSkinr) SetLayout(v CosmeticsSkinrLayout) {
	o.Layout = v
}

// GetLine returns the Line field value if set, zero value otherwise.
func (o *CosmeticsSkinr) GetLine() string {
	if o == nil || IsNil(o.Line) {
		var ret string
		return ret
	}
	return *o.Line
}

// GetLineOk returns a tuple with the Line field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetLineOk() (*string, bool) {
	if o == nil || IsNil(o.Line) {
		return nil, false
	}
	return o.Line, true
}

// HasLine returns a boolean if a field has been set.
func (o *CosmeticsSkinr) HasLine() bool {
	if o != nil && !IsNil(o.Line) {
		return true
	}

	return false
}

// SetLine gets a reference to the given string and assigns it to the Line field.
func (o *CosmeticsSkinr) SetLine(v string) {
	o.Line = &v
}

// GetName returns the Name field value
func (o *CosmeticsSkinr) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CosmeticsSkinr) SetName(v string) {
	o.Name = v
}

// GetShipTypeId returns the ShipTypeId field value
func (o *CosmeticsSkinr) GetShipTypeId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ShipTypeId
}

// GetShipTypeIdOk returns a tuple with the ShipTypeId field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetShipTypeIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipTypeId, true
}

// SetShipTypeId sets field value
func (o *CosmeticsSkinr) SetShipTypeId(v int64) {
	o.ShipTypeId = v
}

// GetTier returns the Tier field value
func (o *CosmeticsSkinr) GetTier() CosmeticsSkinrTier {
	if o == nil {
		var ret CosmeticsSkinrTier
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *CosmeticsSkinr) GetTierOk() (*CosmeticsSkinrTier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *CosmeticsSkinr) SetTier(v CosmeticsSkinrTier) {
	o.Tier = v
}

func (o CosmeticsSkinr) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CosmeticsSkinr) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["creator_id"] = o.CreatorId
	toSerialize["id"] = o.Id
	toSerialize["layout"] = o.Layout
	if !IsNil(o.Line) {
		toSerialize["line"] = o.Line
	}
	toSerialize["name"] = o.Name
	toSerialize["ship_type_id"] = o.ShipTypeId
	toSerialize["tier"] = o.Tier
	return toSerialize, nil
}

func (o *CosmeticsSkinr) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"creator_id",
		"id",
		"layout",
		"name",
		"ship_type_id",
		"tier",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCosmeticsSkinr := _CosmeticsSkinr{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCosmeticsSkinr)

	if err != nil {
		return err
	}

	*o = CosmeticsSkinr(varCosmeticsSkinr)

	return err
}

type NullableCosmeticsSkinr struct {
	value *CosmeticsSkinr
	isSet bool
}

func (v NullableCosmeticsSkinr) Get() *CosmeticsSkinr {
	return v.value
}

func (v *NullableCosmeticsSkinr) Set(val *CosmeticsSkinr) {
	v.value = val
	v.isSet = true
}

func (v NullableCosmeticsSkinr) IsSet() bool {
	return v.isSet
}

func (v *NullableCosmeticsSkinr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCosmeticsSkinr(val *CosmeticsSkinr) *NullableCosmeticsSkinr {
	return &NullableCosmeticsSkinr{value: val, isSet: true}
}

func (v NullableCosmeticsSkinr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCosmeticsSkinr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


