#!/bin/sh

# This script generates scopes.go from esi-openapi-spec.json

set -e

SPEC_FILE="esi-openapi-spec.json"
OUTPUT_FILE="scopes.go"

echo "Generating ${OUTPUT_FILE} from ${SPEC_FILE}..."

# Start the Go file content
cat > ${OUTPUT_FILE} << EOL
package goesi

// This file is generated by generate_scopes.sh. DO NOT EDIT.

const (
EOL

# Extract scopes and append to the Go file
jq -r '.components.securitySchemes.OAuth2.flows.authorizationCode.scopes | keys[]' ${SPEC_FILE} | while read -r scope; do
    # Create a constant name from the scope string.
    # ESI uses two naming styles: "esi-wallet.read_character_wallet.v1" and
    # "esi.activity.char:read", so the prefix and the separators both vary.
    const_name=$(echo "${scope}" | sed -E 's/^esi[.:_-]//; s/[.:_-]/ /g' | awk '{
        result = ""
        for (i = 1; i <= NF; i++) {
            result = result toupper(substr($i, 1, 1)) substr($i, 2)
        }
        print result
    }')
    echo "    Scope${const_name} = \"${scope}\"" >> ${OUTPUT_FILE}
done

# End the constants section
echo ")" >> ${OUTPUT_FILE}

gofmt -w ${OUTPUT_FILE}

echo "Successfully generated ${OUTPUT_FILE}."
